
<!--Capturan los valores de la publicación-->

<?php $arr= Load::model('publicacion')->find("conditions: estado_pub='t'","order: id DESC"); ?>

     

<div class="container-fluid">
  <div class="row-fluid">
    <div class="span10">
       
        
        <div align="center">
        <table class='table-bordered'>
        <?php foreach ($arr as $publicacion ) {?>
        
            <tr>
                <td><?php echo "<div align='center'> <h6>".$publicacion->titulo_pub."</h6></div><br>"  ?></td>
            </tr>
            <tr>
                <td><?php echo "<div align='center'> <p align='left'>".$publicacion->detalle_pub."</div>"  ?></td>
            </tr>
            <tr>
                <td>
                    <?php   //BUCAR IMAGENES ASOCIADAS AL ID DE LA PUBLICACION 
                           $imagen= Load::model('contenido')->find("conditions: id_pub=".$publicacion->id);
                           foreach($imagen as $buscar)
                           {
                 
                            
                               echo  Html::img("../default/public/img/upload/".$buscar->ruta_con,"imagen");
                           }
                        
                             
                     ?>
                      
                </td>
            <tr>
                <td><?php echo "<div align='right'> <p align='right'><h5>Publicado el:&nbsp;".$publicacion->fecha_pub."</h5></div>"  ?></td>
            </tr>
<!--            SECCION DE COMENTARIO-->
            <tr>
                <td>
                    <div align="right">
                    <ul class="nav nav-pills nav-stacked">
                      
                        <li class="dropdown active">
                             <a class="dropdown-toggle"data-toggle="dropdown"href="#">
                            Comentar                              
                         <b class="caret active"></b>
                       </a>
                            
                       <ul class="dropdown-menu active">
<!--                           FORMULARIO DE COMENTARIO!-->
                           
                         <li class="dropdown">
                             <div align="right">
                                <ul class="dropdown-menu">
                                    <li>
                                        
                                        
                                        <?php echo Form::open('comentario/ingresar'); ?>
                                            <center>
                                                
                                                <?php echo Form::textarea("comentario.detalle_com");?>
                                                
                                               
                                                <?php echo Form::submit('Comentar',"class='btn btn-primary boton'"); ?>
                                                <?php echo Form::hidden('comentario.id_pub',null , $publicacion->id); ?>
                                                <?php echo Form::hidden('comentario.id_usu',null , Auth::get('id')); ?>
                                                <?php echo Form::hidden('comentario.estado_com',null , 1); ?>
                                                
                                                <?php Form::close(); ?>
                                                
                                            </center>
                                        </form>
                                        
                                        
                                    </li>
                                </ul>
                             </div>  
                            </li>
                           
                       </ul>
                      
                      </li>
                      </div>
                        
                    </ul>
                     
                    
                </td>
            </tr>
                
            <!--                            generar espacion entre las publicaciones-->
           <tr>
                 <td>&nbsp;</td>
           </tr>
            <!--                            generar espacion entre las publicaciones-->
           <tr>
                 <td>&nbsp;</td>
            </tr>
            
<!--              Opcion del administrador-->
                        <?php
                        if(Auth::is_valid())
                        {
                            if (Session::get('rol_usu') == 'administrador')
                            { ?>
                            <tr>
                                <td><div align="right"> <?php  echo Html::link("publicacion/editar/".$publicacion->id,'Editar');?></div>  </td>
    
                            </tr>
                            
                       <?php
                            }
                        }
                        ?>
                        
            
          
        
        <?php } ?>

                            
                          
        </table>
            
        </div>  
    </div>
    <div class="span2">
        <div align="right">
            <table>
                <tr>
                    <td><h6>Publica tus centros turísticos en quality tours</h6></td>
                <tr>
                    <td> <?php echo Html::img("1341096209_publish.png","publicar"); ?> </td>
                </tr>
            </table>
        </div>    
    </div>
  </div>
</div>