
<!--Capturan los valores de la publicación-->

<?php $arr= Load::model('publicacion')->find("conditions: estado_pub='t'"); ?>

     

<div class="container-fluid">
  <div class="row-fluid">
    <div class="span8">
       
        <?php foreach ($arr as $publicacion ) {?>
        <div align="center">
        <table class='table-bordered'>
            <tr>
                <td><?php echo "<div align='center'> <h6>".$publicacion->titulo_pub."</h6></div><br>"  ?></td>
            </tr>
            <tr>
                <td><?php echo "<div align='center'> <p align='left'>".$publicacion->detalle_pub."</div>"  ?></td>
            </tr>
            <tr>
                <td><?php echo "<div align='right'> <p align='right'><h5>Publicado el:&nbsp;".$publicacion->fecha_pub."</h5></div>"  ?></td>
            </tr>
<!--              Opcion del administrador-->
                        <?php
                        if(Auth::is_valid())
                        {
                            if (Session::get('rol_usu') == 'administrador')
                            { ?>
                            <tr>
                                <td><div align="right"> <?php  echo Html::link("publicacion/editar/".$publicacion->id,'Editar');?></div>  </td>
    
                            </tr>

                            <?php
                            }
                        }
                        ?>
                        
            
        </table>
        </div>    
        
        <?php } ?>
        
    </div>
    <div class="span2">
      <!--Body content-->
    </div>
  </div>
</div>