<?php
//Código para el idioma
    if($leng == "en")
    {
        include_once APP_PATH.'libs/en.php';
    }
    else
    {
        include_once APP_PATH.'libs/es.php';
    }
?>    
<div><?php View::content(); 
//CARGA NICEDIT
echo Tag::js("nicedit/nicEdit");
?></div> 

<script type="text/javascript">
    $(document).ready(function (){
        
        $(".boton").click(function(){
            
            
            $(".errorVal").remove();
            
            //ELIMINAMOS ESPACIOS EN BLANCO AL COMIENZO/FINAL
            $(".nombre").val($.trim($(".nombre").val()));
            
            //VALIDACIONES
            if($(".nombre").val() == ""){
                $(".nombre").focus().after("<span class='errorVal'><?php echo $servicio_ingresar_valnom; ?></span>");
                return false;
            }else if($(".precio").val() == "" ){
                $(".precio").focus().after("<span class='errorVal'><?php echo $servicio_ingresarvalpre; ?></span>");
                return false;
            }else if(!$.isNumeric($(".precio").val()) || $(".precio").val() <= 0 || $(".precio").val() == ""){
                $(".precio").focus().after("<span class='errorVal'><?php echo $servicio_ingresarvalpre; ?></span>");
                return false;
            }
            else if($(".tipo").val() == "Seleccione" || $(".tipo").val() == "Select" ){
                $(".tipo").focus().after("<span class='errorVal'>Ingrese el tipo de servicio</span>");
                return false;
            }
        });
        
     //Borrar mensaje de error si el usuario a llenado el campo nombre o precio del servicio
     $(".nombre, .precio").keyup(function ()
     {
        if( $(this).val() != "" )
        {
            $(".errorVal").fadeOut();
            return false;
        }
     });   
     
     
     
 }); //Fin funcion principal
  
</script>

<style>
    .errorVal{
    background-color: #BC1010;
    padding: 6px 12px;
    border-radius: 4px;
    color: white;
    font-weight: bold;
    margin-left: 16px;
    margin-top: 6px;
    position: absolute;
}
.errorVal:before{ /* Este es un truco para crear una flechita */
    content: '';
    border-top: 8px solid transparent;
    border-bottom: 8px solid transparent;
    border-right: 8px solid #BC1010;
    border-left: 8px solid transparent;
    left: -16px;
    position: absolute;
    top: 5px;
}
</style>

 <script type="text/javascript">
 //LINKEO A NICEDIT
  bkLib.onDomLoaded(function() { 
      nicEditors.allTextAreas(
		{buttonList : ['bold','italic','underline','ol','ul','subscript','superscript',
'strikethrough','fontFormat','hr','link','unlink','image','xhtml' ],
		iconsPath : '<?php echo PUBLIC_PATH;?>/javascript/nicedit/nicEditorIcons.gif'})
	});



  </script>

<?php 
    $arr = array(''.$servicio_ingresar_seleccione.''=>''.$servicio_ingresar_seleccione.'','Hostel'=>'Hostel','Bed & Breakfast'=>'Bed & Breakfast','Apart hotel'=>'Apart hotel',
        'Cabaña-Motel'=>'Cabaña-Motel','Camping'=>'Camping','Lodge'=>'Lodge','Resort'=>'Resort',
        'Departamentos'=>'Departamentos','Estancia'=>'Estancia','Hospedaje Rural'=>'Hospedaje Rural',
        'Hostal'=>'Hostal','Hosteria'=>'Hosteria','Hotel'=>'Hotel','Termas'=>'Termas','Otro'=>'Otro');
?>

<fieldset>
<?php echo Form::open('servicio/ingresar/'.$leng) ?>
    <div style="text-align: center">
        <h1> <?php echo $servicio_ingresar_titulo; ?> </h1>
        <table class="table table-bordered">
            <tr>
                <td class="span2"><?php echo $servicio_ingresar_nombre_cli; ?>:&nbsp;</td>
                <td class="span10"><?php echo $nombre_cliente; ?></td>
            </tr>        
            <tr>
                <td><?php echo $servicio_ingresar_name; ?>:&nbsp;</td>
                <td><?php echo Form::text('servicio.nombre_ser', "class='input-medium nombre mask-alphanum' placeholder='" . $servicio_ingresar_tit . "'") ?></td>
            </tr>
            <tr>
                <td><?php echo $servicio_ingresar_detalle; ?>:&nbsp;</td>
                <td>
                    <?php echo Form::textarea('servicio.detalle_ser', 'rows=10 style="width: 100%;" class="detalle"') ?>
                </td>
            </tr>
            <tr>
                <td><?php echo $servicio_ingresar_precio; ?>:&nbsp;</td>
                <td><?php echo Form::text('servicio.precio_ser', "class='input-medium precio mask-pint' placeholder='$' ") ?></td>
            </tr>
            <tr>
                <td><?php echo $servicio_ingresar_tipo; ?> :&nbsp;</td>
                <td><?php echo Form::Select('servicio.tipo_ser', $arr, "class='input-medium tipo'") ?></td>
            </tr>
        </table>
    </div>
    <div align="center">
    <?php echo Form::hidden('servicio.estado_ser','','TRUE')?>
    <?php echo Form::hidden('servicio.visitas_ser','',0)?>
    <?php echo Form::hidden('servicio.id_usu','',Auth::get('id'))?>
    <table>
        <tr>
            <td><?php echo Form::submit(''.$servicio_ingresar_submit.'','class="btn btn-submit boton"') ?>&nbsp;</td>
            
        </tr>         
    </table>
   </div>
<?php echo Form::close() ?> 
</fieldset>