<script type="text/javascript" src="http://maps.googleapis.com/maps/api/js?libraries=places&sensor=false">
    //Esto carga el Places Library, necesario para el autocompletado de direcciones texto
</script>

<?php
//Incluimos el Geocomplete plugin Jquery
echo Tag::js('jquery.geocomplete.min');
?>

<script type="text/javascript">
    $(document).ready(function(){
        $("#geocomplete").geocomplete({
        map: ".map_canvas",
        details: "ul",
        detailsAttribute: "data-geo"
        });
    });
</script>

<style type="text/css">
  html { height: 100% }
  body { height: 100%; margin: 0px; padding: 0px }
  #map_canvas { height: 100% }
</style>
    
<div align="center">
    <table>
        <tr>
            <td>Centro turístico:&nbsp;</td>
            <td><?php echo $nombre_cliente; ?></td>
        </tr>
    </table>
    <br><h6>Indique la ubicación de su destino turístico</h6>
        
    <form>
        <table>
            <tr>
                <td>
                    
                </td>
                <td>
                    <input id="geocomplete" type="text" placeholder="Ingrese una ubicación..." value="" /><br>
                    <input id="find" type="button" value="Buscar" class="btn btn-primary"/>
                    <hr>
                    <ul>
                        <li>Coordenadas: <span data-geo="location"></span></li>
                        <li>Calle: <span data-geo="route"></span></li>
                        <li>Número: <span data-geo="street_number"></span></li>
                        <li>Código Postal: <span data-geo="postal_code"></span></li>
                        <li>Ciudad: <span data-geo="locality"></span></li>
                        <li>Codigo País: <span data-geo="country_short"></span></li>
                        <li>Región: <span data-geo="administrative_area_level_1"></span></li>
                    </ul>
                    <hr>
                </td>
            </tr>
        </table>    
    </form>
        
        
        
    <div class="map_canvas" style="width:400px; height:400px"></div>
        
</div>