
<div><?php View::content() ?></div> 

<script type="text/javascript">
    //Validación con jquery
    //El siguiente script valida que los campos no estén vacios y el formato del RUT
$(document).ready(function () {
    var rutreg = /^\d{1,2}\.\d{3}\.\d{3}[-][0-9kK]{1}$/;
    $(".boton").click(function (){
        $(".errorVal").remove();
        
        if( $(".seleccion_usuario").val() == "" )
        {
            $(".seleccion_usuario").focus().after("<span class='errorVal'>Seleccione un usuario</span>");
            return false;
        }
    });
    
    
    //Para el caso del listbox, no se puede borrar el error de validación con keyup
    //Ya que no es un textbox, usamos el metodo blur
    $(".seleccion_usuario").blur(function()
    {
        if( $(this).val() != "" )
        {
            $(".errorVal").fadeOut();
            return false;
        }
    });
    
});
</script>

<!--
El CSS a continuación da estilo a los mensaje de error en la validación
, no se usó "error" ya que kumbia ya tiene un estilo para esa clase, en su
reemplazo se uso 'errorVal'.
-->

<style>
    .errorVal{
    background-color: #BC1010;
    padding: 6px 12px;
    border-radius: 4px;
    color: white;
    font-weight: bold;
    margin-left: 16px;
    margin-top: 6px;
    position: absolute;
}
.errorVal:before{ /* Este es un truco para crear una flechita */
    content: '';
    border-top: 8px solid transparent;
    border-bottom: 8px solid transparent;
    border-right: 8px solid #BC1010;
    border-left: 8px solid transparent;
    left: -16px;
    position: absolute;
    top: 5px;
}
</style>


<br>
<fieldset>
<?php echo Form::open('administrador/ingresar') ?>
    <div align="center">
        <h1> Convertir Usuario-Administrador </h1>
        <table>
     <tr>
        <td>Usuario</td>
        <td><?php echo  Form::dbSelect('administrador.id','username_usu',array('usuario','find',"rol_usu='turista'"),'-Seleccione-','class=seleccion_usuario') ?></td>
    </tr>
    

</table>
    </div>
    <div align="center">
    <table>
        <tr>
            <td><?php echo Form::submit('Ingresar Administrador','class="btn btn-submit boton"') ?>&nbsp;</td>
            <td><?php echo Form::reset('Reiniciar','class="btn btn-info"')?></td>
        </tr>         
    </table>
   </div>

<?php echo Form::hidden('administrador.estado_usu',null , 1); ?>

<?php echo Form::close() ?> 
    </fieldset>

