<?php
//Código para el idioma
    if($leng == "en")
    {
        include_once APP_PATH.'libs/en.php';
    }
    else
    {
        include_once APP_PATH.'libs/es.php';
    }
?>    

<div class="container-fluid">
  <div class="row-fluid">
    <div class="span10">
     <?php if ($cont != 0)
           {
             for($i=0;$i<=$contador-1; $i++)
             {
     ?>
        <div align="center">
            <table class='well' width="600px">
                <tr>
                    <td><?php echo "<br><div align='center' class='titulo_pub1'><h4>".$titulo[$i]."</h4></div><br>"  ?></td>
                </tr>
                <tr>
                    <td><?php echo "<div align='center' class='detalle_pub1'> <p align='left'>".$detalle[$i]."</div>"  ?></td>
                </tr>
                <tr>
                    <td><?php if($contenido[$i] != 0)
                              {
                                echo "<center>";
                                echo  Html::img("../default/public/img/upload/".$ruta[$i],"imagen","width=300 height=200");
                                echo "</center>";
                              }          
                         ?>
                    </td>
                <tr>
                    <td><?php echo "<div align='right'> <p align='right'><h6>".$fecha[$i]."&nbsp;</h6></div>"  ?></td>
               </tr>
               <?php
               if(Auth::is_valid())
                {
                    if (Session::get('rol_usu') == 'administrador' || Session::get('rol_usu') == 'turista' || Session::get('rol_usu') == 'cliente')
                    { 
               ?>
                        <?php
                    }
                }
                        ?>
<!--              Opcion del administrador-->
                        <?php
                        if(Auth::is_valid())
                        {
                            if (Session::get('rol_usu') == 'administrador')
                                { ?>
                                    <tr>
                                        <td><div align="right"> <?php  echo Html::link("publicacion/editar/".$id[$i].'/'.$e_editar_string,''.$editar_string.'');?> - <?php echo Html::link("publicacion/eliminar/".$id[$i],''.$eliminar_string.''); ?> -<?php echo Html::link("publicacion/traducir/".$id[$i].''.$publicacion_index_idiom.'',''.$publicacion_index_traducir.'')?></div>  </td>
                                    </tr>
                                <?php
                                }
                        }
                        ?>
             </table>
        </div>  
        <?php }
          }?>
        
    </div>
    <div class="span2">
        <div align="right">
            <table>
                <tr>
                    <td><h6>Publica tus centros turísticos en quality tours</h6></td>
                <tr>
                    <td> <?php echo Html::img("1341096209_publish.png","publicar"); ?> </td>
                </tr>
            </table>
        </div>
        <h6>Los más visitados</h6>
        <?php
         for ($i=0;$i<=$indice-1;$i++)
         {
            $cont = $i+1;
            echo "<table>
                  <tr>
                  <td><span class='badge badge-info'>".$cont."</span>&nbsp;<font size='1'>".Html::link("cliente/detalle/".$id_cliente[$i]."/es",$nombre_cli[$i],"target='_blank'")."</font></td>
                  </tr>
                  </table>
                   ";
         }
        ?>
    </div>
  </div>
</div>