
<!--Capturan los valores de la publicación-->
<?php $arr= Load::model('publicacion')->find("conditions: estado_pub='t'","order: id DESC"); ?>
<div class="container-fluid">
  <div class="row-fluid">
    <div class="span10">
       
        
        <div align="center">
        <table class='table-bordered'>
        <?php foreach ($arr as $publicacion ) {?>
        
            <tr>
                <td><?php echo "<div align='center'> <h6>".$publicacion->titulo_pub."</h6></div><br>"  ?></td>
            </tr>
            <tr>
                <td><?php echo "<div align='center'> <p align='left'>".$publicacion->detalle_pub."</div>"  ?></td>
            </tr>
            <tr>
                <td>
                  <?php   //BUCAR IMAGENES ASOCIADAS AL ID DE LA PUBLICACION 
                      $imagen= Load::model('contenido')->find("conditions: id_pub=".$publicacion->id);
                       foreach($imagen as $buscar)
                       {
                           echo  Html::img("../default/public/img/upload/".$buscar->ruta_con,"imagen","width=300 heiht=200");
                       }    
                             
                  ?>
                      
                </td>
            <tr>
                <td><?php echo "<div align='right'> <p align='right'><h5>Publicado el:&nbsp;".$publicacion->fecha_pub."</h5></div>"  ?></td>
            </tr>
            <?php
                        if(Auth::is_valid())
                        {
                            if (Session::get('rol_usu') == 'administrador' || Session::get('rol_usu') == 'turista' || Session::get('rol_usu') == 'cliente')
                        { ?>
            
            <tr>
            <td>
               <div align="right">
               <ul class="nav nav-pills nav-stacked">
                  <li class="dropdown active">
<!--                            SE CUENTAN LOS COMENTARIOS-->
                        <?php $contador = Load::model('comentario')->count("estado_com = 't' and id_pub=".$publicacion->id);?>
                          <a class="dropdown-toggle"data-toggle="dropdown"href="#">
                        <?php echo $contador ?> comentarios - Comentar      
                          <b class="caret active"></b>
                          </a>   
                       <ul class="dropdown-menu active">
<!--                           FORMULARIO DE COMENTARIO!-->
                           
                       <li class="dropdown">
                       <div align="right">
                       <ul class="dropdown-menu">
                   <li>
<!--                         SECCION DE LISTAR COMENTARIOS-->       
                           <?php  
                           $comentario= Load::model('comentario')->find("conditions: estado_com='t' and id_pub=".$publicacion->id);
                           foreach($comentario as $buscar) 
                           {?>    
                           <?php 
//                             CAPTURAR EL NOMBRE DE USUARIO
                                    Load::model('usuario');
                                    $usuario = new Usuario();
                                    $usuario->find($buscar->id_usu);
                                    $username = $usuario->username_usu;  
                            ?>        
                            <div align="left">  <?php echo"<font color='#777777'>".$username."&nbsp; dice:</font><br>".$buscar->detalle_com."<br> <div align='right'><font color='#777777'>".$buscar->fecha_com."</font></div><hr>"; ?> </div>  
                           <?php } ?>
<!--                            FORMULARIO DE COMENTARIO-->
                           <?php echo Form::open('comentario/ingresar'); ?>
                           <center>   
                                 <?php
                                 $Fecha= date('d-m-Y');
                                 //$Hora= date('H:i:s');
                                //futuro uso  $cadena = $Fecha.$Hora;
                                 ?>
                               
                                 <?php echo Form::textarea("comentario.detalle_com");?>
                                 <?php echo Form::submit('Comentar',"class='btn btn-primary boton'"); ?>
                                 <?php echo Form::hidden('comentario.id_pub',null , $publicacion->id); ?>
                                 <?php echo Form::hidden('comentario.id_usu',null , Auth::get('id')); ?>
                                 <?php echo Form::hidden('comentario.estado_com',null , 1); ?>
                                 <?php echo Form::hidden('comentario.fecha_com',null , $Fecha); ?>
                                                
                           <?php Form::close(); ?>   
                           </center>       
                            </li>
                                </ul>
                             </div>  
                           </li>
                      </ul>
                    </li>
                  </div>
                </td>
            </tr>
             <?php
                            }
                        }
                        ?>
<!--              Opcion del administrador-->
                        <?php
                        if(Auth::is_valid())
                        {
                            if (Session::get('rol_usu') == 'administrador')
                            { ?>
                            <tr>
                                <td><div align="right"> <?php  echo Html::link("publicacion/editar/".$publicacion->id,'Editar');?></div>  </td>
    
                            </tr>
                            
                        <?php
                            }
                        }
                        ?>
                        
            
          
        
        <?php } ?>

                            
                          
        </table>
            
        </div>  
    </div>
    <div class="span2">
        <div align="right">
            <table>
                <tr>
                    <td><h6>Publica tus centros turísticos en quality tours</h6></td>
                <tr>
                    <td> <?php echo Html::img("1341096209_publish.png","publicar"); ?> </td>
                </tr>
            </table>
        </div>    
    </div>
  </div>
</div>