<?php
 echo Tag::js('rating'); 
 echo Tag::js('jquery.tagcanvas.min'); 
 echo Tag::js('jquery.truncator'); 
//Código para el idioma
    if($leng == "en")
    {
        include_once APP_PATH.'libs/en.php';
    }
    else
    {
        include_once APP_PATH.'libs/es.php';
    }
?>    
<!--estilo css para estrellas de muestra-->

<script type="text/javascript">
    $(document).ready(function() { //INICIO DEL TAG-CLOUD
        if( ! $('#myCanvas').tagcanvas({
            textColour : '#000000',
            outlineThickness : 3,
            maxSpeed : 0.15,
            depth : 0.75,
            shape : 'hring',
            lock : 'x',
            zoom : 1.1
        })) {
            // TagCanvas failed to load
            $('#myCanvasContainer').hide();
        }
        // your other jQuery stuff here...
    });
</script>
<script>
 /***Limitar tamaño texto***/
 
jQuery(document).ready(function(){

$(function() {
      $('.texto-cortado').truncate({
          max_length: 180,
          more: '<?php echo $index_vermas; ?>',
          less: '<?php echo $index_vermenos; ?>'
      });
    });


});

</script>    
<div class="container-fluid">
  <div class="row-fluid">
      <div class="span2 well" style="background-color: #f9ffff;">
          <?php echo Html::img("ads1.png"); ?>
          
      </div>
    <div class="span7">
     <?php if ($cont != 0)
           {
             for($i=0;$i<=$contador-1; $i++)
             {
     ?>
        <div style='text-align:center;'>
            <table class="well span12" style="background-color: #f9ffff; ">
                <tr>
                    <td><?php echo "<br><div style='text-align:center;' class='titulo_pub1'><h4>".$titulo[$i]."</h4></div><br>"  ?></td>
                </tr>
                <tr>
                    <td><?php echo "<div class='detalle_pub1 texto-cortado' > <p  style='text-align:justify;'>".$detalle[$i]."</p></div>"  ?></p></td>
                </tr>
                <tr>
                    <td></td>
                </tr>
                <tr>
                    <td style='text-align:center;'><?php if($contenido[$i] != 0)
                              {
                                echo  Html::img("upload/".$ruta[$i],"imagen","width=300 height=200");
                              }          
                         ?>
                    </td>
                <tr>
                    <td><?php echo "<div style='text-align:right;'> <p style='text-align:right;'><h6>".$fecha[$i]."&nbsp;</h6></div>"  ?></td>
               </tr>
               <?php
               if(Auth::is_valid())
                {
                    if (Session::get('rol_usu') == 'administrador' || Session::get('rol_usu') == 'turista' || Session::get('rol_usu') == 'cliente')
                    { 
               ?>
                        <?php
                    }
                }
                        ?>
<!--              Opcion del administrador-->
                        <?php
                        if(Auth::is_valid())
                        {
                            if (Session::get('rol_usu') == 'administrador')
                                { ?>
                                    <tr>
                                        <td><div style='text-align:right;'> <?php  echo Html::link("publicacion/editar/".$id_pub[$i].'/'.$e_editar_string,''.$editar_string.'');?> - <?php echo Html::link("publicacion/eliminar/".$id_pub[$i],''.$eliminar_string.''); ?> - <?php echo Html::link("publicacion/traducir/".$id_pub[$i].''.$publicacion_index_idiom.'',''.$publicacion_index_traducir.'')?></div>  </td>
                                    </tr>
                                <?php
                                }
                        }
                        ?>
             </table>
        </div>  
        <?php }
          }?>
        
    </div>
    <div class="span3 well" style="background-color: #f9ffff;">
       
            
                        <div id="myCanvasContainer">
                            <canvas width="170" height="200" id="myCanvas">
                                
<!--                                <p>Anything in here will be replaced on browsers that support the canvas element</p>-->
                                <ul>
                                    <?php 
                                    for ($i=0 ; $i < $contador_cat ; $i++)
                                    {
                                        echo "<li>".Html::link('busqueda/buscando_tc/'.urlencode($cat[$i])."/".$leng, $cat[$i])."</li>";
                                        //echo "<li>".Html::link('busqueda/buscando/'.$leng."?string=".$cat[$i], $cat[$i])."</li>";
                                    }
                                    ?>
                                </ul>
                            </canvas>
                        </div>
                    
        
        <hr style=" border-top: 1px dashed; background-color: #f9ffff;">
        <h6>  <?php echo Html::link("index/ranking/".$leng,$index_titulo_1) ?> </h6>
        <?php
         for ($i=0;$i<=$indice-1;$i++)
         {
            echo "<table>";
            $cont = $i+1;
            echo "
                  <tr>
                  <td style='font-size:11px;'><span class='badge badge-info'>".$cont."</span>&nbsp;".Html::link("cliente/detalle/".$id_cliente[$i]."/".$leng,$nombre_cli[$i],"target='_self'")."</td>
                  </tr>                
                   ";
         }
         echo "</table>";
        ?>
       <hr style=" border-top: 1px dashed; background-color: #f9ffff;">
        <h6> <?php echo Html::link("index/ranking/".$leng,$index_titulo_3,'style=""') ?></h6>
        <?php
        
         $cont = 0; 
         echo "<table>";
         for ($i=0;$i<=$contadors-1;$i++)
         {
            $cont = $i+1;?>

       <?php     echo "
                  <tr>
                  <td style='font-size:11px;'><span class='badge badge-info'>".$cont."</span>&nbsp;".Html::link("cliente/detalle/".$id[$i]."/".$leng,$id_cli_cal[$i],"target='_self'")." <b> ".number_format($valor_cal[$i], $decimals = 1)."</b>
                  </td>
                 </tr>";
         }
         echo "</table>";
        
         ?>
    </div>
  </div>
</div>
