<?php
//Código para el idioma
if ($leng == "en") {
    include_once APP_PATH . 'libs/en.php';
} else {
    include_once APP_PATH . 'libs/es.php';
}
?>   
<div><?php View::content(); ?></div>

<div class="container-fluid">
    <div class="row-fluid">
      <?php View::partial('publicidad_vertical'); ?>
        <div class="span5" style="text-align: center;">
            <h4><b><?php echo $index_titulo_1; ?></b></h4>
<table class="table table-hover table-bordered">
<?php
for ($i = 0; $i <= $indice - 1; $i++) {
    $cont = $i + 1;
    ?>

                
                    <tr>
                        <td style="height: 30px;"><span class='badge badge-info'><?php echo $cont ?></span>&nbsp  <?php echo Html::link("cliente/detalle/" . $id_cliente[$i] . "/" . $leng, $nombre_cli[$i], "target='_self'") ?> <?php echo "&nbsp;-&nbsp;" . $visitas[$i]."&nbsp; ".$cliente_detalle_visitas; ?></td>


                    </tr>
                


<?php }
?></table>


        </div>
        <div class="span5" style="text-align: center;">
            <h4><b><?php echo $index_titulo_3; ?></b></h4>
<?php
$cont = 0;
echo "<table class='table table-hover table-bordered'>";
for ($i = 0; $i <= $contadors - 1; $i++) {
    $cont = $i + 1;
                  echo "<tr>
                  <td><span class='badge badge-info'>" . $cont . "</span>&nbsp;" . Html::link("cliente/detalle/" . $id[$i] . "/" . $leng, $id_cli_cal[$i], "target='_self'") . " <b> " . number_format($valor_cal[$i], $decimals = 1) . "</b>
                  </td>
                 
                 
                 <td><div class='stars0 stars" . number_format($valor_cal[$i], $decimals = 0) . "' 
                     title='" . number_format($valor_cal[$i], $decimals = 2) . "'></div> </td>
                 </tr>";
                  
}
echo "</table>";
?>

        </div>
    </div>
</div>