<div><?php View::content() ?></div> 


<center><h2>Condiciones del servicio</center></h2>
<div style="text-align: center;">
<p align="justify">
El presente documento llamado “Condiciones del servicio” rige la relación entre Quality tours S.A (en adelante “Quality tours”) y los anfitriones de centros turísticos en cualquiera de los tres planes disponibles que hubiesen elegido en esta plataforma web.

Si no está de acuerdo con las Condiciones del servicio no podrá utilizar el sitio.</p>
<br>
<p align="justify"><b>1. Uso del sitio web</b></p>
<p align="justify">Al aceptar las condiciones del servicio también aceptas expresamente las condiciones de uso.</p>

<p align="justify">Las condiciones del servicio podrán ser modificados, información que se le dará a conocer a los usuarios mediante correo electrónico y notificaciones en la plataforma y para los cuales los anfitriones tendrán un plazo de diez días hábiles, a contar de la fecha de información, para realizar reclamos y/o observaciones, esto último no rige para los anfitriones de centros turísticos que usen en plan free</p>
<br>
<p align="justify"><b>2. Planes Quality Tours</b></p>
<p align="justify">El servicio de Quality tours consta de tres planes:</p>
<p align="justify"><b>1.- Plan free:</b> Este plan tiene limitaciones respecto a la cantidad de servicios a publicar, La cual es de solo 2 y 2 imágenes asociadas al centro turístico</p>
<p align="justify"><b>2.- Plan normal:</b> Este plan tiene limitaciones respecto a la publicación de contenido y a la cantidad de servicios posibles a publicitar. En este caso, solo se permitirá publicar cuatro servicios y  5 fotos relacionadas al centro turístico </p>
<p align="justify"><b>3.- Plan plus:</b> Este plan tiene un amplio contenido que publicitar ya que podrá publicitar hasta 15 servicios por centro turístico y 30 imágenes asociadas al centro turístico</p>
<br><p align="justify"><b>3.- De la suscripción</b></p>
<p align="justify">Para poder adquirir una suscripción el anfitrión del centro turístico tendrá que tener 18 años de edad y ser de nacionalidad Chilena.
La suscripción, en el caso del plan normal y free, tendrá una duración de un año a contar de la fecha de aceptación de la solicitud.
La suscripción en el caso del plan normal tendrá una duración ilimitada.
El anfitrión del centro turístico será el responsable de la información que el ingrese a la plataforma web de Quality tours sea correcta y veraz. 
Para la aceptación de la solicitud de suscripción el anfitrión del centro turístico tendrá que pagar el valor de la suscripción en cual es:
Plan normal: 
Plan plus:</p>
<br>
<p align="justify"><b>4.- De la renovación de la suscripción </b></p>
<p align="justify">La renovación de la suscripción solo se puede realizar en el plan normal y plus. Y se puede activar y realizar solo un mes antes del término de la suscripción. En ningún caso antes o después.
El anfitrión del centro turístico será el responsable de revisar que la información para la renovación sea correcta, en el caso de que no lo sea y/o quiera modificarla tendrá que esperar a que la suscripción actual termine y mandar una nueva solicitud.</p>
<br>
<p align="justify"><b>5.- De la modificación de los datos</b></p>
<p align="justify">En el caso de que el anfitrión del centro turístico requiera modificar los datos de contacto y/o información tendrá que avisarle mediante correo electrónico al administrador para que este acepte la modificación y realice los cambios.</p>
<br>
<p align="justify"><b>6.- De la cancelación de la suscripción.</b></p>
<p align="justify">Quality tours podrá cancelar la suscripción de un anfitrión de centro turístico cuando este incumpla y/o no respete las leyes de la republica de Chile o este incumpla y/o no respete las políticas del servicio y las condiciones de uso de esta plataforma.
</p>
    
    
</div>



