<?php
//Código para el idioma
if ($leng == "en") {
    include_once APP_PATH . 'libs/en.php';
} else {
    include_once APP_PATH . 'libs/es.php';
}
?>   
<?php

View::content();
require(APP_PATH . 'libs/PHPMailer_5.2.2-rc2/class.phpmailer.php');
require(APP_PATH . 'libs/PHPMailer_5.2.2-rc2/class.smtp.php');
$mail = new PHPMailer();
$mail->IsSMTP();
//$mail->SMTPSecure = "ssl";
$mail->SMTPAuth = true;
$mail->SMTPDebug = 0;  // debugging: 1 = errors and messages, 2 = messages only
$mail->Host = "smtp.mail.yahoo.com";
$mail->Port = 25;
$mail->Username = "qualitytoursadm@yahoo.com";
$mail->Password = "qt123123";
?>

<?php

if (isset($_POST['enviar'])) {
    //Preparar el mail
    //$mail->From = $_POST['email'];
    $mail->From = "qualitytoursadm@yahoo.com";
    $mail->FromName = $_POST['email'];
    $mail->Subject = $_POST['asunto'];
    $mail->Body = stripcslashes($_POST['mensaje']);
    $mail->AddAddress("qualitytoursadm@yahoo.com", "Destinatario"); //Dirección a la que enviaremos el correo
    $mail->IsHTML(true);

    if (!$mail->Send()) {
        //echo "Error: " . $mail->ErrorInfo;
        Flash::error("No se pudo enviar el mensaje");
    } else {
        //echo "Mensaje enviado correctamente";
        Flash::success("Mensaje enviado correctamente");
        Router::redirect('/');
    }
}
?> 
<style>
    .div_contacto
    {
        text-align: center;
    }
</style>  


<script type="text/javascript">
    //Validación con jquery
    $(document).ready(function () {
        var emailreg = /^[_a-z0-9-]+(.[_a-z0-9-]+)*@[a-z0-9-]+(.[a-z0-9-]+)*(.[a-z]{2,3})$/;
        $(".boton").click(function (){
            $(".errorVal").remove();
        
            //ELIMINAMOS ESPACIOS EN BLANCO AL COMIENZO/FINAL
            $(".asunto").val($.trim($(".asunto").val()));
        
            if( $(".email").val() == "" || !emailreg.test($(".email").val()) ){
                $(".email").focus().after("<span class='errorVal'>Ingrese un email valido</span>");
                return false;
            }else if( $(".asunto").val().length<3){
                $(".asunto").focus().after("<span class='errorVal'>El asunto debe tener al menos 3 letras</span>");
                return false;
            }else if( $(".asunto").val().length<3){
                $(".asunto").focus().after("<span class='errorVal'>El asunto debe tener al menos 3 letras</span>");
                return false;
            }else if( $(".body").val() == ""){
                $(".body").focus().after("<span class='errorVal'>El mensaje no puede estar vacío</span>");
                return false;
            }else if( $(".body").val().length<10){
                $(".body").focus().after("<span class='errorVal'>El mensaje debe tener al menos 10 letras</span>");
                return false;
            }
        });
    
        //Borrar mensaje de error si el usuario a llenado el campo
        $(".asunto, .body").keyup(function()
        {
            if( $(this).val() != "" )
            {
                $(".errorVal").fadeOut();
                return false;
            }
        });
    
    });
    
</script>

<style>
    .errorVal{
        background-color: #BC1010;
        padding: 6px 12px;
        border-radius: 4px;
        color: white;
        font-weight: bold;
        margin-left: 16px;
        margin-top: 6px;
        position: absolute;
    }
    .errorVal:before{ /* Este es un truco para crear una flechita */
        content: '';
        border-top: 8px solid transparent;
        border-bottom: 8px solid transparent;
        border-right: 8px solid #BC1010;
        border-left: 8px solid transparent;
        left: -16px;
        position: absolute;
        top: 5px;

    }
    textarea {
        resize: none;
        width: 300px;
        height: 200px;   
    }
</style>

<style>

</style>



<div class="container-fluid">
    <div class="row-fluid">
        <?php View::partial('publicidad_vertical'); ?>
        <div class="span10 well"  style="background-color: #f9ffff; ">
            <?php
            echo '<div class="div_contacto">
            <h1 style="font-family: SF">'.$contacto_contacto_titulo.'</h1>    
            <form action="" method="post">  <label for="email">E-mail :</label>
            <input type="text" value=""  class="email mask-email" name="email" size="50" maxlength="60"> <label for="asunto">'.$contacto_contacto_asunto.' : </label>
            <input type="text" name="asunto" class="asunto mask-alphanum" size="50" maxlength="60"><br> <label for="mensaje">'.$contacto_contacto_mensaje.' : </label>
            <textarea name="mensaje" class="body span10" style="resize:none;" cols="31" rows="5"></textarea> <br>
            <label for="enviar">
            <input type="submit" class="btn btn-info boton" name="enviar" value="'.$contacto_contacto_boton.'"></label>
            </form></div>';
            ?>
        </div>
    </div>
</div>