


<div align="center">
    <table class="table">
        <tr>
            <td><div align="center"><?php echo  Html::img("1341165838_image_add.png","ingresar imagen ","width=150 height=150"); ?></div></td>
            <td><div align="center"><?php echo Html::img("1341166104_edit-notes.png","editar ","width=150 height=150");?></div></td>
        </tr>
        <tr>
            <td> <div align="center"><?php  echo Html::link("contenido/ingresar/".$id_pub,'ingresar contenido'); ?></div></td>
            <td><div align="center"><?php echo Html::link("publicacion/editarpub/".$id_pub,"editar publicación");?></div></td>
        </tr>
    </table>
</div>