<div><?php View::content() ?></div> <br>
<?php
//Código para el idioma
    if($leng == "en")
    {
        include_once APP_PATH.'libs/en.php';
    }
    else
    {
        include_once APP_PATH.'libs/es.php';
    }
    
//CARGA NICEDIT
    
    echo Tag::js("nicedit/nicEdit");
?>    
<script type="text/javascript">
    //Validación con jquery
    //El siguiente script valida que los campos no estén vacios y el formato del RUT
$(document).ready(function () {
    
    $(".boton").click(function (){
        $(".errorVal").remove();
        
        
         
        if( $(".titulo").val() == "" )
        {
            $(".titulo").focus().after("<span class='errorVal'><?php echo $publicacion_ingresar_valtitulo ?></span>");
            return false;
        }
        
    });
    
    
    //Para el caso del listbox, no se puede borrar el error de validación con keyup
    //Ya que no es un textbox, usamos el metodo blur
   
    
    $(".titulo").keyup(function()
    {
        if( $(this).val() != "" )
        {
            $(".errorVal").fadeOut();
            return false;
        }
    });
    
   
    
});
</script>

<!--
El CSS a continuación da estilo a los mensaje de error en la validación
, no se usó "error" ya que kumbia ya tiene un estilo para esa clase, en su
reemplazo se uso 'errorVal'.
-->

<style>
    .errorVal{
    background-color: #BC1010;
    padding: 6px 12px;
    border-radius: 4px;
    color: white;
    font-weight: bold;
    margin-left: 16px;
    margin-top: 6px;
    position: absolute;
}
.errorVal:before{ /* Este es un truco para crear una flechita */
    content: '';
    border-top: 8px solid transparent;
    border-bottom: 8px solid transparent;
    border-right: 8px solid #BC1010;
    border-left: 8px solid transparent;
    left: -16px;
    position: absolute;
    top: 5px;
}
</style>
<div style='text-align: center;'><h1><?php echo $publicacion_ingresar_encabesado; ?></h1></div>


 <script type="text/javascript">

  bkLib.onDomLoaded(function() { 
      nicEditors.allTextAreas(
		{buttonList : ['bold','italic','underline','ol','ul','subscript','superscript',
'strikethrough','fontFormat','hr','link','unlink','image','xhtml' ],
		iconsPath : '<?php echo PUBLIC_PATH;?>/javascript/nicedit/nicEditorIcons.gif'})
	});

  </script>

<!-- captura de id para enviarlo al controlador       -->
<?php $id =  Auth::get('id');   ?>
<?php echo Form::open('publicacion/ingresar/'.$leng) ?>
<div >
    <table class="table table-striped">
        
        <tr>
            <td><?php echo Form::text('publicacion.titulo_pub','class="titulo" placeholder="'.$publicacion_ingresar_titulo.'"')?></td> 
        </tr>
        <tr>
            <?php // echo $publicacion_ingresar_detalle; ?>
            <td><?php echo Form::textarea('publicacion.detalle_pub','id="area1" rows="10" style="width: 100%;"')?>
            </td>
        </tr>     
    </table>
</div>
<br>
<div align="center">
    <table>
        <tr>
             <td><?php echo Form::submit(''.$publicacion_ingresar_boton.'','class="btn btn-submit boton" ') ?>&nbsp;</td>
        </tr>   
    </table>
</div>
<?php
    setlocale ( LC_TIME, 'spanish' );
    $fecha = strftime(date('Y/m/d'));?>
<?php echo Form::hidden("publicacion.fecha_pub",null,$fecha);?>
<?php echo Form::hidden('publicacion.estado_pub',null , 1); ?>
<?php echo Form::hidden('publicacion.id_usu',null , $id); ?>

<?php echo Form::close() ?> 