<!DOCTYPE html>
<html lang="es">
 <head>
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta http-equiv='Content-type' content='text/html; charset=<?php echo APP_CHARSET ?>' />
  <title>Quality tours</title>
  <?php
  
  
    echo Tag::js('jquery/jquery-1.7.2.min');
    echo Tag::js('jquery/jquery.confirm-1.3');
    echo Tag::js('bootstrap.min');
    echo Tag::js('bootstrap-modal');
    echo Tag::js('bootstrap-typeahead');
  ;
    
   
    Tag::css('bienvenida');
    Tag::css('style');
    Tag::css('bootstrap.min');
    echo Html::includeCss();
    
  ?>
    
    <script>
        $('.dropdown-toggle').dropdown();
    </script>
    
</head>
<body>
   <div class="container">
    <div id='content'>
        <div align="center">
     <?php // echo Html::img('logo.png','logo','width="400px" height="200px"'); ?> 
      <img src="/trunk/qualitytours/img/logo.png" alt="logo" width="400" height="200" >    
 </div> 
 
<!-- Partial del menu-->
<div> <?php View::partial('kumbia/menuprincipal') ?></div>
        

        <!--Muestra la pagina correspondiente (vista)-->
       
        <?php View::content(); ?>
        
          <!--Muestra el footer-->
     
    
        
    </div>
   </div>
    <div> <?php View::partial('kumbia/footer') ?> </div>
     
</body>
</html>
