<div><?php View::content() ?></div> 

<fieldset>
<?php echo Form::open() ?>
    <div align="center">
        <h1 style="font-family: SF"> Modificaci&oacute;n de datos </h1>
        <table>
    <tr>
        <td>Username:&nbsp;</td>
        <td><?php echo Form::text('usuario.username_usu', "class='input-medium disabled username' disabled=''") ?></td>
    </tr>
    <tr>
        <td>Password:&nbsp;</td>
        <td><?php echo Form::pass('usuario.password_usu', "class='input-medium password' placeholder='Password'") ?></td>
    </tr>

    <tr>
        <td>Nombre:&nbsp;</td>
        <td><?php echo Form::text('usuario.nombre_usu',"class='input-medium nombre'") ?></td>
    </tr>
    <tr>
        <td>Apellido:&nbsp;</td>
        <td><?php echo Form::text('usuario.apellido_usu',"class='input-medium apellido'") ?></td>
    </tr>
    <tr>
        <td>Rut:&nbsp;</td>
        <td><?php echo Form::text('usuario.rut_usu',"class='input-medium disabled rut' disabled=''") ?></td>
    </tr>
    <tr>
        <td>E-mail:&nbsp;</td>
        <td><?php echo Form::text('usuario.email_usu',"class='input-medium email'") ?></td>
    </tr>

</table>
    </div>
    <div align="center">
    <table>
        <tr>
            <td><?php echo Form::submit('Modificar datos','class="btn btn-submit boton"') ?>&nbsp;</td>
            <td><?php echo Form::reset('Reiniciar','class="btn btn-info"')?></td>
        </tr>         
    </table>
   </div>

    <?php echo Form::hidden('usuario.id'); ?>
    <?php echo Form::close() ?> 
</fieldset>