<div><?php View::content() ?></div> 
<script type="text/javascript">
    //Validación con jquery
    //El siguiente script valida que los campos no estén vacios y el formato del RUT
$(document).ready(function () {
    //VALIDACION USERNAME
    $(".boton").click(function (){
        $(".errorVal").remove();
        
         if( $(".palabra").val() == "" )
         {
            $(".palabra").focus().after("<span class='errorVal'>Ingrese username a buscar</span>");
            return false;
         }
    });
    
    //boton de confirmacion
    $('.eliminar').confirm({
      timeout:3000,
      msg:'Desea eliminar&nbsp;',
      dialogShow:'fadeIn',
      dialogSpeed:'slow',
      buttons: {
        wrapper:'<button class="btn btn-info" value="Si"></button>',
        separator:'  '
      }  
    });
    
    //Borrar mensaje de error si el usuario a llenado el campo
    $(".palabra").keyup(function()
    {
    if( $(".palabra").val() != "" )
    {
        $(".errorVal").fadeOut();
        //AJAX COMIENZO
        $.ajax
        ({
            url: '<?php echo PUBLIC_PATH; ?>ajax/usuario_busqueda.php?string='+$(".palabra").val(),
            type: "POST",
            dataType: "json",
            success: function(data)
            {
                //console.log(data[0]['id_usu']);
                if (data != null && data.length > 0)
                {
                    var count = 0;
                    //console.log(data);
                    $(".table-condensed tbody").empty();
                    while (count < data.length)
                        {
                            $(".table-condensed tbody").append("<tr>");
                            $(".table-condensed tbody").append("<td>"+data[count]['id']+"</td>");
                            $(".table-condensed tbody").append("<td>"+data[count]['username_usu']+"</td>");
                            $(".table-condensed tbody").append("<td>"+data[count]['nombre_usu']+"</td>");
                            $(".table-condensed tbody").append("<td>"+data[count]['apellido_usu']+"</td>");
                            $(".table-condensed tbody").append("<td>"+data[count]['email_usu']+"</td>");
                            $(".table-condensed tbody").append("<td>"+data[count]['rol_usu']+"</td>");
                            $(".table-condensed tbody").append("<td>"+
                               "<div class='btn-group'>"+
                                    "<a class='btn btn-primary' href='#'><i class='icon-user icon-white'></i> Opciones</a>"+
                                    "<a class='btn btn-primary dropdown-toggle' data-toggle='dropdown' href='#'><span class='caret'></span></a>"+
                                        "<ul class='dropdown-menu'>"+
                                            "<li><a href='/trunk/qualitytours/usuario/modificar/"+data[count]['id']+"'><i class='icon-pencil'></i> Editar</a></li>"+
                                            "<li><a href='#'><i class='icon-arrow-up'></i>Convertir a cliente</a></li>"+
                                            "<li><a href='/trunk/qualitytours/usuario/eliminar/"+data[count]['id']+"'><i class='icon-trash'></i>Eliminar</a></li>"+
                                        "</ul>"+
                                "</div>");
//                            $(".table-condensed tbody").append('<td><form action="/trunk/qualitytours/usuario/modificar/'+data[count]['id']+'" method="post"><input type="submit" value="Modificar" class= "btn btn-info modificar"></form></td>');
//                            $(".table-condensed tbody").append('<td><form action="/trunk/qualitytours/usuario/eliminar/'+data[count]['id']+'" method="post"><input type="submit" value="Eliminar" class= "btn btn-danger eliminar"></form></td>');
                            
                            $(".table-condensed tbody").prepend("</tr>");
                            count++;
                        }
                }
                else 
                {
                    $(".table-condensed tbody").empty();
                    $(".table-condensed tbody").append('<td><b>NO SE ENCONTRARON RESULTADOS</b></td>');
                }
            } // cierre success
        }); //cierre ajax
        //AJAX FIN
        return false;
    }
    });
    
    
    
});
</script>

<!--
El CSS a continuación da estilo a los mensaje de error en la validación
, no se usó "error" ya que kumbia ya tiene un estilo para esa clase, en su
reemplazo se uso 'errorVal'.
-->

<style>
    .errorVal{
    background-color: #BC1010;
    padding: 6px 12px;
    border-radius: 4px;
    color: white;
    font-weight: bold;
    margin-left: 16px;
    margin-top: 6px;
    position: absolute;
}
.errorVal:before{ /* Este es un truco para crear una flechita */
    content: '';
    border-top: 8px solid transparent;
    border-bottom: 8px solid transparent;
    border-right: 8px solid #BC1010;
    border-left: 8px solid transparent;
    left: -16px;
    position: absolute;
    top: 5px;
}
</style>
<!--formulario de busqueda-->
 <div align="center">
        <h1 style="font-family: SF"> Buscar usuarios </h1>
            <table>
                <tr> 
                    <td>Palabra clave&nbsp;&nbsp;</td>
                    <td><?php echo Form::text('usuario',"class='span3 palabra' placeholder='Ingrese username'") ?></td>
                </tr>
                <tr>
                    <td colspan="2">
                        <div class="accordion" id="accordion2">
                            <div class="accordion-group">
                                <div class="accordion-heading">
                                    <a class="accordion-toggle" data-toggle="collapse" data-parent="#accordion2" href="#collapseOne">
                                        Más opciones de busqueda
                                    </a>
                                </div>
                            <div id="collapseOne" class="accordion-body collapse">
                                <div class="accordion-inner">
                                     <label class="radio">
                                        <input type="radio" name="optionsRadios" id="optionsRadios1" value="turista" checked>
                                            Turista
                                     </label>
                                     <label class="radio">
                                        <input type="radio" name="optionsRadios" id="optionsRadios2" value="option2">
                                            Centro turistico
                                     </label>
                                </div>
                            </div>
                            </div>
                        </div>
                    </td>
                </tr>
            </table>
       
<!--Resultado de la busqueda-->
        <br>
        <br>
        <h4> Resultado de la busqueda </h4>
        <br>
        <table class="table table-condensed">
            <thead>
                <tr>
                    <!-- cabecera de la tabla-->
                    <th>id</th>
                    <th>Username</th>
                    <th>Nombre</th>
                    <th>Apellido</th>
                    <th>Email</th>
                    <th>Tipo </th>
                    <th> </th>
                    <th> </th>
                </tr>
            </thead>
            <tbody>
            </tbody>
        </table>
        <?php //if($tabla_activada == '1') {
        //if($listaobtenida->prev) echo Html::linkAction("buscar/$listaobtenida->prev/2/$datoabuscarr/$opcionn", '<< Anterior |');
        //if($listaobtenida->next) echo Html::linkAction("buscar/$listaobtenida->next/2/$datoabuscarr/$opcionn", 'Próximo >>'); 
        //}?>
     </div>
