<div><?php View::content() ?></div> 

<script type="text/javascript">
    //Validación con jquery
    //El siguiente script valida que los campos no estén vacios y el formato del RUT
$(document).ready(function () {
    var rutreg = /^\d{1,2}\.\d{3}\.\d{3}[-][0-9kK]{1}$/;
    var emailreg = /^[_a-z0-9-]+(.[_a-z0-9-]+)*@[a-z0-9-]+(.[a-z0-9-]+)*(.[a-z]{2,3})$/;
    $(".boton").click(function (){
        $(".errorVal").remove();
        
        
         if( $(".username").val() == "" ){
            $(".username").focus().after("<span class='errorVal'>Ingrese username</span>");
            return false;
        }else if( $(".password").val() == ""){
            $(".password").focus().after("<span class='errorVal'>Ingrese  password</span>");
            return false;
        }else if( $(".nombre").val() == ""){
            $(".nombre").focus().after("<span class='errorVal'>Ingrese  nombre</span>");
            return false;
        }else if( $(".apellido").val() == "" ){
            $(".apellido").focus().after("<span class='errorVal'>Ingrese apellido</span>");
            return false;
        } else if( $(".rut").val() == "" || !rutreg.test($(".rut").val()) ){
            $(".rut").focus().after("<span class='errorVal'>Ingrese rut correctamente</span>");
            return false;
        }else if($(".email").val() == "" || !emailreg.test($(".email").val()) ){
           $(".email").focus().after("<span class='errorVal'>Ingrese email</span>");
           return false;
        }
    });
    
    //Borrar mensaje de error si el usuario a llenado el campo
    $(".nombre, .username, .password, .apellido").keyup(function()
    {
        if( $(this).val() != "" )
        {
            $(".errorVal").fadeOut();
            return false;
        }
    });
    
    
    
    
    
    //Borrar el mensaje de error si el usuario ingresa un rut con formato válido
    $(".rut").keyup(function()
    {
        if( $(this).val() != "" && rutreg.test($(this).val()))
        {
            $(".errorVal").fadeOut();
            return false;
        }
    });
    
    //borrar el mensaje de error si se ingresa un email valido
    $(".email").keyup(function()
    {
        if( $(this).val() != "" && emailreg.test($(this).val()))
        {
            $(".errorVal").fadeOut();
            return false;
        }
    });
    
    

    
});
</script>

<!--
El CSS a continuación da estilo a los mensaje de error en la validación
, no se usó "error" ya que kumbia ya tiene un estilo para esa clase, en su
reemplazo se uso 'errorVal'.
-->

<style>
    .errorVal{
    background-color: #BC1010;
    padding: 6px 12px;
    border-radius: 4px;
    color: white;
    font-weight: bold;
    margin-left: 16px;
    margin-top: 6px;
    position: absolute;
}
.errorVal:before{ /* Este es un truco para crear una flechita */
    content: '';
    border-top: 8px solid transparent;
    border-bottom: 8px solid transparent;
    border-right: 8px solid #BC1010;
    border-left: 8px solid transparent;
    left: -16px;
    position: absolute;
    top: 5px;
}
</style>



<br>
<fieldset>
<?php echo Form::open('usuario/ingresar') ?>
    <div align="center">
        <h1> Regístrate en Qualitytours </h1>
        <table>
    <tr>
        <td>Username:&nbsp;</td>
        <td><?php echo Form::text('usuario.username_usu', "class='input-medium username' placeholder='Username'") ?></td>
    </tr>
    <tr>
        <td>Password:&nbsp;</td>
        <td><?php echo Form::pass('usuario.password_usu', "class='input-medium password' placeholder='Password'") ?></td>
    </tr>

    <tr>
        <td>Nombre:&nbsp;</td>
        <td><?php echo Form::text('usuario.nombre_usu',"class='input-medium nombre'") ?></td>
    </tr>
    <tr>
        <td>Apellido:&nbsp;</td>
        <td><?php echo Form::text('usuario.apellido_usu',"class='input-medium apellido'") ?></td>
    </tr>
    <tr>
        <td>Rut:&nbsp;</td>
        <td><?php echo Form::text('usuario.rut_usu',"class='input-medium rut' placeholder='ej: 6.765.223-1' rut") ?></td>
    </tr>
    <tr>
        <td>E-mail:&nbsp;</td>
        <td><?php echo Form::text('usuario.email_usu',"class='input-medium email'") ?></td>
    </tr>

</table>
    </div>
    <div align="center">
    <table>
        <tr>
            <td><?php echo Form::submit('Ingresar Usuario','class="btn btn-submit boton"') ?>&nbsp;</td>
            <td><?php echo Form::reset('Reiniciar','class="btn btn-info"')?></td>
        </tr>         
    </table>
   </div>

 
<?php echo Form::hidden('usuario.estado_usu',null , 1); ?>
<?php echo Form::hidden('usuario.rol_usu',null,'turista'); ?>

<?php echo Form::close() ?> 
    </fieldset>

