<?php
    //Código para el idioma
    if($leng == "en")
    {
        include_once APP_PATH.'libs/en.php';
    }
    else
    {
        include_once APP_PATH.'libs/es.php';
    }
?>  
<div><?php View::content() ?></div> 
<h1 style="text-align: center;">Recuperar clave</h1>
<?php echo Form::open(); ?>
<table class="table">
    <tr>
        <td style="text-align: right;"><b>Ingrese su nombre de usuario:</b></td>
        <td style="text-align: left;"><?php echo Form::text("buscar","class='mask-alphanum'"); ?></td>
    </tr>
</table>
<div style="text-align: center;"><?php echo Form::submit("Recuperar","class='btn btn-info  boton'"); ?></div>
<?php echo Form::close();?>