<div><?php View::content() ?></div> 
<script type="text/javascript">
    //activacion del modal de la cancelacion solicitud
    function activar_renovar () {
        $('#renovar').modal('toggle');
    };
    //activacion del modal de la cancelacion solicitud
    function cancelar () {
        $('#cancela').modal('toggle');
    };

    //activacion del modal confirmacion mail
    function confirmar () {
        $('#email').modal('toggle');
    }
    
    //activacion del modal confirmacion mail relacionado con solicitud cambio plan
    function confirmar_cambio () {
        $('#email_cambio').modal('toggle');
    }
    
    function cancelar_solicitud_cambio () {
        $('#solicitud_cambio_cancelar').modal('toggle');
    }    
    
</script>

<style>
    textarea {
        resize: none;
        width: 300px;
        height: 100px;

    }
</style>

<div align="center">
    <h2> Datos de la suscripción </h2> <br>
    <table>
        <tr>
            <!--    Datos usuario/cliente-->        
            <td>
                <div align="center">

                    <dl>
                        <table class="table table-bordered">
                            <tr>
                                <td><dt>Nombre de usuario:</dt></td>
                            <td width="250px"><dd><?php echo $nombre_usu ?></dd></td>
                            </tr>        
                            <tr>
                                <td><dt>Nombre de centro turistico:</dt></td>
                            <td width="250px"><dd><?php echo $nombre_cli ?></dd></td>
                            </tr>
                            <tr>
                                <td><dt>Rut privado:</dt></td>
                            <td width="250px"><dd><?php echo $rut_usu ?></dd></td>
                            </tr>
                            <tr>
                                <td><dt>Rut comercial:</dt></td>
                            <td width="250px"><dd><?php echo $rut_cli ?></dd></td>
                            </tr>
                            <tr>
                                <td><dt>Giro:</dt></td>
                            <td width="250px"><dd><?php echo $giro_cli ?></dd></td>
                            </tr>
                            <tr>
                                <td><dt>Telefono comercial:</dt></td>
                            <td width="250px"><dd><?php echo $telefono_cli ?></dd></td>
                            </tr>
                            <tr>
                                <td><dt>Tipo de plan:</dt></td>
                            <td width="250px"><dd><?php echo $tipo_plan ?></dd></td>
                            </tr>
                            <tr>
                        </table>
                    </dl>
                </div>
            </td>

            <td>
                &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
            </td>
            <!--    Opciones-->   

            <?php if (isset($panel_suscripcion_renovacion) && $estado_sol == "Pendiente" || $estado_sol == "Esperando") { ?>
                <td>
                    <h4> <center> Datos solicitud renovacion </center></h4>
                    <!-- ******************************************************* 
                         Panel de administracion de la solicitud de renovacion
                         *******************************************************  -->

                    <!-- Datos (fecha y estado )de la solicitud de renovacion-->
                    <table class="table table-bordered">
                        <thead>
                            <tr>
                                <th><center>Fecha</center></th>
                        <th><center>Estado</center></th>
            </tr>
            </thead>
            <tbody>
                <tr>
                    <td><center><?php echo $fecha_sol ?> </center></td>
            <td><center><?php echo $estado_sol ?> </center></td>
            </tr>
            </tbody>
        </table>
        <!-- Fin Datos (fecha y estado )de la solicitud de renovacion-->

        <!-- Datos (Observaciones)de la solicitud de renovacion-->
        <table class="table table-bordered">
            <thead>
                <tr>
                    <th><center>Observaciones</center></th>
            </tr>
            </thead>
            <tbody>
                <tr>
                    <td width="400px"><center><?php echo $observaciones_sol ?></center></td>
            </tr>
            </tbody>
        </table>
        <center>
            <table>
                <tr>
                    <?php if ($estado_sol == "Pendiente") { ?><td><button class="btn btn-danger btn-small" type="submit" onclick="cancelar ();">Cancelar renovacion</button></td> <?php } ?>
                    <?php if ($estado_sol == "Esperando" && $mail_sol == "f") { ?><td><button class="btn btn-primary btn-small" type="submit" onclick="confirmar ();">Confirmacion mail</button>&nbsp</td>
                        <?php
                    } else if ($estado_sol == "Esperando" && $mail_sol == "t") {
                        echo "<b>Usted ya envio la confirmacion del envio del mail <b>";
                    }
                    ?>

                </tr>
            </table>
        </center>
    </td>    

<?php } else { ?> 
    <td>
        <dl>
            <table class="table table-bordered">
                <thead>
                    <tr>
                        <th><dt>Fecha solicitud</dt></th>
                <th><dt>Fecha de inicio</dt</th>
                <th><dt>Fin suscripción</dt></th>
                </tr>
                </thead>
                <tbody>
                    <tr>
                        <td width="120px"><dd><?php echo $fecha_solicitud ?></dd></td>
                <td width="120px"><dd><?php echo $ini_sus ?></dd></td>
                <td width="120px"><dd><?php echo $fin_sus ?></dd></td>
                </tr>
                </tbody>
            </table>
            <table class="table table-bordered">
                <thead>
                    <tr>
                        <th><center><dt>Observacion</dt></center></th>
                </tr>
                </thead>
                <tbody>
                    <tr>
                        <td width="120px"><dd><?php echo $observaciones ?></dd></td>
                </tr>
                </tbody>
            </table>
            <?php
            if (isset($muestra_boton)) {
                if ($muestra_boton == "Si") {
                    ?>
                    <center><button class="btn btn-success" type="submit" onclick="activar_renovar()">Renovar suscripción</button></center>
                    <p align="center">Si desea cambiar los datos de la suscripcion, debe esperar<br>
                        a que la actual termine para mandar una nueva solicitud</p>
                    <?php
                }
            } else if (isset($existe)) {
                echo $existe;
            } else if (isset($noexiste)) {
                echo $noexiste;
            }
            ?>
        </dl>
    </td>  
<?php } ?>
</tr>

</table>

<?php if (isset($activacion_panel_cambio_plan)) { ?>
    <?php if ($activacion_panel_cambio_plan == "Mostrar") { ?>
        <?php echo Form::open("solicitud/cambio_plan/$leng") ?>
        <?php $data = array('normal' => 'Normal', 'plus' => 'Plus'); ?>
        <h5><center>Cambio de plan</center></h5>
        <table class="table table-bordered" width="120px">
            <tr>
                <td>Seleccione el plan:&nbsp;</td>
                <td><?php echo Form::select('tipo_plan', $data, "class='span2'") ?></td>
            </tr>
        </table>
        <?php echo Form::submit('Cambiar plan', 'class="btn btn-submit btn-success boton"') ?>
        <?php echo Form::close(); ?>
    <?php } else if ($activacion_panel_cambio_plan == "No mostrar") { ?>
        <h5><center>Cambio de plan</center></h5>

        <?php if ($estado == "Pendiente") { ?><td><button class="btn btn-danger btn-small" type="submit" onclick="cancelar_solicitud_cambio ();">Cancelar solicitud</button><?php } ?>

        <?php if ($estado == "Esperando" && $mail == "f") { ?><td><button class="btn btn-primary btn-small" type="submit" onclick="confirmar_cambio ();">Confirmacion mail</button><?php } ?>

        <?php } ?>
    <?php } ?>
</div>
<!--
****************
Seccion de modal
****************
-->
<?php if (isset($muestra_boton)) {
    if ($muestra_boton == "Si") { ?>
        <!-- Modal para aceptar la renovacion de la solicitud-->
        <div id="renovar" class="modal hide fade" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
                <h3 id="myModalLabel">¿ Esta seguro de renovar la suscripción?</h3>
            </div>
            <div class="modal-body">
                <p><b>Al renovar su suscripción usted acepta las condiciones del servicio</b><br>
                    Observaciones: <br> 
                <ul>1.- Asegurece que los datos mostrados corresponden a su centro turistico</ul>
                <ul>2.- La solicitud de renovacion tiene que ser confirmada por un administrador</ul></p>
            </div>
            <div class="modal-footer">
                <button class="btn" data-dismiss="modal" aria-hidden="true">Cerrar</button>
                <a href="/trunk/qualitytours/solicitud/renovarsuscripcion/<?php echo $leng ?>"><button class="btn btn-primary">Renovar suscripción</button></a>
            </div>
        </div>
    <?php }
} ?> 
<?php
if (isset($estado_sol)) {
    if ($estado_sol == "Pendiente") {
        ?>
        <!--   Modal de confirmacion de cancelacion de la solicitud-->   
        <div id="cancela" class="modal hide fade" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
                <h3 id="myModalLabel">¿ Esta seguro de cancelar ?</h3>
            </div>
            <div class="modal-body">
                <p>La cancelación de esta solicitud no se podra deshacer</p>
            </div>
            <div class="modal-footer">
                <button class="btn" data-dismiss="modal" aria-hidden="true">Cerrar</button>
                <a href="/trunk/qualitytours/solicitud/cancela_renovacion/<?php echo Auth::get("id") . "/" . $leng ?>"><button class="btn btn-primary">Cancelar solicitud</button></a>
            </div>
        <?php } else if ($estado_sol == "Esperando") { ?>
            <!--   Modal de confirmacion de envio mail-->   
            <div id="email" class="modal hide fade" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
                    <h3 id="myModalLabel">¿ha enviado el correo correspondiente?</h3>
                </div>
                <div class="modal-body">
                    <p>Si usted ha enviado el mail con los datos solicitados: </p>
                    <p>  - Imagen del deposito bancario</p>
                    <p>  - Datos solicitados</p>
                </div>
                <div class="modal-footer">
                    <button class="btn" data-dismiss="modal" aria-hidden="true">Cerrar</button>
                    <a href="/trunk/qualitytours/solicitud/confirmacionmail_renovacion/<?php echo Auth::get("id") . "/" . $leng ?>"><button class="btn btn-primary">Aceptar</button></a>
                </div>  
            <?php }
        } ?>

        <?php
        if (isset($activacion_panel_cambio_plan)) {
            if (isset($estado)) {
                if ($estado == "Esperando" && $mail == "f") {
                    ?>

                    <div id="email_cambio" class="modal hide fade" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
                        <div class="modal-header">
                            <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
                            <h3 id="myModalLabel">¿ha enviado el correo correspondiente?</h3>
                        </div>
                        <div class="modal-body">
                            <p>Si usted ha enviado el mail con los datos solicitados: </p>
                            <p>  - Imagen del deposito bancario</p>
                            <p>  - Datos solicitados</p>
                        </div>
                        <div class="modal-footer">
                            <button class="btn" data-dismiss="modal" aria-hidden="true">Cerrar</button>
                            <a href="/trunk/qualitytours/solicitud/confirmacionmail_cambio/<?php echo Auth::get("id") . "/" . $leng ?>"><button class="btn btn-primary">Aceptar</button></a>
                        </div>                  

                        <?php
                    } else if ($estado == "Pendiente") {
                        ?>
<!--                        Modal para cancelar el cambio de plan-->
                        <div id="solicitud_cambio_cancelar" class="modal hide fade" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
                            <div class="modal-header">
                                <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
                                <h3 id="myModalLabel">¿Esta seguro de cancelar el cambio de plan?</h3>
                            </div>
                            <div class="modal-body">
                                <p>Esta acción no se puede revertir, para cambiar el plan con posteridad debe mandar otra solicitud</p>
                            </div>
                            <div class="modal-footer">
                                <button class="btn" data-dismiss="modal" aria-hidden="true">Cerrar</button>
                                <a href="/trunk/qualitytours/solicitud/cancela_cambio/<?php echo Auth::get("id") . "/" . $leng ?>"><button class="btn btn-primary">Aceptar</button></a>
                            </div>
                        </div>  
                    <?php
                    }
                }
            }
            ?>

