<?php
//Código para el idioma
    if($leng == "en")
    {
        include_once APP_PATH.'libs/en.php';
    }
    else
    {
        include_once APP_PATH.'libs/es.php';
    }
?>    
<div><?php View::content() ?></div> 

<!--PARA GOOGLE MAPS COMIENZO-->
<style type="text/css">
  html { height: 100% }
  body { height: 100%; margin: 0px; padding: 0px }
  #map_canvas { height: 100% }
</style>

<script type="text/javascript">
    var id_cli = <?php echo $id_cliente?>;
    var id_usu = <?php echo Auth::get('id')?>;
    var promedio = <?php echo $calificacion;?>
  
    
</script>

<!--eliminar comentario-->
<script type="text/javascript">
    
    
    $(document).ready(function() {
        $('.delete').live( 'click', function() {
        //$('.delete').click(function()// NO FUNCIONABA CUANDO ELIMINA NUEVOS COMENTARIOS
           
            //Recogemos el valor del servicio
            var service = $(this).attr('id');
            
            var dataString = 'id='+service;
            
            $.ajax({
                type: "POST",
                url: "<?php echo PUBLIC_PATH; ?>ajax/eliminar_comentario.php",
                data: dataString,
                success: function() {            
                    //$('#delete-ok').empty();
                    //$('#delete-ok').append('<div>Se ha eliminado correctamente el servicio con id='+service+'.</div>').fadeIn("slow");
                    //$('#'+parent).remove();
                    $('#service'+service).remove();
                }
                
            }); //FIN AJAX
        });                 
    });    
</script>

 <?php echo Tag::js('rating'); ?>
 
<script type="text/javascript">
    
    $(document).ready(function () {
        
        $(".boton").click(function (){
        $(".errorVal").remove();
        
        
         if( $(".comentario").val() == "" ){
             $(".comentario").focus().after("<span class='errorVal'><?php echo $cliente_detalle_valcoment; ?></span>");
             return false;
             }
         });
    
    
    //Borrar mensaje de error si el usuario a llenado el campo
    $(".comentario").keyup(function()
    {
        if( $(this).val() != "" )
        {
            $(".errorVal").fadeOut();
            return false;
        }
    });
    
});
    
</script>

<!--
El CSS a continuación da estilo a los mensaje de error en la validación
, no se usó "error" ya que kumbia ya tiene un estilo para esa clase, en su
reemplazo se uso 'errorVal'.
-->
<style>
    .errorVal{
    background-color: #BC1010;
    padding: 6px 12px;
    border-radius: 4px;
    color: white;
    font-weight: bold;
    margin-left: 16px;
    margin-top: 6px;
    position: absolute;
}
.errorVal:before{ /* Este es un truco para crear una flechita */
    content: '';
    border-top: 8px solid transparent;
    border-bottom: 8px solid transparent;
    border-right: 8px solid #BC1010;
    border-left: 8px solid transparent;
    left: -16px;
    position: absolute;
    top: 5px;
}
.delete {
cursor: pointer;
font-size: 16px;
font-weight: bold;
margin-left: 820px;
}
</style>



<meta name="viewport" content="initial-scale=1.0, user-scalable=yes" />

<script type="text/javascript" src="https://maps.google.com/maps/api/js?libraries=weather&sensor=false">
//Esto carga el api de Google Maps
</script>

<script type="text/javascript">
//Este código carga el mapa con un marcador en la ubicacion
//del centro turístico
//FUNCTION INITIALIZE
var map;
var latlng = new google.maps.LatLng(<?php echo $latitud; ?>,<?php echo $longitud; ?>)
$(document).ready(function(){

    //Setup del mapa
    var myOptions = {
          zoom: 12,
          center: latlng,
          mapTypeId: google.maps.MapTypeId.ROADMAP
        };
    map = new google.maps.Map(document.getElementById('map_canvas'),
            myOptions);
      
  
  marker = new google.maps.Marker({
            position: latlng,
            map: map 
            //,title:
        });
        var calificacion;
 
//AGREGAMOS CAPA DE CLIMA
 var weatherLayer = new google.maps.weather.WeatherLayer({
  temperatureUnits: google.maps.weather.TemperatureUnit.CELSIUS
});
weatherLayer.setMap(map);

//NUBES
var cloudLayer = new google.maps.weather.CloudLayer();
cloudLayer.setMap(map)



});
</script>
 <script>
           $('.carousel').carousel({
            interval: 1000
            })
 </script>

<script type="text/javascript">
$(document).ready(function() {
    
    $('#star1').rating("<?php echo PUBLIC_PATH;?>ajax/ingresar_calificacion.php", 
    {
        maxvalue: 5,
        curvalue: <?php echo $calificacion;?>, 
        id:0
    });
   
});
 
</script>



<!--FORMULARIO DE COMENTARIO-->
<script>

        
    $(document).ready(function(){
	$('#boton-enviar').click(function(event){
            
            event.preventDefault();
            var nombre = $('#nombre').val();
            var comentario = $('#comentario').val();
            if (nombre != '' && comentario != ''){
                $("#comentario").val('');
                $("#mensaje").fadeOut(1000, function(){
                    $.post(
                    "<?php echo PUBLIC_PATH;?>ajax/ingresar_comentario.php", 
                    { nombre: nombre, comentario: comentario,  id_usu: id_usu,  id_cli: id_cli}, 
                    function(data) {
                       
                        $("#comentarios").append(data);  
                        //location.reload();
                        // location.reload();
                        
                        }, 
                        "html");
                        $('#mensaje').text('Comentario agregado!');
			});
                        }
                        else{}
                        
                    });
                    
                        });
 </script>
<table class="table table-bordered">
<tr>  
<thead>
    <td width="400px"><div id="map_canvas" style="width:400px; height:400px"></div></td>
    <td width="600px">
    <h3 style="font-family:SF"><?php echo $nombre_cliente." "; ?><?php echo Html::link('contacto/contacto_cli/'.$id_cliente, Html::img('icon_mail_phone.gif'));?></h3>
    <h6>
        <?php if (isset($region_ubi)) echo $region_ubi; ?><br>
        <?php if (isset($ciudad_ubi)) echo $ciudad_ubi; ?><br>
        <?php if (isset($region_ubi)) echo $direccion_ubi; ?>
       
        
    </h6>
        <?php echo"<span class='label label-info'>".$mostrar.":&nbsp;".$cliente_detalle_visitas."</span>";?><br>
        <?php
            foreach ($array_servicios as $servicio)
                {
                    echo Html::link("servicio/detalle/" . $servicio->id."/".$leng, $cliente_detalle_servicios.": " . $servicio->nombre_ser . "<br>");
                }  
        ?>
            <?php
    //Trozo PHP para verificar si hay imagenes
            if (count($contenido) > 0)
                
            {?>
        <br>
       <center>
       <div class="span5">       
                    <div id="myCarousel" class="carousel slide" with="300">
                    <!-- Carousel items -->
                        <div class="carousel-inner">
                            <div class="item active"><?php echo Html::img("../default/public/img/upload/".$ruta_con[0],"imagen");?></div>
                                <?php
                                for($img = 1; $img<=$contimg-1; $img++)
                                {
                                    echo "<div class='item'>".Html::img("../default/public/img/upload/".$ruta_con[$img],"imagen")."</div>";
                                } ?>         


                    </div>
                        <!-- Carousel nav -->

                    <a class="carousel-control left" href="#myCarousel" data-slide="prev">&lsaquo;</a>
                    <a class="carousel-control right" href="#myCarousel" data-slide="next">&rsaquo;</a>
                    </div>
       </div>
       </center>
  <?php }?>
      </td>
      </thead>
      </tr>
      <tr>
        <td>
            <?php 
                if(!Auth::is_valid())
                {
                    echo "<font size='1'><b>".$cliente_detalle_mensaje1."</b></font><br>";
                }
                $calificacion = number_format($calificacion, $decimals = 1);
                echo "<b>Califica tu experencia de viaje:<br></b>
                        <b><font size='1'>Promedio:</font><font size='4'>".$calificacion."</font></b><br>
                        <b><font size='1'>Cantidad:</font><font size='4'>".$cantidad."</font></b><br>";
            ?>
                <div id="star1" class="rating">&nbsp;</div> 
               
        </td>
       </tr>

       </table>   
       
            
            <?php 

                if($cont == 0)
                {

                }
                if($cont == 1)
                {?>
        <div class="span12">
                         
                        <?php  for($i=0; $i<=$contador-1 ; $i++) 
                        {?>

                    <div class="service_list" id="service<?=$idComentario[$i]?>" data="<?=$idComentario[$i]?>">    
                        <table class="table table-hover">
                            <tr>
                                <td><?php echo "<b>".$nombre[$i]."</b>"; ?></td>
                                <td><div align="right"><?php echo "<b>".$fecha[$i]."</b>";?></div></td>
                            </tr>
                        </table>


                        <table>
                            <tr>
                                <td> <div align="left"> <?php echo $detalle[$i];?> </div></td>
                            </tr> 
                            <?php
                        if(Auth::is_valid())
                        {
                            if(Auth::get("id") ==  $id[$i])
                            { ?>

                                <a  class="delete" id="<?=$idComentario[$i]?>">Eliminar</a>  

                       <?php }  

                        }?>


                        </table> 
                    </div>  
            <?php  } //fin for?>

                <?php  }?>        
                <?php 
                    if(!Auth::is_valid())            
                    {
                        echo "<b>Login to post comments.</b>";
                    }
                    else
                    {  
                ?>
                <strong id="mensaje"> Agrega un nuevo comentario:</strong>
                
                        <div id="comentarios">
                           

                                <!-- aca apareceran los nuevos comentarios -->
                           
                        </div>
            
               
                        <!--Formulario de comentario-->
                    <form action="#">
                            <?php echo Form::hidden("nombre",null,$nombre_usuario);?>  
                            <div align="center"> <?php echo Form::text("comentario","class='span3  comentario'"); ?> </div>  
                            <?php echo Form::hidden("id_usu",null,Auth::get("id") ); ?>
                            <?php echo Form::hidden("id_cli", null,$id_cliente) ?>
                            <div align="center"><input id="boton-enviar" type="submit" value="Comentar" class="btn btn-primary boton" /></div>
                    </form>  

                <?php  }?>
</div>
 



