<?php
//Código para el idioma
    if($leng == "en")
    {
        include_once APP_PATH.'libs/en.php';
    }
    else
    {
        include_once APP_PATH.'libs/es.php';
    }
?>    
<div><?php View::content() ?></div> 
<!--CODIGO PARA ESTILO DE COMENTARIO-->
<style>
#stylized{
border:solid 2px #b7ddf2;
background:#ebf4fb;
margin:70px 200px 80px 0px;
}
.myform{
margin:0 auto;
width:500px;
padding:14px;
}

#stylized h1 {
font-size:14px;
font-weight:bold;
margin-bottom:8px;
}
#stylized p{
font-size:11px;
color:#666666;
margin-bottom:20px;
border-bottom:solid 1px #b7ddf2;
padding-bottom:10px;
}
#stylized label{
display:block;
font-weight:bold;
text-align:right;
width:140px;
float:left;
}
#stylized .small{
color:#666666;
display:block;
font-size:11px;
font-weight:normal;
text-align:right;
width:140px;
}
#stylized input{
float:left;
font-size:12px;
padding:4px 2px;
border:solid 1px #aacfe4;
width:200px;
margin:2px 0px 0px 10px;}
#stylized select{
float:left;
font-size:12px;
padding:4px 2px;
border:solid 1px #aacfe4;
width:130px;
margin:2px 100px 20px 10px;
}

#stylized textarea{
float:left;
font-size:12px;
padding:4px 2px;
border:solid 1px #aacfe4;

margin:2px 0px 20px 10px;
}
#stylized  .bt_plus{
float:none;
font-size:12px;
padding:0px;

width:20px;
margin:5px 0 5px 3px ;

}

#stylized .boton{
clear:both;
margin-left:150px;
width:125px;
height:31px;
background:#666666 url(../img/button.png) no-repeat;
text-align:center;
line-height:31px;
color:#FFFFFF;
font-size:11px;
font-weight:bold;
}
    
</style>
    
<!--PARA GOOGLE MAPS COMIENZO-->
<style type="text/css">
  html { height: 100% }
  body { height: 100%; margin: 0px; padding: 0px }
  #map_canvas { height: 100% }
</style>

<script type="text/javascript">
    var id_cli = <?php echo $id_cliente?>;
    var id_usu = <?php echo Auth::get('id')?>;
    var promedio = <?php echo $calificacion;?>
</script>
 <?php echo Tag::js('rating'); ?>
<?php  echo Tag::js('jquery.form');?>

<script type="text/javascript">
    
    
   
    
    
    $(document).ready(function () {
        
        $(".boton").click(function (){
        $(".errorVal").remove();
        
        
         if( $(".detalle").val() == "" ){
             $(".detalle").focus().after("<span class='errorVal'>Ingrese un comentario</span>");
             return false;
             }
         });
    
    
    //Borrar mensaje de error si el usuario a llenado el campo
    $(".detalle").keyup(function()
    {
        if( $(this).val() != "" )
        {
            $(".errorVal").fadeOut();
            return false;
        }
    });
    
});
    
</script>

<!--
El CSS a continuación da estilo a los mensaje de error en la validación
, no se usó "error" ya que kumbia ya tiene un estilo para esa clase, en su
reemplazo se uso 'errorVal'.
-->
<style>
    .errorVal{
    background-color: #BC1010;
    padding: 6px 12px;
    border-radius: 4px;
    color: white;
    font-weight: bold;
    margin-left: 16px;
    margin-top: 6px;
    position: absolute;
}
.errorVal:before{ /* Este es un truco para crear una flechita */
    content: '';
    border-top: 8px solid transparent;
    border-bottom: 8px solid transparent;
    border-right: 8px solid #BC1010;
    border-left: 8px solid transparent;
    left: -16px;
    position: absolute;
    top: 5px;
}
</style>



     <meta name="viewport" content="initial-scale=1.0, user-scalable=yes" />

<script type="text/javascript" src="https://maps.google.com/maps/api/js?libraries=weather&sensor=false">
//Esto carga el api de Google Maps
</script>

<script type="text/javascript">
//Este código carga el mapa con un marcador en la ubicacion
//del centro turístico
//FUNCTION INITIALIZE
var map;
var latlng = new google.maps.LatLng(<?php echo $latitud; ?>,<?php echo $longitud; ?>)
$(document).ready(function(){

    //Setup del mapa
    var myOptions = {
          zoom: 12,
          center: latlng,
          mapTypeId: google.maps.MapTypeId.ROADMAP
        };
    map = new google.maps.Map(document.getElementById('map_canvas'),
            myOptions);
      
  
  marker = new google.maps.Marker({
            position: latlng,
            map: map 
            //,title:
        });
        var calificacion;
 
//AGREGAMOS CAPA DE CLIMA
 var weatherLayer = new google.maps.weather.WeatherLayer({
  temperatureUnits: google.maps.weather.TemperatureUnit.CELSIUS
});
weatherLayer.setMap(map);

//NUBES
var cloudLayer = new google.maps.weather.CloudLayer();
cloudLayer.setMap(map)



});
</script>
<!--ESTILO CSS PARA LAS ESTRELITAS-->
<style>
  



</style>

<script type="text/javascript">
$(document).ready(function() {
    
    $('#star1').rating("<?php echo PUBLIC_PATH;?>ajax/ingresar_calificacion.php", 
    {
        maxvalue: 5,
        curvalue: <?php echo $calificacion;?>, 
        id:0
    });
   
});
 
</script>
<!--FORMULARIO DE COMENTARIO-->
 <script type="text/javascript"> 
        // esperamos que el DOM cargue
        $(document).ready(function() { 
            // definimos las opciones del plugin AJAX FORM
            var opciones= {
                               beforeSubmit: mostrarLoader, //funcion que se ejecuta antes de enviar el form
                               success: mostrarRespuesta, //funcion que se ejecuta una vez enviado el formulario
							   
            };
             //asignamos el plugin ajaxForm al formulario myForm y le pasamos las opciones
            $('#myForm').ajaxForm(opciones) ; 
            
             //lugar donde defino las funciones que utilizo dentro de "opciones"
             function mostrarLoader(){
                      $("#loader_gif").fadeIn("slow");
             };
             function mostrarRespuesta (responseText){
				           alert("Mensaje enviado: "+responseText);
                          $("#loader_gif").fadeOut("slow");
                          $("#ajax_loader").append("<br>Mensaje: "+responseText);
             };
   
        }); 
 </script> 

 
         <table class="table table-bordered">
                <tr>  
                    <thead>
                        <td width="400px"><div id="map_canvas" style="width:400px; height:400px"></div></td>
                        <td width="600px">
                            <h3 style="font-family:SF"><?php echo $nombre_cliente; ?></h3>
                            <h6>
                                <?php echo $region_ubi; ?><br>
                                <?php echo $ciudad_ubi; ?><br>
                                <?php echo $direccion_ubi; ?>
                            </h6>
                            <?php echo"<span class='label label-info'>".$mostrar.":&nbsp;Views</span>";?><br>
                            <?php


                                foreach ($array_servicios as $servicio) {
                                        echo Html::link("servicio/detalle/" . $servicio->id, "Services: " . $servicio->nombre_ser . "<br>");
                                    }  
                                    ?>
                        </td>

                    </thead>
                </tr>
                <tr>
                    <td>
                        <?php 
                           $calificacion = number_format($calificacion, $decimals = 1);
                           echo "<b>Califica tu experencia de viaje:<br></b>
                                 <b><font size='1'>Promedio:</font><font size='4'>".$calificacion."</font></b><br>
                                 <b><font size='1'>Cantidad:</font><font size='4'>".$cantidad."</font></b><br>";
                        ?>
                         <div id="star1" class="rating">&nbsp;</div> 
                     </td>
                    
                </tr>



                <?php
                    //Trozo PHP para verificar si hay imagenes
                    if (count($contenido) > 0)
                    {
                        echo "<tr><td colspan='2'><center>";
                        foreach($contenido as $buscar)
                        {
                            echo  Html::img("../default/public/img/upload/".$buscar->ruta_con,"imagen","width=200 height=150");
                        }   
                        echo "</center></td></tr>";
                    }
                ?>

            </table>   
       
            
            <?php 

                if($cont == 0)
                {

                }
                if($cont == 1)
                {?>
        <div class="span12">
                    <ul class="nav nav-list inverse">
                    <li class="active"><a href="#"><i class="icon-pencil"></i><?php echo "<b>".$numComentarios."</b>:&nbsp; "; ?>Comments</a></li>

                    </ul>   

                <?php  for($i=0; $i<=$contador-1 ; $i++) 
                    {?>

                        <table class="table table-hover">
                            <tr>
                                <td><?php echo "<b>".$nombre[$i]."</b>"; ?></td>
                                <td><div align="right"><?php echo "<b>".$fecha[$i]."</b>";?></div></td>
                            </tr>
                        </table>
                        <table>
                            <tr>
                                <td> <div align="left"> <?php echo $detalle[$i];?> </div></td>
                                </tr>  
                            <?php 
                            if(!Auth::is_valid())
                            {
                                $variable = Auth::is_valid();
                            }
                            else
                            {
                                if(Auth::get("id") ==  $id[$i])
                                        { ?>
                                        <tr>
                                            <td><?php echo Html::link("comentario/eliminar/".$idComentario[$i]."/".$id_cliente.'/'.$leng, "Remove");?></td>
                                        </tr>                             
                                <?php }  

                            }?>


                            </table> 
            <?php   }?>
        </div>    
        <?php  }?>




        <?php 
        if(!Auth::is_valid())            
        {
            echo "<b>Login to post comments.</b>";
        }
        else
        {  
        ?>

            <!--Formulario de comentario-->
            <div id="ajax_loader">
                
            </div>
            <br>
            <div align="center" class="span12">


               
            <form id="myForm" action="<?php echo PUBLIC_PATH;?>ajax/ingresar_comentario.php" method="post" style="height:200px;"> 
                
               <?php echo Form::text("mensaje");?> <br>
            
                <?php echo Html::img("loader.gif","loader_gif","style=' display:none;' id='loader_gif'")?>
                <?php  echo Form::submit('Comentar','class="btn btn-primary boton"'); ?>
            </form> 
              

<!--   <?php // echo Form::open('comentario/ingresar/'.$id_cliente.'/'.$leng); ?>
                    <table>
                       <tr>
                           <td><?php// echo Form::text('comentario.detalle_com', "class='span3 detalle' placeholder='Write a comment...'") ?></td>
                       </tr>    
                       <tr>
                           <td><?php // echo Form::submit('Comment','class="btn btn-primary boton"'); ?> </td> 
                       </tr>

                    </table>-->
<!--            </div>-->

              <?php  
                setlocale ( LC_TIME, 'spanish' );
                $fecha = strftime(date('Y/m/d'));
                echo Form::hidden('comentario.id_usu','null',Auth::get('id'));
                echo Form::hidden("comentario.fecha_com","null",$fecha);
                echo Form::hidden("comentario.estado_com","null",1);
                echo Form::hidden("comentario.cli_id_usu","null",$id_cliente);
                echo Form::close();    

              }?>


            
