<style>
    footer {


        position: relative;
        margin-top: 200px; /* ponga en negativo el alto de su pie de página para nuestro    ejemplo usamos 63, usted debe remplazarlo según su diseño   */
        height: 63px;
        clear:both;
        width:100%;

    }
</style> 
<footer>

    <div class="row-fluid">
        <div class="span12">
            <address>
                <center><strong>Quality tours 2012 <i class="icon-hand-left"></i></strong></center>
            </address>   
            <div class="row-fluid">
                <div class="span6"> 
        <blockquote>
    <p><span style="font-size: 10px">Condiciones de uso | Condiciones del servicio | Politica de privacidad </span></p>
    <small style="font-size: 8px">Actualizado al 30 de Noviembre</small>
    </blockquote></div>
                <div class="span6">  
                    <blockquote class="pull-right">
                    <p style="line-height: 80%">
                        <a rel="license" href="http://creativecommons.org/licenses/by-sa/3.0/deed.es"><img alt="Licencia Creative Commons" style="border-width:0" src="http://i.creativecommons.org/l/by-sa/3.0/80x15.png" /></a><br />
                        <span xmlns:dct="http://purl.org/dc/terms/" property="dct:title"></span> <span style="font-size: 10px; "><a xmlns:cc="http://creativecommons.org/ns#" href="http://qualitytours.no-ip.org" property="cc:attributionName" rel="cc:attributionURL">Quality tours</a><br> 
                            se encuentra bajo una <a rel="license" href="http://creativecommons.org/licenses/by-sa/3.0/deed.es"><br>Licencia Creative Commons </a>. </span>  
                    </p>
                    </blockquote>
                </div>
            </div>
        </div>    

    </div>
    <!--        <div  align="center"> <font size=1>Actualizado al 30 de Noviembre</font></div>-->
</footer>
