
<script type="text/javascript">
    $(function() {
        $(window).scroll(function() {
            if($(this).scrollTop() != 0) {
                $('#toTop').fadeIn();	
            } else {
                $('#toTop').fadeOut();
            }
        });
 
        $('#toTop').click(function() {
            $('body,html').animate({scrollTop:0},800);
        });	
    });
</script>

<footer >

    <div class="row-fluid" style=" background-color: #fbffff">
        <div class="span12">
            <!--            <address>
                            <center><strong>Quality tours 2012 <i class="icon-hand-left"></i></strong></center>
                        </address>   -->

            <hr style="height: 1px; background-color: #fbffff; border-style:inset;  ">

            <div class="row-fluid">
                <div class="span6"> 
                    <blockquote>
                        <p><span style="font-size: 10px">
                            <?php
                       $url = $_SERVER['REQUEST_URI'];
                        //devuelve los 2 ultimos caracteres de la url si es igual a en se utiliza las variables en inglés
                        $url = substr($url, -2);
                        if ($url == "en") echo Html::link('pages/terms_of_use', 'Terms of use'); 

                        else echo Html::link('pages/condiciones', 'Condiciones de uso');
                        ?>
                                | Condiciones del servicio | Pol&iacute;tica de privacidad | <?php echo Html::link('contacto/contacto', 'Contactenos'); ?> </span></p>
                        <small style="font-size: 8px">Actualizado al 9 de Diciembre</small>
                    </blockquote>
                </div>
                <div class="span6">  
                    <blockquote class="pull-right">
<!--                        <p><span style="font-size: 10px"><a href="http://qualitytours.no-ip.org">Quality Tours 2012</a></span></p>
                        <span style="font-size: 10px">Algunos derechos reservados</span>-->
                        <p><span style="font-size: 10px"><a href="http://qualitytours.no-ip.org">Quality Tours 2012</a> </span></p>
                        <small style="font-size: 10px">Algunos derechos reservados</small>
                    </blockquote>
                </div>
            </div>
            <div id="toTop"><i class="icon-arrow-up"></i></div>
        </div>    

    </div>
</footer>
 <!-- <a rel="license" href="http://creativecommons.org/licenses/by-sa/3.0/deed.es"><img alt="Licencia Creative Commons" style="border-width:0" src="http://i.creativecommons.org/l/by-sa/3.0/80x15.png" /></a><br />
                            <span xmlns:dct="http://purl.org/dc/terms/" property="dct:title"></span> <span style="font-size: 10px; "><a xmlns:cc="http://creativecommons.org/ns#" href="http://qualitytours.no-ip.org" property="cc:attributionName" rel="cc:attributionURL">Quality Tours</a><br> 
                                se encuentra bajo una<a rel="license" href="http://creativecommons.org/licenses/by-sa/3.0/deed.es">Licencia Creative Commons </a></span>  -->