 <style>
   footer {
  

  position: relative;
  margin-top: 250px; /* ponga en negativo el alto de su pie de página para nuestro    ejemplo usamos 63, usted debe remplazarlo según su diseño   */
  height: 63px;
  clear:both;
  width:100%;
  
 }
  </style> 
  <footer>
        <div  align="center"> <b> Quality tours 2012&nbsp;</b><i class="icon-hand-left"></i></div>
  </footer>
    <!--    <div  align="center"> <font size=1>Actualizado al 9 de Noviembre</font></div>-->
    