<!--CODIGO PARA BUSQUEDA -->
<?php 

 $arr= Load::model('ubicacion')->find(); 

?>


<script type="text/javascript">
        jQuery(document).ready(function() {
            var alCities = [
//             ARRAY DE CIUDADES y region   
             <?php    foreach ($arr as $buscar)
            {
                echo "'".$buscar->region_ubi."','".$buscar->ciudad_ubi."', ";  
            }
            ?>  
              
                
            ].sort();
            $('#ciudad').typeahead({source: alCities, items:1});
        });
 </script>



        <div class="navbar ">
            <div class="navbar-inner">
                <div class="container">

                    <a class="brand" href="#">Quality Tours</a>
                    
                    <ul class="nav">
                        
<!--                        HOME-->
                        <li class="active">
                            <?php echo Html::link('index/','Home');?>
                        </li>
                        
                        <!--LINK al Config-->
<!--                    <li><?php //echo Html::link('pages/show/kumbia/status/', 'Config', 'title="Ver configuración de la aplicación"') ?></li>-->
                        

<!--                    Menu del usuario-->
                        <?php
                        if(Auth::is_valid())
                        {
                            if (Session::get('rol_usu') == 'turista')
                            { ?>
                                <li class="dropdown">
                                    <a href="#"
                                        class="dropdown-toggle"
                                        data-toggle="dropdown">
                                        Cuenta
                                        <b class="caret"></b>
                                    </a>
                                    
                                    <ul class="dropdown-menu">
                                        <li><?php echo Html::link('usuario/modificar/','Modificar datos');?></li>
                                       
                                    </ul>
                                </li>
                            <?php
                            }
                        }
                        ?>
                        
<!--                    Menu del cliente-->
                        <?php
                        if(Auth::is_valid())
                        {
                            if (Session::get('rol_usu') == 'cliente')
                            { ?>
                                <li class="dropdown">
                                    <a href="#"
                                        class="dropdown-toggle"
                                        data-toggle="dropdown">
                                        Cliente
                                        <b class="caret"></b>
                                    </a>
                                    
                                    <ul class="dropdown-menu">
                                        <li><?php echo Html::link('servicio/ingresar/','Publicar servicio');?></li>
                                        <li><?php echo Html::link('ubicacion/ingresar/','Indique su ubicación');?></li>
                                        <li><?php echo Html::link('contenido/ingresarcli/','Subir fotos');?></li>
                                    </ul>
                                </li>
                            <?php
                            }
                        }
                        ?>
                        
<!--                    Panel de administración-->
                        <?php
                        if(Auth::is_valid())
                        {
                            if (Session::get('rol_usu') == 'administrador')
                            { ?>
                                <li class="dropdown">
                                    <a href="#"
                                        class="dropdown-toggle"
                                        data-toggle="dropdown">
                                        Administraci&oacute;n
                                        <b class="caret"></b>
                                    </a>
                                    
                                    <ul class="dropdown-menu">
                                        <li><?php echo Html::link('cliente/ingresar/','Ingresar cliente');?></li>
                                        <li><?php echo Html::link('usuario/buscar/','Buscar usuarios');?></li>
                                        <li><?php echo Html::link('publicacion/ingresar/','Ingresar publicacion');?></li>
                                        <li><?php echo Html::link('administrador/ingresar/','Ingresar administrador');?></li>
                                        <li><?php echo Html::link('categoria/ingresar','Ingresar Categorias'); ?></li>
                                    </ul>
                                </li>
                            <?php
                            }
                        }
                        ?>
                        
                        
                    </ul>
                    
                    <ul class="nav pull-right">
                        
<!--                        CAMPO DE BUSQUEDA-->
                       
                            
                            <?php  echo Form::open("busqueda/buscando/",'post','class=navbar-search');?>
                             <?php echo Form::text("ciudad","class='search-query span2' placeholder='Buscar destinos' data-provide='typeahead' "); ?>

<!--                            <input type="text" id="ciudad" class="search-query span2" placeholder="Buscar destinos" data-provide="typeahead" class="search-query">-->
                            <?php echo Form::close()?>
                        
                        

<!--                        MENU INICIO/CIERRE DE SESION-->
                            <li class="dropdown">
                                <a href="#"
                                    class="dropdown-toggle"
                                    data-toggle="dropdown">
                                    <?php
                                    if(Auth::is_valid())
                                    {
                                        echo Auth::get('username_usu');
                                    }
                                    else
                                    {
                                        echo "Iniciar sesión";
                                    }
                                    ?>
                                    <b class="caret"></b>
                                </a>
                                <ul class="dropdown-menu">
                                    <li>
                                        
                                        <?php
                                        //Si el user esta loguedao se mostrará la opción para cerrar sesión en el menu desplegable
                                        if(Auth::is_valid())
                                        {
                                            echo "<li>";
                                            echo Html::link('usuario/cerrarsesion','Cerrar Sesión');
                                            echo "</li>";
                                        }
                                        else
                                        { //Si no esta logueado se mostrará el form para iniciar sesión
                                            ?>
                                        <?php echo Form::open('usuario/autenticar','post','class=navbar-form'); ?>
                                            <center>
                                                Usuario 
                                                <?php echo Form::text("username_usu","class='span2'");?>
                                                Contraseña 
                                                <?php echo Form::pass("password_usu","class='span2'");?>
                                                <?php echo Form::submit('Ingresar',"class='btn btn-primary'"); ?>
                                                
                                                <li>  <?php echo Html::link('usuario/ingresar/','Regístrate');?></li>
                                            </center>
                                        </form>
                                        <?php } ?>
                                        
                                    </li>
                                </ul>
                            </li>
                    </ul>
                    
                </div>
            </div>
            
        </div>
