<div><?php
View::content();
echo Tag::js('jquery.keyfilter');

//Código para el idioma
if ($leng == "en") {
    include_once APP_PATH . 'libs/en.php';
} else {
    include_once APP_PATH . 'libs/es.php';
}
?></div> 

<script type="text/javascript">
    //Validación con jquery
    //El siguiente script valida que los campos no estén vacios
$(document).ready(function () {
    var emailreg = /^[_a-z0-9-]+(.[_a-z0-9-]+)*@[a-z0-9-]+(.[a-z0-9-]+)*(.[a-z]{2,3})$/;
    $(".boton").click(function (){
        $(".errorVal").remove();
        
         //ELIMINAMOS ESPACIOS EN BLANCO AL COMIENZO/FINAL
            $(".nombre").val($.trim($(".nombre").val()));
            $(".apellido").val($.trim($(".apellido").val()));
        
        if( $(".password").val() == ""){
            $(".password").focus().after("<span class='errorVal'><?php echo $val_password_string; ?></span>");
            return false;
        }else if( $(".password").val().length<5){
            $(".password").focus().after("<span class='errorVal'><?php echo $usuario_ingreso_minimo; ?></span>");
            return false;
        }else if( $(".password").val() != $(".passworddos").val()){
            $(".passworddos").focus().after("<span class='errorVal'><?php echo $val_passwords_string; ?></span>");
            return false;
        }else if( $(".nombre").val() == ""){
            $(".nombre").focus().after("<span class='errorVal'><?php echo $val_nombre_string; ?></span>");
            return false;
        }else if( $(".apellido").val() == "" ){
            $(".apellido").focus().after("<span class='errorVal'><?php echo $val_apellido_string; ?></span>");
            return false;
        }else if($(".email").val() == "" || !emailreg.test($(".email").val()) ){
           $(".email").focus().after("<span class='errorVal'><?php echo $val_email_string; ?></span>");
           return false;
       }
    });
    
    //Borrar mensaje de error si el usuario a llenado el campo
    $(".nombre, .password, .apellido, .email, .passworddos").keyup(function()
    {
        if( $(this).val() != "" )
        {
            $(".errorVal").fadeOut();
            return false;
        }
    });
    
    //borrar el mensaje de error si se ingresa un email valido
    $(".email").keyup(function()
    {
        if( $(this).val() != "" && emailreg.test($(this).val()))
        {
            $(".errorVal").fadeOut();
            return false;
        }
    });    
   
//funcion que valida que las dos contraseñas esten ingresadas correctamente
       function coincidePassword(){
        var valor1 = $(".password").val();
        var valor2 = $(".passworddos").val();
        $(".errorVal").remove();
        
        if(valor1.length<5){
            $(".password").focus().after("<span class='errorVal'><?php echo $usuario_ingreso_minimo; ?></span>");
            return false;
        }
        if(valor1 != valor2){
            $(".passworddos").focus().after("<span class='errorVal'><?php echo $val_passwords_string; ?></span>");
            return false;
        }
        if(valor1.length==0 || valor1==""){
            $(".passworddos").focus().after("<span class='errorVal'><?php echo $val_passwords_string; ?></span>");
            return false;
        }
       }   
    $(".passworddos").keyup(function()
    {
        coincidePassword();
    });  
});
</script>

<style>
    .errorVal{
    background-color: #BC1010;
    padding: 6px 12px;
    border-radius: 4px;
    color: white;
    font-weight: bold;
    margin-left: 16px;
    margin-top: 6px;
    position: absolute;
}
.errorVal:before{ /* Este es un truco para crear una flechita */
    content: '';
    border-top: 8px solid transparent;
    border-bottom: 8px solid transparent;
    border-right: 8px solid #BC1010;
    border-left: 8px solid transparent;
    left: -16px;
    position: absolute;
    top: 5px;
}
</style>

<fieldset>
<?php echo Form::open('usuario/automodificar/'.$leng) ?>
    <div align="center">
        <h1 style="font-family: SF"> <?php echo $usuario_automodificar_titulo; ?> </h1>
        <table>
    <tr>
        <td><?php echo $usuario_ingresar_usuario ?>:&nbsp;</td>
        <td><?php echo Form::text('usuario.username_usu', "class='input-medium disabled username' disabled=''") ?></td>
    </tr>
    <tr>
        <td><?php echo $usuario_automodificar_modcontraseña ?>:&nbsp;</td>
        <td><?php echo Form::pass('usuario.password_usu', "class='input-medium password mask-alphanum' placeholder='Password'") ?></td>
    </tr>
    <tr>
        <td><?php echo $usuario_ingresar_confirmar ?>:&nbsp;</td>
        <td><?php echo Form::pass('',"class='input-medium passworddos mask-alphanum' placeholder='Password'") ?></td>
    </tr>

    <tr>
        <td><?php echo $nombre_ingresar_string;?>:&nbsp;</td>
        <td><?php echo Form::text('usuario.nombre_usu',"class='input-medium nombre mask-alpha'") ?></td>
    </tr>
    <tr>
        <td><?php echo $apellido_ingresar_string;?>:&nbsp;</td>
        <td><?php echo Form::text('usuario.apellido_usu',"class='input-medium apellido mask-alpha'") ?></td>
    </tr>
    <tr>
        <td>E-mail:&nbsp;</td>
        <td><?php echo Form::text('usuario.email_usu',"class='input-medium email mask-email'") ?></td>
    </tr>

</table>
    </div>
    <div align="center">
    <table>
        <tr>
            <td><?php echo Form::submit("Ok",'class="btn btn-submit boton"') ?>&nbsp;</td>
            <td><?php echo Html::link("index/?".$leng, Form::button($usuario_automodificar_botonatras,'class="btn btn-info"')); ?></a</td>
        </tr>         
    </table>
   </div>
    <?php echo Form::hidden('usuario.id'); ?>
    <?php echo Form::close() ?> 
</fieldset>