<div><?php View::content() ?></div> 
<script type="text/javascript">
//Para llamar al modal    
$(document).ready(function () {
$('#myModal').modal({
    keyboard: false
    })
});
</script>


<div class="modal hide" id="myModal">
    <div class="modal-header">
    <button type="button" class="close" data-dismiss="modal">×</button>
    <h3>Usuario Eliminado</h3>
    </div>
    <div class="modal-body">
    <p>La eliminacion del usuario se ha efectuado con exito</p>
    </div>
    <div class="modal-footer">
    <a href="../buscar" class="btn btn-primary">Aceptar</a>
    </div>
</div>