
<div><?php View::content() ?></div> 

<script type="text/javascript">
//activacion del modal de la cancelacion solicitud
    function activar_modal () {
        $('#myModal').modal('toggle');
    };

//activacion del modal confirmacion mail
    function mail () {
        $('#email').modal('toggle');
    }

</script>
<div align="center">
    <h1 style="font-family: SF"> Estado de tu solicitud </h1>
    <br></br>

<!-- Tabla informacion general solicitud-->    
    <table class="table table-condensed">
        <thead>
            <tr>
                <th><center>Estado solicitud</center></th>
                <th><center>Fecha solicitud</center</th>
                <th><center>Tipo de solicitud</center</th>

                <?php if ($colortabla == "info") { ?>
                    <th><center>Confirme env&iacute;o mail</center></th><?php } ?>
            </tr>
        </thead>        
        <tbody>
            <tr class="<?php echo $colortabla ?>">
                <td><center><?php echo $estado ?></center</td>
                <td><center><?php echo $fecha ?></center</td>
                <td><center><?php echo $tipo ?></center</td>
                
<!--                Se valida que el usuario no haya mandado el mail y que el estado de la solicitud sea esperando, esto para poder mostar el boton-->
                <?php if ($colortabla == "info"  && $mail_sol == "f") { ?>
                <td><center><button class="btn btn-small btn-success" type="button" onclick="mail ()">Mail enviado</button></center></td>
<!--                En el caso de que ya envio el mail, se muestra el aviso-->
                <?php }else if($mail_sol == "t"){?> <td><center><b>Usted ya confirm&oacute; el env&iacute;o</b></center></td><?php } ?>
    
                <?php if ($colortabla == "warning") { ?>
                <td><a href="/trunk/qualitytours/cliente/ver/<?php echo Auth::get("id")."/".$leng ?>"><button class="btn btn-small btn-info" type="button">Ver datos registro</button></a></td>
                <td><td><button class="btn btn-small btn-danger" type="button" onclick="activar_modal()" >Cancelar solicitud</button></td></td>
                <?php } ?>
            </tr>
        </tbody>
    </table>
    <br></br>

<!--    Tabla de observaciones-->
    <table class="table table-bordered">
        <thead>
            <tr>
                <th><center> Observaciones </center></th>
            </tr>
        </thead>        
        <tbody>
            <tr>
                <td><center><?php echo $observaciones ?></center></td>
            </tr>         
        </tbody>
    </table>
<!--   Fin tabla de observaciones-->  

<!--   boton otras solicitudes-->   
    <center><a href="/trunk/qualitytours/solicitud/vertodas/<?php echo Auth::get("id").'/'.$leng ?>"><button class="btn btn-small btn-success" type="button">Ver otras solicitudes</button></a></center>
     <br></br>
</div>

<?php if ($colortabla != "info") { ?>
<!--   Modal de confirmacion de cancelacion de la solicitud-->   
<div id="myModal" class="modal hide fade" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
    <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
        <h3 id="myModalLabel">¿Est&aacute; seguro de cancelar ?</h3>
    </div>
    <div class="modal-body">
        <p>La cancelaci&oacute;n de esta solicitud no se podr&aacute; deshacer</p>
    </div>
    <div class="modal-footer">
        <button class="btn" data-dismiss="modal" aria-hidden="true">Cerrar</button>
        <a href="/trunk/qualitytours/solicitud/cancela/<?php echo Auth::get("id").'/'.$leng ?>"><button class="btn btn-primary">Cancelar solicitud</button></a>
    </div>
<?php } else { ?>
<!--   Modal de confirmacion de envio mail-->   
<div id="email" class="modal hide fade" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
    <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
        <h3 id="myModalLabel">¿Ha enviado el correo correspondiente?</h3>
    </div>
    <div class="modal-body">
        <p>Si usted ha enviado el mail con los datos solicitados: </p>
        <p>  - Imagen del dep&oacute;sito bancario en el caso de plan normal y plus</p>
        <p>  - Datos solicitados</p>
    </div>
    <div class="modal-footer">
        <button class="btn" data-dismiss="modal" aria-hidden="true">Cerrar</button>
        <a href="/trunk/qualitytours/solicitud/confirmacionmail/<?php echo Auth::get("id").'/'.$leng ?>/"><button class="btn btn-primary">Aceptar</button></a>
    </div>  
 <?php   } ?>