
<div><?php View::content() ?></div> 

<div align="center">
    <h1 style="font-family: SF"> Estado de tu solicitud </h1>
    <br></br>

    <table class="table table-condensed">
        <thead>
            <tr>
                <!-- cabecera de la tabla-->
                <th>Estado solicitud</th>
                <th>Fecha solicitud</th>
                <th>Tipo de solicitud</th>
                <th>Datos de la solicitud</th>
            </tr>
        </thead>        

        <tr class="<?php echo $colortabla ?>">
            <td><?php echo $estado ?></td>
            <td><?php echo $fecha ?></td>
            <td><?php echo $tipo ?></td>
            <td><?php echo $observaciones ?></td>
            <td><a href=""><button class="btn btn-info" type="button">Ver datos registro</button></a></td>
            <td><button class="btn btn-danger" type="button">Cancelar solicitud</button></td>
        </tr>
    </table>
    <br></br>
    
    <table class="table table-bordered">
        <thead>
            <tr>
               <th><center> Observaciones </center></th>
            </tr>
        </thead>        
        <tbody>
            <tr>
                <td><center><?php echo $observaciones ?></center></td>
            </tr>
        </tbody>
        </table>
    <br></br>
</div>
