<div><?php View::content() ?></div> 

<center><h2>Condiciones de uso</center></h2>
<div align="center">
<p align="justify">Esta plataforma web qualitytours.no-ip.org se rige por los términos y condiciones contenidos en este texto, está administrado y es 
   titularidad de Quality tours S.A (en adelante “Quality tours”), Al utilizar esta Plataforma web aceptas explícitamente los 
   Términos y Condiciones, incluyendo todas las políticas que se refieren en él.  Estos términos podrán ser modificados, 
   información que se le dará a conocer a los usuarios mediante correo electrónico y notificaciones en la plataforma. Si no está de 
   acuerdo con los Términos y Condiciones no podrá utilizar el sitio.</p> <br>

<p align="justify"><strong>1. Uso del sitio web</strong> </p>

<p align="justify">En la plataforma web tienes la opción de interactuar con anfitriones de alojamientos 
    (Centros turísticos) de todo chile, Toda esta interacción es vigilada y registrada, Quality tours no tiene responsabilidad 
    por las consecuencias que pudiese resultar de esta interacción.</p><br>

<p align="justify"><strong>2. Veracidad de los datos y uso de la información de los usuarios.</strong></p>

<p align="justify"> usuario se hace responsable por la veracidad de los datos proporcionados a la plataforma web (nombre real, apellido real, email) y se compromete a actualizarlos cuando lo estime pertinente.
Quality tours se compromete a no hacer uso de los datos proporcionados por los usuarios salvo para uso interno ya sea mediante la plataforma o mediante los servicios proporcionados por GOOGLE INC. En NINGÚN caso, la información de los usuarios será entregada, facilitada o vendida a terceros.
Para mayor información sobre el uso de información de usuarios, por favor leer nuestras Políticas de Privacidad</p><br>

<p align="justify"><strong>3.- Calidad de Contenido de la plataforma web.</strong></p>
<p align="justify">Los datos y otros materiales que aparecen en esta plataforma web se han ingresado 
    siguiendo estrictos procedimientos de control de calidad por un equipo de editores profesionales. Sin embargo, 
    Quality tours no se responsabiliza por la veracidad, exactitud y confiabilidad del contenido de esta plataforma y, 
    asimismo, estima que los datos no deben considerarse oficiales. Los precios de  servicios que figuran en este medio 
    pueden no ser correctos debido a que la veracidad de esta información no depende de Quality tours. Por favor, en el 
    caso de existir información errónea, solicitamos llenar el formulario de contacto con el fin de informarnos la página 
    que presenta el error (es) y si gusta puede enviar la corrección (es) propuesta (s), citando donde sea necesario las fuentes 
    para comprobar la información.</p><br>

<p align="justify"><strong>4.- Daños Intencionales.</strong></p>
<p align="justify">Quality tours se reserva el derecho de recurrir a la ley para castigar cualquier esfuerzo intencional de manipular la 
información o el software de la plataforma web; causar daño premeditadamente; e intentar 'Hackear' o vulnerar la seguridad de la plataforma. 
En estos casos Quality tours tendrá toda la facultad de iniciar acciones legales en su beneficio para compensar los daños causados.</p><br>

<p align="justify"><strong>5.- Daños a Computadores de Usuarios.</strong></p>
<p align="justify">Quality tours no se responsabiliza de ningún daño o perjuicio que presente el computador como consecuencia del acceso a esta plataforma 
web y sus herramientas, o cualquier virus o similar que pueda afectar su computador a través de este portal o sus servicios. Sin embargo, 
cabe destacar que contamos con una protección antivirus.</p><br>

<p align="justify"><strong>6. Derechos de autor.</strong></p>
<p align="justify">Tanto el logotipo Quality tours "Asesorias turisticas", el software, slogan, descripciones traducidas profesionalmente de empresas 
turísticas son titularidad de Quality tours S.A que posee todos sus derechos.
El contenido (entre ellos fotos) que el anfitrión del centro turístico pudiese subir a la plataforma web quedaran regidos bajo 
la <a rel="license" href="http://creativecommons.org/licenses/by-nc-nd/3.0/cl/">Licencia Creative Commons </a>.Para mayor información sobre esto, por favor 
leer nuestras condiciones del servicio.</p><br>

<p align="justify"><strong>7.  Jurisdicción y Ley Aplicable.</strong></p>

<p align="justify">Este acuerdo estará regido en todos sus puntos por las leyes vigentes en la República Chilena.
Cualquier disputa derivada del presente acuerdo, estará sometida a las leyes aplicables y a los Tribunales competentes de la Ciudad 
de Santiago y los procedimientos se llevarán a cabo en idioma castellano.</p><br>

<p align="justify">Si tienes alguna duda sobre los Términos y Condiciones Generales escríbanos a qualitytoursadm@yahoo.com</p>
</div> 