<?php
View::content();
?>
<h2><center>Terms of Use</center></h2>
<div align="center">
    <p align="justify">This web platform qualitytours.no-ip.org is governed by the terms and conditions contained herein, is managed and owned by Quality Tours SA (hereinafter "Quality tours"), By using this Web platform you explicitly accept the Terms and Conditions, including all policies that relate to it. These terms may be amended, information that will introduced to users through email and notifications on the platform. If you do not agree with the terms and conditions you may not use the platform.
</p>

<p align="justify"><strong>1. Using the web platform</strong></p><p align="justify">
In this web platform you have the option to interact with tourist centers (resorts) throughout Chile, all this interaction is monitored and registered, Quality Tours has no responsibility for the consequences that could result from this interaction.
</p>

<p align="justify"><strong>2. Accuracy of data and user information uses.</strong></p><p align="justify">
You are responsible for the accuracy of the data provided to the web platform (real name, real last name, email) and commitment to update when deemed appropriate. Quality tours agrees not to use the data provided by the users except for internal use by either the platform or through the services provided by GOOGLE INC. In no case, the user information will be given, provided or sold to third parties. For more information about user information use, please read our Privacy Policy
</p>

<p align="justify"><strong>3. - Web Platform Content Quality.</strong></p><p align="justify">
Data and other materials appearing on this platform have been entered following strict quality control procedures by a team of professional editors. However, Quality Tours is not responsible for the truthfulness, accuracy or reliability of the content of this platform, also the data should not be considered official. Prices of services listed in this medium may not be correct because that the accuracy of the information does not depend on Quality tours. Please, in the case of detecting misinformation, fill out the contact form to inform us the page(s) that show the error (s) and if you like you can send the correction proposal (s), citing where necessary sources to verify the information.
</p>

<p align="justify"><strong>4. - Intentional Damage.</strong></p><p align="justify">
Quality tours reserves the right to use the law to punish any intentional effort to manipulate information or our web platform software, willfully damage, and try to hack or compromise the security of the platform. In these cases Quality tours will have all the power to take legal actions on their behalf to offset the damage.
</p>

<p align="justify"><strong>5. - Damage to User Computers.</strong></p><p align="justify">
Quality tours is not responsible for any damages to computers as a result of accessing this Web platform, or any virus or similar that may affect your computer through this website or its services. However, we have a virus protection.
</p>

<p align="justify"><strong>6. Copyright.</strong></p><p align="justify">
Both  Quality Tours logo "tourist consultants" software, slogan, professionally translated descriptions of tourist companies are owned by Quality tours SA which owns all rights. The content (including photos) that tourist centers could upload to the web platform remain governed under the Creative Commons. For more information about this, please read our Terms of Service.
</p>

<p align="justify"><strong>7. Jurisdiction and Applicable Law.</strong></p><p align="justify">
This agreement shall be governed in all respects by the laws of the Republic of Chile. Any dispute arising under this agreement shall be subject to the applicable laws and courts of the city of Santiago de Chile and procedures will be conducted in Spanish language.
</p>

<p align="justify">If you have any questions about the Terms and Conditions please write to: qualitytoursadm@yahoo.com
    </p>    
 
</div>
