<!--PARA GOOGLE MAPS COMIENZO-->
<style type="text/css">
  html { height: 100% }
  body { height: 100%; margin: 0px; padding: 0px }
  #map_canvas { height: 100% }
</style>

<meta name="viewport" content="initial-scale=1.0, user-scalable=yes" />

<script type="text/javascript" src="https://maps.google.com/maps/api/js?sensor=false">
//Esto carga el api de Google Maps
</script>

<script type="text/javascript">
//Este código carga el mapa con un marcador en la ubicacion
//del centro turístico
//FUNCTION INITIALIZE
var map;
var latlng = new google.maps.LatLng(<?php echo $latitud; ?>,<?php echo $longitud; ?>)
$(document).ready(function(){

    //Setup del mapa
    var myOptions = {
          zoom: 14,
          center: latlng,
          mapTypeId: google.maps.MapTypeId.ROADMAP
        };
    map = new google.maps.Map(document.getElementById('map_canvas'),
            myOptions);
      
   marker = new google.maps.Marker({
            position: latlng,
            map: map,
            title:"<?php echo $nombre ?>"
        });
});
</script>

<table class="table table-bordered">
    <tr>  
        <thead>
            <td width="400px"><div id="map_canvas" style="width:400px; height:400px"></div></td>
            <td
                width="600px">
                <h2><?php echo $nombre_cliente?></h2>
                <br>
                <h2><?php echo $nombre?></h2>
                <br>
                <h3><?php echo  $precio?></h3>
                <br>
                <h4><?php echo $direccion."<br>".$ciudad."<br>".$region?></h4>
                <br>
                <h5><?php echo $detalle?></h5>
            </td>
        </thead>
    </tr>
</table>

