<?php
//Código para el idioma
    if($leng == "en")
    {
        include_once APP_PATH.'libs/en.php';
    }
    else
    {
        include_once APP_PATH.'libs/es.php';
    }
?>
<!--eliminar comentario-->
<script type="text/javascript">
    
    
    $(document).ready(function() {
        $('.delete').live( 'click', function() {
        //$('.delete').click(function()// NO FUNCIONABA CUANDO ELIMINA NUEVOS COMENTARIOS
           
            //Recogemos el valor del servicio
            var service = $(this).attr('id');
            
            var dataString = 'id='+service;
            
            $.ajax({
                type: "POST",
                url: "<?php echo PUBLIC_PATH; ?>ajax/eliminar_comentario.php",
                data: dataString,
                success: function() {            
                    //$('#delete-ok').empty();
                    //$('#delete-ok').append('<div>Se ha eliminado correctamente el servicio con id='+service+'.</div>').fadeIn("slow");
                    //$('#'+parent).remove();
                    $('#service'+service).remove();
                }
                
            }); //FIN AJAX
        });                 
    });    
</script>


<style>
    .delete {
cursor: pointer;
font-size: 16px;
font-weight: bold;
margin-left: 820px;
}
</style>
<!--PARA GOOGLE MAPS COMIENZO-->
<style type="text/css">
  html { height: 100% }
  body { height: 100%; margin: 0px; padding: 0px }
  #map_canvas { height: 100% }
</style>

<meta name="viewport" content="initial-scale=1.0, user-scalable=yes" />
<script type="text/javascript">
    var id_ser = <?php echo $id_servicio?>;
    var id_usu = <?php echo Auth::get('id')?>;
    
    
</script>

<script type="text/javascript" src="https://maps.google.com/maps/api/js?libraries=weather&sensor=false">
//Esto carga el api de Google Maps
</script>

<script type="text/javascript">
    //Este código carga el mapa con un marcador en la ubicacion
    //del centro turístico
    //FUNCTION INITIALIZE
    var map;
    var latlng = new google.maps.LatLng(<?php echo $latitud; ?>,<?php echo $longitud; ?>)
    $(document).ready(function(){
        
        //Setup del mapa
        var myOptions = {
            zoom: 14,
            center: latlng,
            mapTypeId: google.maps.MapTypeId.ROADMAP
        };
        map = new google.maps.Map(document.getElementById('map_canvas'),
        myOptions);
        
        marker = new google.maps.Marker({
            position: latlng,
            map: map,
            title:"<?php echo $nombre ?>"
        });
        
        //AGREGAMOS CAPA DE CLIMA
        var weatherLayer = new google.maps.weather.WeatherLayer({
            temperatureUnits: google.maps.weather.TemperatureUnit.CELSIUS
        });
        weatherLayer.setMap(map);
        
        //NUBES
        var cloudLayer = new google.maps.weather.CloudLayer();
        cloudLayer.setMap(map)     
        
    });
</script>
<!--FORMULARIO DE COMENTARIO-->
<script>
    $(document).ready(function(){
	$('#boton-enviar').click(function(event){
            
            event.preventDefault();
            var nombre = $('#nombre').val();
            var comentario = $('#comentario').val();
            if (nombre != '' && comentario != ''){
                $("#comentario").val('');
                $("#mensaje").fadeOut(1000, function(){
                    $.post(
                    "<?php echo PUBLIC_PATH;?>ajax/ingresar_comentario_serv.php", 
                    { nombre: nombre, comentario: comentario,  id_usu: id_usu,  id_ser: id_ser}, 
                    function(data) {
                        $("#comentarios").append(data);  
                        }, 
                        "html");
                        $('#mensaje').text('Comentario agregado!');
			});
                        }
                        else{}
                        
                    });
                    
                        });
 </script>
<?php 
    setlocale(LC_MONETARY, 'en_US');
    $number = $precio;
?>
 
 
<table class="table table-bordered">
    <tr>  
        <thead>
            <td width="400px"><div id="map_canvas" style="width:400px; height:400px"></div></td>
            <td
                width="600px">
                <h2><?php echo $nombre_cliente?></h2>
                <br>
                <h2><?php echo $nombre?></h2>
                <br>
                <h3><?php echo "$".$precio ?></h3>
                <br>
                <h4><?php echo $direccion."<br>".$ciudad."<br>".$region?></h4>
                <br>
                <h5><?php echo $detalle?></h5>
            </td>
        </thead>
    </tr>
</table>

  <?php 

                if($cont == 0)
                {

                }
                if($cont == 1)
                {?>
     
                          
                        <?php  for($i=0; $i<=$contador-1 ; $i++) 
                        {?>

                    <div class="service_list" id="service<?=$idComentario2[$i]?>" data="<?=$idComentario2[$i]?>">    
                        <table class="table table-hover">
                            <tr>
                                <td><?php echo "<b>".$nombre2[$i]."</b>"; ?></td>
                                <td><div align="right"><?php echo "<b>".$fecha2[$i]."</b>";
                                 if(Auth::is_valid())
                                 {
                                    if(Auth::get("id") ==  $id2[$i] || Auth::get("rol_usu") == "administrador")
                                    { ?>
                                        <a  class="delete" id="<?=$idComentario2[$i]?>"><i class="icon-remove"></i></a>  
                              <?php } 
                              
                                 }?>
                                 </div></td>
                            </tr>
                        </table>
                        <table>
                            <tr>
                                <td> <div align="left"> <?php echo $detalle2[$i];?> </div></td>
                            </tr> 
                        </table> 
                    </div>  
                    <?php  } //fin for?>

                <?php  }?>        
                <?php 
                    if(!Auth::is_valid())            
                    {
                        echo "<b>Login to post comments.</b>";
                    }
                    else
                    {  
                ?>
       <strong id="mensaje"> Agrega un nuevo comentario:</strong>

            <div id="comentarios">

                    <!-- aca apareceran los nuevos comentarios -->

            </div>

            <!--Formulario de comentario-->
          <form action="#">
                <?php echo Form::hidden("nombre",null,$nombre_usuario);?>  
                <div align="center"> <?php echo Form::text("comentario","class='span3  comentario'"); ?> </div>  
                <?php echo Form::hidden("id_usu",null,Auth::get("id") ); ?>
                <?php echo Form::hidden("id_ser", null,$id_servicio) ?>
                <div align="center"><input id="boton-enviar" type="submit" value="Comentar" class="btn btn-primary boton" /></div>
           </form>  
        
    <?php  }?>


            



