<?php
//Código para el idioma
    if($leng == "en")
    {
        include_once APP_PATH.'libs/en.php';
    }
    else
    {
        include_once APP_PATH.'libs/es.php';
    }
?>   

<div><?php View::content() ?></div> 
<script type="text/javascript">
    //activacion del modal de la cancelacion solicitud
    function activar_cancelacion () {
        $('#myModal').modal('toggle');
    };

</script>

<style>
    textarea {
        resize: none;
        width: 300px;
        height: 100px;

    }
</style>

<div align="center">
    <h2>  <?php echo $solicitud_administrar_solicitud_de;  echo $nombre_cli; ?></h2> <br>
    <table>
        <tr>
            <!--    Datos usuario/cliente-->        
            <td>
                <div align="center">

                    <dl>
                        <table class="table table-bordered">
                            <tr>
                                <td colspan="2"><center><h4><?php echo $solicitud_administrar_datos; ?> </h4></center></td>
                            </tr>  
                            <tr>
                                <td><dt><?php echo $solicitud_administrar_username; ?>:</dt></td>
                            <td width="250px"><dd><?php echo $nombre_usu ?></dd></td>
                            </tr>        
                            <tr>
                                <td><dt><?php echo $solicitud_administrar_nombre; ?>:</dt></td>
                            <td width="250px"><dd><?php echo $nombre_cli ?></dd></td>
                            </tr>
                            <tr>
                                <td><dt><?php echo $solicitud_administrar_privado; ?>:</dt></td>
                            <td width="250px"><dd><?php echo $rut_usu ?></dd></td>
                            </tr>
                            <tr>
                                <td><dt><?php echo $solicitud_administrar_comercial; ?>:</dt></td>
                            <td width="250px"><dd><?php echo $rut_cli ?></dd></td>
                            </tr>
                            <tr>
                                <td><dt><?php echo $solicitud_administrar_giro; ?>:</dt></td>
                            <td width="250px"><dd><?php echo $giro_cli ?></dd></td>
                            </tr>
                            <tr>
                                <td><dt><?php echo $solicitud_administrar_telefono; ?>:</dt></td>
                            <td width="250px"><dd><?php echo $telefono_cli ?></dd></td>
                            </tr>
                            <tr>
                                <td><dt><?php echo $solicitud_administrar_tipo; ?>:</dt></td>
                            <td width="250px"><dd><?php echo $tipo_plan ?></dd></td>
                            </tr>
                            <tr>
                                <td><dt><?php echo $solicitud_administrar_solicitud; ?>:</dt></td>
                            <td width="250px"><dd><?php echo $fecha_sol ?></dd></td>
                            </tr>
                            <tr>
                                <td><dt><?php echo $solicitud_administrar_estado; ?>:</dt></td>
                            <td width="250px"><dd><?php echo $estado_sol ?></dd></td>
                            </tr>
                        </table>
                    </dl>
                </div>
            </td>

            <td>
                &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
            </td>
            <!--    Opciones-->       
            <td>
<!--                Se verifica que la solicitud no este cancelada y rechazada-->
                <?php if ($estado_sol == "Cancelada" || $estado_sol == "Rechazada" || $estado_sol == "Aceptada") { ?>
                    <center><h4><?php echo $solicitud_administrar_observaciones; ?></h4></center>
                    <center><?php echo $observaciones ?></center>
                    <br></br>
                    <center><h4><?php echo $solicitud_administrar_notiene; ?></h4></center>
                    <center><a href='/trunk/qualitytours/solicitud/buscar'><button class="btn btn-success" type="button"><?php echo $usuario_automodificar_botonatras; ?></button></a></center>
                    
<!--                Si la solicitud no esta cancelada o rechazada muestra las opciones de administracion-->
                <?php } else { ?>
                    <center>
<!--                    Se verifica que el mail fue mandado y que el estado de la solicitud sea esperando, si esto se cumple se muestra el boton de aceptar solicitud-->
                    <?php if ($mail_sol == "t" && $estado_sol == "Esperando") {?><a href='/trunk/qualitytours/solicitud/aceptarsolicitud/<?php echo $id_usuario ?>/<?php echo $id_solicitud ?>/<?php echo $leng ?>'><button class="btn btn-small btn-success" type="button"><?php echo $solicitud_administrar_aceptar_sol; ?></button></a><?php }?>
<!--                    Se verifica que el mail no este mandando y que el estado de la solicitud sea pendiente, si esto se cumple se muestra los botones de aviso y rechazo-->
                    <?php if ($mail_sol == "f" && $estado_sol == "Pendiente") {?>
                    <a href='/trunk/qualitytours/solicitud/aviso/<?php echo $id_solicitud ?>/<?php echo $id_usuario ?>/<?php echo $leng;?>'<button class="btn btn-small btn-primary" type="button"><?php echo $solicitud_administrar_espera; ?></button></a>
                    <button class="btn btn-small btn-danger" type="button" onclick="activar_cancelacion()"><?php echo $solicitud_administrar_rechazar; ?></button><?php }?>
<!--                    Si el usuario no ha confirmado el envio del mail se muestra el mensaje-->
                    <?php if ($mail_sol == "f" && $estado_sol == "Esperando") {echo "<b>".$solicitud_administrar_mensaje1."</b>";}?>
                    </center>
                    
                    <br></br>
                    <center><h4><?php echo $solicitud_administrar_mensaje2; ?></h4></center>
                    <?php echo Form::open('solicitud/ingresarobservacion/' . $id_usuario . '/' . $id_solicitud."/".$leng) ?>
                    <center><?php echo Form::textarea('solicitud.observaciones_sol') ?></center>

                    <?php echo Form::hidden('solicitud.id') ?>
                    <?php echo Form::hidden('solicitud.id_usu') ?>
                    <?php echo Form::hidden('solicitud.id') ?>
                    <?php echo Form::hidden('solicitud.adm_id_usu') ?>
                    <?php echo Form::hidden('solicitud.fecha_sol') ?>
                    <?php echo Form::hidden('solicitud.estado_sol') ?>
                    <?php echo Form::hidden('solicitud.tipo_sol') ?>
                    <?php echo Form::hidden('solicitud.mail_sol') ?>
                    <?php echo Form::hidden('solicitud.modificaciones_sol') ?>
                    <?php echo Form::hidden('solicitud.activo_sol') ?>

                    <center><?php echo Form::submit(''.$solicitud_administrar_enviar.'', 'class="btn btn-submit boton"') ?></center>
                    <?php echo Form::close() ?>
                <?php } ?>
            </td>        
        </tr>
    </table>
</div>
<br></br>

<!--Modal para rechazar la solicitud-->

<div id="myModal" class="modal hide fade" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
    <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
        <h3 id="myModalLabel"><?php echo $solicitud_administrar_estaseguro; ?></h3>
    </div>
    <div class="modal-body">
        <p><b><?php echo $solicitud_administrar_modal1; ?></b></p>
        <p><?php echo $solicitud_administrar_modal2; ?></p>
        <p>- <?php echo $solicitud_administrar_modal3; ?></p>
    </div>
    <div class="modal-footer">
        <button class="btn" data-dismiss="modal" aria-hidden="true"><?php echo $solicitud_administrar_cerrar; ?></button>
        <a href="/trunk/qualitytours/solicitud/rechazar/<?php echo $id_solicitud ?>/<?php echo $id_usuario."/".$leng ?>"><button class="btn btn-primary"><?php echo $solicitud_administrar_rechazar; ?></button></a>
    </div>
</div>

