
<div><?php View::content() ?></div> 

<div align="center">
    <h1 style="font-family: SF"> Estado de tu solicitud </h1>
    <br></br>

    <table class="table table-condensed">
        <thead>
            <tr>
                <!-- cabecera de la tabla-->
                <th>Estado solicitud</th>
                <th>Fecha solicitud</th>
                <th>Tipo de solicitud</th>
                
                <?php if($colortabla== "info") {?>
                <th><center>Confirme envio mail</center></th>
                <?php } ?>
    
            </tr>
        </thead>        

        <tr class="<?php echo $colortabla ?>">
            <td><?php echo $estado ?></td>
            <td><?php echo $fecha ?></td>
            <td><?php echo $tipo ?></td>
            
            <?php if($colortabla== "info") {?>
            <td><center><button class="btn btn-small btn-success" type="button">Mail enviado</button></center></td>
            <?php } ?>
    
            <td><a href="/trunk/qualitytours/cliente/ver/<?php echo Auth::get("id") ?>"><button class="btn btn-small btn-info" type="button">Ver datos registro</button></a></td>
            <td><a href="/trunk/qualitytours/solicitud/cancela/<?php echo Auth::get("id") ?>"><button class="btn btn-small btn-danger" type="button">Cancelar solicitud</button></a></td>
        </tr>
    </table>
    <br></br>
    
    <table class="table table-bordered">
        <thead>
            <tr>
               <th><center> Observaciones </center></th>
            </tr>
        </thead>        
        <tbody>
            <tr>
                <td><center><?php echo $observaciones ?></center></td>
            </tr>
        </tbody>
        </table>
    <br></br>
</div>
