<?php 
    View::content() ;
?>
<script type="text/javascript"> //JQUERY PARA BUSQUEDA AJAX
    $(document).ready(function()
    {
        
        $.ajax
        ({
            
            type: "POST",
            data : {
                string: <?php echo "'".$string."'";?>
            },            
            url: '<?php echo PUBLIC_PATH; ?>ajax/busqueda_gral.php',
            dataType: "html",
            success: function(data)
            {
                var datos = data.split('SEPARADOR');
                var objetosJSON = new Array(3);
                
                for (i=0;i<datos.length;i++)
                {
                    objetosJSON[i] = $.parseJSON(datos[i]);
                    console.log(objetosJSON[i]);
                }
            }  // FIN SUCCESS 
        }); //FIN AJAX
        
        
    });
    
</script>
    