<div><?php View::content() ?></div> 
<?php echo  "<h6>Resultado de busqueda de :<b>".$busqueda."</b></h6><br>" ;  
$encontrar=0;
?>
    <table class="table">
        <tr>
            <td><div align='center'><b>Nombre</b></div></td>
            <td><div align='center'><b>Giro</b></div> </td>
            <td><div align='center'><b>Telefono</b></div> </td>
            <td><div align="center"><b>Servicio</b></div></td>
        </tr>   

<!--    BUSCANDO  POR REGION -->
 <?php $arr= Load::model('ubicacion')->find("columns: id_usu","conditions:  region_ubi='".$busqueda."'","order: id ASC"); ?>
 
     
     
     <?php foreach ($arr as $buscar ) 
       {
         
         //consultar por el cliente
            $encontrar=1;
            Load::model('cliente');
            $cliente = new Cliente();
            $cliente->find($buscar->id_usu,"condictions: estado_usu='t'");
            $nombre = $cliente->nombre_cli;
            $giro = $cliente->giro_cli;
            $telefono = $cliente->telefono_cli;
            //capturar servicio
            Load::model('servicio');
            $servicio = new Servicio();
            $servicio->find($buscar->id_usu,"condictions: estado_usu='t'");
            
            $ver = $servicio->id;
         
            
        ?>    
            <!--             Mostrar los datos encontrados:-->
<!--       <table class="table" align="center">-->
               <tr>
                   <td><?php echo"<div align='center'>".$nombre."</div>"; ?></td>
                   <td><?php echo"<div align='center'>".$giro."</div>"; ?></td>
                   <td><?php echo"<div align='center'>".$telefono."</div>"; ?></td>
                   <td><?php echo"<div align='center'> ".Html::link('servicio/detalle/'.$ver."","Visitar")."</div>";?></td>
                       
               </tr>    
        
             
                
                
 <?php } ?>
       </table>
        <table class="table">
      

<!--BUSCANDO POR CIUDAD-->

<?php $arr= Load::model('ubicacion')->find("columns: id_usu","conditions:  ciudad_ubi='".$busqueda."'","order: id ASC"); ?>
 
     
     
     <?php foreach ($arr as $buscar ) 
       {
            $encontrar=1;
            Load::model('cliente');
            $cliente = new Cliente();
            $cliente->find($buscar->id_usu,"condictions: estado_usu='t'");
            $nombre = $cliente->nombre_cli;
            $giro = $cliente->giro_cli;
            $telefono = $cliente->telefono_cli;
             //capturar servicio
            Load::model('servicio');
            $servicio = new Servicio();
            $servicio->find($buscar->id_usu,"condictions: estado_usu='t'");
            
            $ver = $servicio->id_usu;
            
            
       ?>    
            
<!--             Mostrar los datos encontrados:-->
          
               <tr>
                   <td><?php echo"<div align='center'>".$nombre."</div>"; ?></td>
                   <td><?php echo"<div align='center'>".$giro."</div>"; ?></td>
                   <td><?php echo"<div align='center'>".$telefono."</div>"; ?></td>
                   <td><?php echo"<div align='center'> ".Html::link('servicio/detalle/'.$ver."","Visitar")."</div>";?></td>
                       
               </tr>    
            
               
                
                
             
    <?php   } ?>
        </table>         


        <?php  
          if($encontrar == 0)
          {
              echo "<b>Lo sentimos no existen resultados para la búsqueda ingresada.</b>";
          }
        
        ?>