<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
    
    
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <title>Quality Tours | Error</title>
    <meta http-equiv="refresh" content="1; url=<?php echo PUBLIC_PATH."index"; ?>" />
</head>
<body>
    <div style="text-align: center; margin: 50px; font-size: 12pt; background-color: transparent; font-family: Lucida Grande, Verdana, Sans-serif;">
        <table align="center" id="content" style="background-color: #fff; border: #999 0px solid; padding: 10px 10px 6px 10px;">
            <tbody>
                <tr>
                    <td>
                        <a href="http://qualitytours.no-ip.org"><img width="800px"  src="<?php echo PUBLIC_PATH ?>img/logoes.png" alt="Kumbia PHP Framework"/></a>
                    </td>
                </tr>
                <tr>
                    <td>
                        <center><h2>Página no encontrada </h2></center>                       
                    </td>
                </tr>
            </tbody>
        </table>
    </div>
</body>
</html>
