<!DOCTYPE html>
<html lang="es">
 <head>
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta http-equiv='Content-type' content='text/html; charset=<?php echo APP_CHARSET ?>' />

  <title>Quality tours</title>
  <?php
  
  
    echo Tag::js('jquery/jquery-1.7.2.min');
    echo Tag::js('jquery/jquery.confirm-1.3');
    echo Tag::js('bootstrap.min');
    echo Tag::js('bootstrap-modal');
    echo Tag::js('bootstrap-typeahead');
    echo Tag::js('jquery.jsonp-2.1.4');
    echo Tag::js('starsManager');

  
    
   
    Tag::css('bienvenida');
    Tag::css('style');
    Tag::css('bootstrap.min');
    
    echo Html::includeCss();
  ?>
    
    <script>
        $('.dropdown-toggle').dropdown();
    </script>
    
<!--    Codigo de google analytics-->

<script type="text/javascript">

  var _gaq = _gaq || [];
  _gaq.push(['_setAccount', 'UA-36068749-1']);
  _gaq.push(['_trackPageview']);

  (function() {
    var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
    ga.src = ('https:' == document.location.protocol ? 'https://' : 'http://') + 'stats.g.doubleclick.net/dc.js';
    var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
  })();

</script>
<!--    Fin codigo de google analytics-->    

</head>
<body>
   <div class="container">
    <div id='content'>
        <div align="center">
    <?php 
    $url =  $_SERVER['REQUEST_URI'];
    //devuelve los 2 ultimos caracteres de la url si es igual a en se utiliza las variables en inglés
    $url = substr( $url,-2);
        if($url == "es" || $url == "s/" || $url =="ex" )
        {?>
 <?php   echo Html::img('logoes.png','logo','width="500px" height="300px"'); ?>
        </div> 
 <?php  }
 else
        {
            echo Html::img('logoen.png','logo2','width="500px" height="300px"');
            echo "</div>";
        }
 ?>
    

<!-- Partial del menu-->
   <div> <?php View::partial('kumbia/menuprincipal') ?></div> 
          
        <!--Muestra la pagina correspondiente (vista)-->
       
        <?php View::content(); ?>
        
          <!--Muestra el footer-->
     
    
        
    </div>
   </div>
    <div> <?php View::partial('kumbia/footer') ?> </div>
     
</body>
</html>
