<?php
    View::content();
    require(APP_PATH.'libs/PHPMailer_5.2.2-rc2/class.phpmailer.php');
    require(APP_PATH.'libs/PHPMailer_5.2.2-rc2/class.smtp.php');
    $mail = new PHPMailer();
    $mail->IsSMTP();
    //$mail->SMTPSecure = "ssl";
    $mail->SMTPAuth = true;
    $mail->SMTPDebug = 1;  // debugging: 1 = errors and messages, 2 = messages only
    $mail->Host = "smtp.mail.yahoo.com";
    $mail->Port = 25;
    $mail->Username = "qualitytoursadm@yahoo.com";
    $mail->Password = "qt123123";
    
    
    
    
?>

<?php


if (isset($_POST['enviar'])) 
{
    //Preparar el mail
    //$mail->From = $_POST['email'];
    $mail->From = "qualitytoursadm@yahoo.com";
    $mail->FromName = $_POST['email']." - ".$_POST['username']." - QTours";
    $mail->Subject = $_POST['asunto'];
    $mail->Body = stripcslashes($_POST['mensaje']);
    $mail->AddAddress($email_cli, "Destinatario"); //Dirección a la que enviaremos el correo
    $mail->IsHTML(true);
    
    if(!$mail->Send()){
    echo "Error: " . $mail->ErrorInfo;
    } else {
    //echo "Mensaje enviado correctamente";
    Flash::success("Mensaje enviado correctamente");
    Router::redirect('/');
    }
  
}
?> 
<style>
    .div_contacto
    {
        text-align: center;
    }
</style>

<script type="text/javascript">
    //Validación con jquery
$(document).ready(function () {
   
    $(".boton").click(function (){
        $(".errorVal").remove();
        
         if( $(".asunto").val() == "" ){
            $(".asunto").focus().after("<span class='errorVal'>El asunto no puede estar vacío</span>");
            return false;
        }else if( $(".asunto").val().length<3){
            $(".asunto").focus().after("<span class='errorVal'>El asunto debe tener al menos 3 letras</span>");
            return false;
        }else if( $(".body").val() == ""){
            $(".body").focus().after("<span class='errorVal'>El mensaje no puede estar vacío</span>");
            return false;
        }else if( $(".body").val().length<10){
            $(".body").focus().after("<span class='errorVal'>El mensaje debe tener al menos 10 letras</span>");
            return false;
        }
    });
    
    //Borrar mensaje de error si el usuario a llenado el campo
    $(".asunto, .body").keyup(function()
    {
        if( $(this).val() != "" )
        {
            $(".errorVal").fadeOut();
            return false;
        }
    });
    
    });
    
</script>

<style>
    .errorVal{
    background-color: #BC1010;
    padding: 6px 12px;
    border-radius: 4px;
    color: white;
    font-weight: bold;
    margin-left: 16px;
    margin-top: 6px;
    position: absolute;
}
.errorVal:before{ /* Este es un truco para crear una flechita */
    content: '';
    border-top: 8px solid transparent;
    border-bottom: 8px solid transparent;
    border-right: 8px solid #BC1010;
    border-left: 8px solid transparent;
    left: -16px;
    position: absolute;
    top: 5px;
}
</style>


<?php

echo '<div class="div_contacto">
<h1 style="font-family: SF"> Contactar: '.$nombre_cli.'</h1>    
<form action="" method="post">  
<input type="hidden" value="'.$username_usu.'" name="username" size="50" maxlength="80">
<input type="hidden" value="'.$email_usu.'"  name="email" size="50" maxlength="60"> <label for="asunto">Asunto : </label>
<input type="text" name="asunto" size="50" class="asunto" maxlength="60"><br> <label for="mensaje">Mensaje : </label>  <textarea name="mensaje" class="body" cols="31" rows="5"></textarea> <br>
<label for="enviar">
<input type="submit" class="boton" name="enviar" value="Enviar consulta"></label>
 </form></div>';
?>