<?php
    View::content();
    require(APP_PATH.'libs/PHPMailer_5.2.2-rc2/class.phpmailer.php');
    require(APP_PATH.'libs/PHPMailer_5.2.2-rc2/class.smtp.php');
    $mail = new PHPMailer();
    $mail->IsSMTP();
    //$mail->SMTPSecure = "ssl";
    $mail->SMTPAuth = true;
    $mail->SMTPDebug = 1;  // debugging: 1 = errors and messages, 2 = messages only
    $mail->Host = "smtp.mail.yahoo.com";
    $mail->Port = 25;
    $mail->Username = "qualitytoursadm@yahoo.com";
    $mail->Password = "qt123123";
    
    
    
    
?>

<?php


if (isset($_POST['enviar'])) 
{
    //Preparar el mail
    //$mail->From = $_POST['email'];
    $mail->From = "qualitytoursadm@yahoo.com";
    $mail->FromName = $_POST['email'];
    $mail->Subject = $_POST['asunto']." - Usuario:".$_POST['username'];
    $mail->Body = stripcslashes($_POST['mensaje']);
    $mail->AddAddress("qualitytoursadm@yahoo.com", "Destinatario"); //Dirección a la que enviaremos el correo
    $mail->IsHTML(true);
    
    if(!$mail->Send()){
    echo "Error: " . $mail->ErrorInfo;
    } else {
    //echo "Mensaje enviado correctamente";
    Flash::success("Mensaje enviado correctamente");
    Router::redirect('/');
    }
  
}
?> 
<style>
    .div_contacto
    {
        text-align: center;
    }
</style>    
<?php

echo '<div class="div_contacto">
<h1 style="font-family: SF"> Contacto administrador </h1>    
<form action="" method="post">  
<input type="hidden" value="'.$username_usu.'" name="username" size="50" maxlength="80">
<input type="hidden" value="'.$email_usu.'"  name="email" size="50" maxlength="60"> <label for="asunto">Asunto : </label>
<input type="text" name="asunto" size="50" maxlength="60"><br> <label for="mensaje">Mensaje : </label>  <textarea name="mensaje" cols="31" rows="5"></textarea> <br>
<label for="enviar">
<input type="submit" name="enviar" value="Enviar consulta"></label>
 </form></div>';
?>