<?php
View::content();
?>
<script type="text/javascript"> //JQUERY PARA BUSQUEDA AJAX
    $(document).ready(function()
    {
        
        $.ajax
        ({
            
            type: "POST",
            data : {
                string: <?php echo "'" . $string . "'"; ?>
            },            
            url: '<?php echo PUBLIC_PATH; ?>ajax/busqueda_gral.php',
            dataType: "html",
            success: function(data)
            {
                var datos = data.split('SEPARADOR');
                var objetosJSON = new Array(3);
                
                for (i=0;i<datos.length;i++)
                {
                    objetosJSON[i] = $.parseJSON(datos[i]);
                    //console.log(objetosJSON[i]);
                    
                    if(i==0)
                    {
                        $(".resultados").append("<h4>Centros tur&iacute;sticos</h4>");
                        //$(".resultados").append("");
                        $(".resultados").append("<table class='table table-condensed tclientes'>");
                        $(".tclientes").append("<thead><tr></tr></thead>");
                        $(".tclientes thead tr").append("<th>Nombre Cliente</th>");
                        $(".tclientes thead tr").append("<th>Ciudad</th>");
                        $(".tclientes thead tr").append("<th>Region</th>");
                        $(".tclientes thead tr").append("<th>Calificaci&oacute;n</th>");
                        alert(objetosJSON.length);
                        for (x=0;x<objetosJSON[i].length;x++)
                        {
                            $(".tclientes").append("<tr class='c1res"+x+"'>");
                            $(".c1res"+x).append("<td><a href='/trunk/qualitytours/cliente/detalle/"+objetosJSON[i][x].id_cliente+"/es'>"+objetosJSON[i][x].nombre_cliente+"</a></td><td>"+objetosJSON[i][x].ciudad+"</td><td>"+objetosJSON[i][x].region+"</td>")
                            
                            if (objetosJSON[i][x].promedio == 0)
                                {
                                    $(".c1res"+x).append("<td>Sin calificaciones</td>")
                                }
                            else
                                {
                                    var calificacion = objetosJSON[i][x].promedio;
                                    calificacion = Math.round(calificacion*100) / 100;
                                    $(".c1res"+x).append("<td>"+calificacion+"</td>");
                                }
                            $(".tclientes").prepend("</tr>");
                        }
                        $(".resultados").prepend("</table>");
                    } //FIN IF
                    
                }  // FIN FOR
            }  // FIN SUCCESS 
        }); //FIN AJAX
        
        
    });//FIN DOCUMENT READY JQUERY
</script>


<div class="resultados" style="text-align: center;" align="center">

</div>