<?php 

 $arr= Load::model('ubicacion')->find();

?>


<script type="text/javascript">
        jQuery(document).ready(function() {
            var alCities = [
                
            <?php    foreach ($arr as $ubicaciones)
            {
                echo "'".$ubicaciones->region_ubi."','".$ubicaciones->ciudad_ubi."', ";  
            }
            ?>           
                
            ].sort();
            $('#city').typeahead({source: alCities, items:5});
        });
 </script>




 
 
Buscar ubicación:<input type="search" id="city" name="city" placeholder="Type a city name" data-provide="typeahead" class="search-query" />