<div><?php View::content() ?></div> 
<script type="text/javascript">
    //activacion del modal de la cancelacion solicitud
    function activar_renovar () {
        $('#renovar').modal('toggle');
    };

</script>

<style>
    textarea {
        resize: none;
        width: 300px;
        height: 100px;

    }
</style>

<div align="center">
    <h2> Datos de la suscripción </h2> <br>
    <table>
        <tr>
            <!--    Datos usuario/cliente-->        
            <td>
                <div align="center">

                    <dl>
                        <table class="table table-bordered">
                            <tr>
                                <td><dt>Nombre de usuario:</dt></td>
                            <td width="250px"><dd><?php echo $nombre_usu ?></dd></td>
                            </tr>        
                            <tr>
                                <td><dt>Nombre de centro turistico:</dt></td>
                            <td width="250px"><dd><?php echo $nombre_cli ?></dd></td>
                            </tr>
                            <tr>
                                <td><dt>Rut privado:</dt></td>
                            <td width="250px"><dd><?php echo $rut_usu ?></dd></td>
                            </tr>
                            <tr>
                                <td><dt>Rut comercial:</dt></td>
                            <td width="250px"><dd><?php echo $rut_cli ?></dd></td>
                            </tr>
                            <tr>
                                <td><dt>Giro:</dt></td>
                            <td width="250px"><dd><?php echo $giro_cli ?></dd></td>
                            </tr>
                            <tr>
                                <td><dt>Telefono comercial:</dt></td>
                            <td width="250px"><dd><?php echo $telefono_cli ?></dd></td>
                            </tr>
                            <tr>
                                <td><dt>Tipo de plan:</dt></td>
                            <td width="250px"><dd><?php echo $tipo_plan ?></dd></td>
                            </tr>
                            <tr>
                        </table>
                    </dl>
                </div>
            </td>

            <td>
                &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
            </td>
            <!--    Opciones-->       
            <td>
                <dl>
                    <table class="table table-bordered">
                        <thead>
                            <tr>
                                <th><dt>Fecha solicitud</dt></th>
                        <th><dt>Fecha de inicio</dt</th>
                        <th><dt>Fin suscripción</dt></th>
                        </tr>
                        </thead>
                        <tbody>
                            <tr>
                                <td width="120px"><dd><?php echo $fecha_solicitud ?></dd></td>
                        <td width="120px"><dd><?php echo $ini_sus ?></dd></td>
                        <td width="120px"><dd><?php echo $fin_sus ?></dd></td>
                        </tr>
                        </tbody>
                    </table>
                    <table class="table table-bordered">
                        <thead>
                            <tr>
                                <th><center><dt>Observacion</dt></center></th>
                        </tr>
                        </thead>
                        <tbody>
                            <tr>
                                <td width="120px"><dd><?php echo $observaciones ?></dd></td>
                        </tr>
                        </tbody>
                    </table>
                    <?php
                    if (isset($muestra_boton)) {
                        if ($muestra_boton == "Si") { ?>
                            
                            <center><button class="btn btn-success" type="submit" onclick="activar_renovar()">Renovar suscripción</button></center>
                            <p align="center">Si desea cambiar los datos de la suscripcion, debe esperar<br>
                                a que la actual termine para mandar una nueva solicitud</p>
                    <?php   }
                        } else if(isset($existe)){echo $existe;}
                        else if(isset($noexiste)){echo $noexiste;}
                        
                        ?>
                </dl>
            </td>        
        </tr>
    </table>
</div>
<div id="renovar" class="modal hide fade" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
    <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
        <h3 id="myModalLabel">¿ Esta seguro de renovar la suscripción?</h3>
    </div>
    <div class="modal-body">
        <p><b>Al renovar su suscripción usted acepta las condiciones del servicio</b><br>
            Observaciones: <br> 
        <ul>1.- Asegurece que los datos mostrados corresponden a su centro turistico</ul>
        <ul>2.- La solicitud de renovacion tiene que ser confirmada por un administrador</ul></p>
    </div>
    <div class="modal-footer">
        <button class="btn" data-dismiss="modal" aria-hidden="true">Cerrar</button>
        <a href="/trunk/qualitytours/solicitud/renovarsuscripcion"><button class="btn btn-primary">Renovar suscripción</button></a>
    </div>
</div>

