<div><?php View::content() ?></div> 
<!--PARA GOOGLE MAPS COMIENZO-->
<style type="text/css">
  html { height: 100% }
  body { height: 100%; margin: 0px; padding: 0px }
  #map_canvas { height: 100% }
</style>

<meta name="viewport" content="initial-scale=1.0, user-scalable=yes" />

<script type="text/javascript" src="https://maps.google.com/maps/api/js?sensor=false">
//Esto carga el api de Google Maps
</script>

<script type="text/javascript">
//Este código carga el mapa con un marcador en la ubicacion
//del centro turístico
//FUNCTION INITIALIZE
var map;
var latlng = new google.maps.LatLng(<?php echo $latitud; ?>,<?php echo $longitud; ?>)
$(document).ready(function(){

    //Setup del mapa
    var myOptions = {
          zoom: 14,
          center: latlng,
          mapTypeId: google.maps.MapTypeId.ROADMAP
        };
    map = new google.maps.Map(document.getElementById('map_canvas'),
            myOptions);
      
  
  marker = new google.maps.Marker({
            position: latlng,
            map: map,
            title:"<?php echo  $nombre_cliente ?>"
        });
});
</script>

<table class="table table-bordered">
    <tr>  
        <thead>
            <td width="400px"><div id="map_canvas" style="width:400px; height:400px"></div></td>
            <td width="600px">
                <h3><?php echo $nombre_cliente?></h3><br>
                <?php
                foreach ($array_servicios as $servicio) {
                    echo Html::link("servicio/detalle/" . $servicio->id, "Servicio: " . $servicio->nombre_ser . "<br>");
                }
                ?>
            </td>
                
        </thead>
    </tr>
    
    <?php
        //Trozo PHP para verificar si hay imagenes
        if (count($contenido) > 0)
        {
            echo "<tr><td colspan='2'><center>";
            foreach($contenido as $buscar)
            {
                echo  Html::img("../default/public/img/upload/".$buscar->ruta_con,"imagen","width=200 height=150");
            }   
            echo "</center></td></tr>";
        }
    ?>
</table>


