<?php
//Código para el idioma
    if($leng == "en")
    {
        include_once APP_PATH.'libs/en.php';
    }
    else
    {
        include_once APP_PATH.'libs/es.php';
    }
?>    
<div><?php View::content() ?></div> 
<!--PARA GOOGLE MAPS COMIENZO-->
<style type="text/css">
  html { height: 100% }
  body { height: 100%; margin: 0px; padding: 0px }
  #map_canvas { height: 100% }
</style>
<!--
El CSS a continuación da estilo a los mensaje de error en la validación
, no se usó "error" ya que kumbia ya tiene un estilo para esa clase, en su
reemplazo se uso 'errorVal'.
-->
<script type="text/javascript">
    $(document).ready(function () {
        
        $(".boton").click(function (){
        $(".errorVal").remove();
        
        
         if( $(".detalle").val() == "" ){
             $(".detalle").focus().after("<span class='errorVal'>Ingrese un comentario</span>");
             return false;
             }
         });
    
    
    //Borrar mensaje de error si el usuario a llenado el campo
    $(".detalle").keyup(function()
    {
        if( $(this).val() != "" )
        {
            $(".errorVal").fadeOut();
            return false;
        }
    });
    
});
    
</script>
<style>
    .errorVal{
    background-color: #BC1010;
    padding: 6px 12px;
    border-radius: 4px;
    color: white;
    font-weight: bold;
    margin-left: 16px;
    margin-top: 6px;
    position: absolute;
}
.errorVal:before{ /* Este es un truco para crear una flechita */
    content: '';
    border-top: 8px solid transparent;
    border-bottom: 8px solid transparent;
    border-right: 8px solid #BC1010;
    border-left: 8px solid transparent;
    left: -16px;
    position: absolute;
    top: 5px;
}
</style>



     <meta name="viewport" content="initial-scale=1.0, user-scalable=yes" />

<script type="text/javascript" src="https://maps.google.com/maps/api/js?libraries=weather&sensor=false">
//Esto carga el api de Google Maps
</script>

<script type="text/javascript">
//Este código carga el mapa con un marcador en la ubicacion
//del centro turístico
//FUNCTION INITIALIZE
var map;
var latlng = new google.maps.LatLng(<?php echo $latitud; ?>,<?php echo $longitud; ?>)
$(document).ready(function(){

    //Setup del mapa
    var myOptions = {
          zoom: 12,
          center: latlng,
          mapTypeId: google.maps.MapTypeId.ROADMAP
        };
    map = new google.maps.Map(document.getElementById('map_canvas'),
            myOptions);
      
  
  marker = new google.maps.Marker({
            position: latlng,
            map: map 
            //,title:
        });
        var calificacion;
 
//AGREGAMOS CAPA DE CLIMA
 var weatherLayer = new google.maps.weather.WeatherLayer({
  temperatureUnits: google.maps.weather.TemperatureUnit.CELSIUS
});
weatherLayer.setMap(map);

//NUBES
var cloudLayer = new google.maps.weather.CloudLayer();
cloudLayer.setMap(map)



});
</script>
<script>
  /* @version 1.0 starsManager
 * @author Lucas Forchino
 * @webSite: http://www.jqueryload.com
 * jpsonp rating Example.
 * This example show you how to create a rating using jsonp and jquery.
 */
(function(){
    LKS={};
    LKS.params={};
    LKS.params.stars=5;
    LKS.params.url='http://www.jqueryload.com/examples/stars/test.php?callback=LKS.draw';
    LKS.start= function(){
        $.jsonp( {'url':LKS.params.url});
    }
    var calificacion;
    LKS.sendVote = function (id,vote){
      
      calificacion = id;
        $(".stars").click(function()
        {   //CUANDO SE HACE CLICK EN LAS ESTRELLAS
            
            //CODIGO AJAX
            $.ajax
            ({
                type: 'POST',
                data: {
                //id_cli: $('#id_cli').val(),
                id_cli : <?php echo Auth::get('id'); ?>,
                id_usu: <?php echo $id_cliente ?>,
                cal   : calificacion
                },
                url: '<?php echo PUBLIC_PATH;?>ajax/ingresar_calificacion.php',
                dataType: 'text',
                success: function(data)
                {
                    if(data == 'exito')
                    {
                        //alert("Calificación ingresada");
                    }
                    else
                    {
                        alert("Error en el ingreso de la calificación, inténtelo mas tarde.");
                    }
                }
                
             
            });
        });
    }
    LKS.draw = function(data){
        $('.stars').each(function(index,item){
            var id=$(item).attr('itemid');
            $(item).attr('value',data[id]);
        });
        $('.stars').each(function(index,item){
            var n;
            var value= $(item).attr('value');
            for (n=0;n<LKS.params.stars;n++){
                var star=$('<a>');
                star.addClass('star');
                star.attr('href','javascript:void(0)');
                star.attr('vote',n+1);
                if (n<=value)
                {star.addClass('point');}
                $(item).append(star);
                
                
            }
        });
        $('.stars a').bind('mouseover',function(data){
            var childs=$(data.target).parent().children();
            childs.each(function(index,item){
                if ($(this).index() <= $(data.target).index())
                    {$(item).addClass('hover');}
                else
                    {$(item).removeClass('hover');}

            })
        })
        $('.stars a').bind('mouseout',function(data){
            var childs=$(data.target).parent().children();
            $(childs).removeClass('hover');
        });
       $('.stars a').bind('click',function(){
              var item=$(this).parent().attr('itemid');
              var vote=$(this).attr('vote');
              LKS.sendVote(vote);
              
       });

    }
}());  
</script>    
 <script>
        $(document).ready(function(){
            LKS.start();
            
            
    
        });
 </script>
 
         <table class="table table-bordered">
                <tr>  
                    <thead>
                        <td width="400px"><div id="map_canvas" style="width:400px; height:400px"></div></td>
                        <td width="600px">
                            <h3><?php echo $nombre_cliente; ?></h3> <?php echo"<span class='label label-info'>".$mostrar.":&nbsp;Views</span>";?><br>
                            <?php


                                foreach ($array_servicios as $servicio) {
                                        echo Html::link("servicio/detalle/" . $servicio->id, "Services: " . $servicio->nombre_ser . "<br>");
                                    }  
                                    ?>
                        </td>

                    </thead>
                </tr>
                <tr>
                    
                    <td> 
            <a id='accion'>accion</a>
       <div id='response'></div>  

                      
                        <div class="stars"  value="1.5" > </div>
                  </td>
                </tr>



                <?php
                    //Trozo PHP para verificar si hay imagenes
                    if (count($contenido) > 0)
                    {
                        echo "<tr><td colspan='2'><center>";
                        foreach($contenido as $buscar)
                        {
                            echo  Html::img("../default/public/img/upload/".$buscar->ruta_con,"imagen","width=200 height=150");
                        }   
                        echo "</center></td></tr>";
                    }
                ?>

            </table>   
       
            
            <?php 

                if($cont == 0)
                {

                }
                if($cont == 1)
                {?>
                <div class="span12">
                         <ul class="nav nav-list inverse">
                         <li class="active"><a href="#"><i class="icon-pencil"></i><?php echo "<b>".$numComentarios."</b>:&nbsp; "; ?>Comments</a></li>

                         </ul>   

                      <?php  for($i=0; $i<=$contador-1 ; $i++) 
                            {?>

                                <table class="table table-hover">
                                    <tr>
                                        <td><?php echo "<b>".$nombre[$i]."</b>"; ?></td>
                                        <td><div align="right"><?php echo "<b>".$fecha[$i]."</b>";?></div></td>
                                    </tr>
                                </table>
                                <table>
                                    <tr>
                                        <td> <div align="left"> <?php echo $detalle[$i];?> </div></td>
                                     </tr>  
                                    <?php 
                                   if(!Auth::is_valid())
                                    {
                                        $variable = Auth::is_valid();
                                    }
                                    else
                                    {
                                     if(Auth::get("id") ==  $id[$i])
                                             { ?>
                                             <tr>
                                                 <td><?php echo Html::link("comentario/eliminar/".$idComentario[$i]."/".$id_cliente.'/'.$leng, "Remove");?></td>
                                             </tr>                             
                                       <?php }  

                                    }?>


                                 </table> 




                    <?php   }?>
               </div>    
              <?php  }?>




             <?php 
             if(!Auth::is_valid())            
             {
                 echo "<b>Login to post comments.</b>";
             }
             else
             {  
            ?>

            <!--Formulario de comentario-->
            <div align="center" class="span12">
                <?php echo Form::open('comentario/ingresar/'.$id_cliente.'/'.$leng); ?>
                    <table>
                       <tr>
                           <td><?php echo Form::text('comentario.detalle_com', "class='span3 detalle' placeholder='Write a comment...'") ?></td>
                       </tr>    
                       <tr>
                           <td><?php echo Form::submit('Comment','class="btn btn-primary boton"'); ?> </td> 
                       </tr>

                    </table>
            </div>

              <?php  
                setlocale ( LC_TIME, 'spanish' );
                $fecha = strftime(date('Y/m/d'));
                echo Form::hidden('comentario.id_usu','null',Auth::get('id'));
                echo Form::hidden("comentario.fecha_com","null",$fecha);
                echo Form::hidden("comentario.estado_com","null",1);
                echo Form::hidden("comentario.cli_id_usu","null",$id_cliente);
                echo Form::close();    

              }?>


            
