<?php
//Código para el idioma
    if($leng == "en")
    {
        include_once APP_PATH.'libs/en.php';
    }
    else
    {
        include_once APP_PATH.'libs/es.php';
    }
?>    

<div>
    <?php
    View::content();
    echo Tag::js("jquery/jquery.Rut.min");
    ?>
</div> 

<script type="text/javascript">
    var cats;
    
    //Validación con jquery
    //El siguiente script valida que los campos no estén vacios y el formato del RUT
    $(document).ready(function () {
        var rutreg = /^\d{1,2}\.\d{3}\.\d{3}[-][0-9kK]{1}$/;
        
        $(".boton").click(function (){
            
            //SE LIMPIA ARRAY CATEGORIAS
            cats=' ';
            //array_categorias.length = 0;
        
            //CAPTURA DE LAS CATEGORIAS
            $(".categoria.active").each(function()
            {
                //array_categorias.push($(this).val());
                cats = cats+"."+$(this).val();
                
            });
            //enviar al controlador
            //cats=array_categorias[0];
            $(".categorias_string").val(cats);
      
            $(".errorVal").remove();
            if( $(".nombre").val() == "" ){
                $(".nombre").focus().after("<span class='errorVal'><?php echo $solicitud_ingresarsol_valnombre; ?></span>");
                return false;
            }else if( $(".rutp").val() == ""){
                $(".rutp").focus().after("<span class='errorVal'><?php echo $solicitud_ingresarsol_valrut; ?></span>");
                return false;
            }else if( $(".rut").val() == ""){
                $(".rut").focus().after("<span class='errorVal'><?php echo $solicitud_ingresarsol_valrutvalido; ?></span>");
                return false;
            }else if(!$.Rut.validar($(".rut").val()) ){
                $(".rut").focus().after("<span class='errorVal'><?php echo $solicitud_ingresarsol_valrutvalido; ?></span>");
                return false;
            }else if(!$.Rut.validar($(".rutp").val()) ){
                $(".rutp").focus().after("<span class='errorVal'><?php echo $solicitud_ingresarsol_valrutvalido; ?></span>");
                return false;
            }else if( $(".giro").val() == ""){
                $(".giro").focus().after("<span class='errorVal'><?php echo $solicitud_ingresarsol_valgiro; ?></span>");
                return false;
            }else if( $(".telefono").val() == "" ){
                $(".telefono").focus().after("<span class='errorVal'><?php echo $solicitud_ingresarsol_valtelefono; ?></span>");
                return false;
            }else if($('#acepta').is(':checked') == false){
                $("#acepta").focus().after("<span class='errorVal'><?php echo $solicitud_ingresarsol_valterminos; ?></span>");
                return false;
            }
            
            //VALIDAMOS LOS RUTS
            var rut_repetido=0;
            
            $.ajax //VALIDACION RUT PRIVADO
            ({

                type: "POST",
                async: false,
                data : {
                    tipo_rut: 'privado',
                    rut: $(".rutp").val()
                },            
                url: '<?php echo PUBLIC_PATH; ?>ajax/validar_rut.php',
                dataType: "text",
                success: function(data)
                {
                    if (data == "repetido")
                    {
                        $(".rutp").focus().after("<span class='errorVal'><?php echo $solicitud_ingresarsol_valrutrepetido; ?></span>");
                        rut_repetido=1;
                    }
                    
                }
            })
            
            $.ajax //VALIDACION RUT PRIVADO
            ({

                type: "POST",
                async: false,
                data : {
                    tipo_rut: 'comercial',
                    rut: $(".rut").val()
                },            
                url: '<?php echo PUBLIC_PATH; ?>ajax/validar_rut.php',
                dataType: "text",
                success: function(data)
                {
                    if (data == "repetido")
                    {
                        $(".rut").focus().after("<span class='errorVal'><?php echo $solicitud_ingresarsol_valrutrepetido; ?></span>");
                        rut_repetido=1;
                    }
                    
                }
            })
            
            if (rut_repetido==1) return false;
            //FIN VALIDCION RUTS
            
        });

        //Borrar mensaje de error si el usuario a llenado el campo
        $(".nombre, .giro, .telefono").keyup(function()
        {
            if( $(this).val() != "" )
            {
                $(".errorVal").fadeOut();
                return false;
            }
        });

        //Para el caso del listbox, no se puede borrar el error de validación con keyup
        //Ya que no es un textbox, usamos el metodo blur
        // $(".seleccion_usuario").blur(function()
        // {
        // if( $(this).val() != "" )
        //  {
        //     $(".errorVal").fadeOut();
        //     return false;
        //  }
        //});

        //Borrar el mensaje de error si el usuario ingresa un rut con formato válido
        $(".rutp").keyup(function()
        {   
            if( $(this).val() != "" && rutreg.test($(this).val()))
            {
                $(".errorVal").fadeOut();
                return false;
            }
        });
        //Borrar el mensaje de error si el usuario ingresa un rut con formato válido
        $(".rut").keyup(function()
        {   
            if( $(this).val() != "" && rutreg.test($(this).val()))
            {
                $(".errorVal").fadeOut();
                return false;
            }
        });        
        
        //Borrar el mensaje de error si el usuario ingresa un rut con formato válido 
        $(".rutp").Rut({
            on_error: function(){  $(".rutp").focus().after("<span class='errorVal'><?php echo $solicitud_ingresarsol_valrutinvalido; ?></span>"); return false; },
            format_on: 'keyup'
        });
    
        $(".rut").Rut({
            on_error: function(){  $(".rut").focus().after("<span class='errorVal'><?php echo $solicitud_ingresarsol_valrutinvalido; ?></span>"); return false; },
            format_on: 'keyup'
        });

        $(".rutp").keyup(function()
        {
            if( $(".rutp").val() != "" && rutreg.test($(".rutp").val()))
            {
                $(".errorVal").fadeOut();
                return false;
            }
        });
    
        $(".rut").keyup(function()
        {
            if( $(".rut").val() != "" && rutreg.test($(".rut").val()))
            {
                $(".errorVal").fadeOut();
                return false;
            } 
        });
    });
</script>

<!--
El CSS a continuación da estilo a los mensaje de error en la validación
, no se usó "error" ya que kumbia ya tiene un estilo para esa clase, en su
reemplazo se uso 'errorVal'.
-->

<style>
    .errorVal{
        background-color: #BC1010;
        padding: 1px 2px;
        border-radius: 4px;
        color: white;
        /*        font-weight: bold;*/
        margin-left: -330px;
        margin-top: 20px;
        position: absolute;
    }
    /*    .errorVal:before{  Este es un truco para crear una flechita 
            content: '';
            border-top: 8px solid transparent;
            border-bottom: -18px solid transparent;
            border-right: 8px solid #BC1010;
            border-left: 180px solid transparent;
            left: -28px;
            position: absolute;
            top: 25px;
        }*/
</style>

<br>
<fieldset>

    <div align="center">
        <h2><?php echo $solicitud_ingresarsol_titulo;  ?></h2>
        <table>
            <tr>
                <td>
                    <h4><center> Ingrese los datos del centro turistico</center></h4>
                    <table class="table table-bordered">
                        <?php $data = array('free' => 'Free', 'normal' => 'Normal', 'plus' => 'Plus'); ?>

                        <?php echo Form::open('cliente/ingresarsolicitud/'.$leng) ?>
                        <tr>
                            <td><?php echo $usuario_ingresar_usuario; ?>:&nbsp;</td>
                            <td><?php echo Auth::get('username_usu') ?></td>
                        </tr>        
                        <tr>
                            <td><?php echo $solicitud_ingresarsol_nomcentroturistico; ?>:&nbsp;</td>
                            <td><?php echo Form::text('cliente.nombre_cli', "class='input-medium nombre mask-alphanum' placeholder='".$solicitud_ingresarsol_phnombrecliente ."'") ?></td>
                        </tr>
                        <tr>
                            <td><?php echo  $solicitud_ingresarsol_rutprivado;  ?>:&nbsp;</td>
                            <td><?php echo Form::text('cliente.rut_usu', "class='input-medium rutp' placeholder='ej: 6.765.223-1' rutp") ?></td>
                        </tr>
                        <tr>
                            <td><?php echo $solicitud_ingresarsol_rutcomercial;  ?>:&nbsp;</td>
                            <td><?php echo Form::text('cliente.rut_cli', "class='input-medium rut' placeholder='ej: 6.765.223-1' rut") ?></td>
                        </tr>
                        <tr>
                            <td><?php echo $solicitud_ingresarsol_giro;  ?>:&nbsp;</td>
                            <td><?php echo Form::text('cliente.giro_cli', "class='input-medium giro mask-alphanum' ") ?></td>
                        </tr>
                        <tr>
                            <td><?php  echo $solicitud_ingresarsol_telefonocomercial;  ?>:&nbsp;</td>
                            <td><?php echo Form::text('cliente.telefono_cli', "class='input-medium telefono mask-alphanum'") ?></td>
                        </tr>
                        <tr>
                            <td><?php echo $solicitud_ingresarsol_selecioneplan;  ?>:&nbsp;</td>
                            <td><?php echo Form::select('cliente.tipo_plan', $data, "class='span2'") ?></td>
                        </tr>
                        <tr>
                            <td align="right" colspan="2"><?php echo $solicitud_ingresarsol_leidocondiciones;  ?>&nbsp;<?php echo Form::check('acepta', 'checkValue') ?></td>
                        </tr>
                    </table>
                </td>
                <td>
                    &nbsp;&nbsp;&nbsp;&nbsp
                </td>

                <td>
                    <h4> <center> <?php echo $solicitud_ingresarsol_seleccioncat;  ?> </center> </h4>
                    <table>
                        <tr>
                            <td><?php echo $solicitud_ingresarsol_lugarescat;  ?>: &nbsp;</td>
                            <td>
                                <div  class="btn-group" data-toggle="buttons-checkbox">
                                    <button type="button" class="btn btn-info btn-mini categoria" name="Playa" value="Playa"><?php echo $solicitud_ingresarsol_catplaya;  ?></button>
                                    <button type="button" class="btn btn-info btn-mini categoria" name="Lago" value="Lago"><?php echo $solicitud_ingresarsol_catlago;  ?></button>
                                    <button type="button" class="btn btn-info btn-mini categoria" name="Rio" value="Río"><?php echo $solicitud_ingresarsol_catrio;  ?></button>
                                    <button type="button" class="btn btn-info btn-mini categoria" name="Piscina" value="Piscina"><?php echo $solicitud_ingresarsol_catpicina;  ?></button>
                                </div>    
                            </td>
                        </tr>
                        <tr>
                            <td>&nbsp;</td>
                        </tr>
                        <tr>
                            <td><?php echo $solicitud_ingresarsol_climacat; ?> &nbsp;</td>
                            <td>
                                <div  class="btn-group" data-toggle="buttons-checkbox">
                                    <button type="button" class="btn btn-info btn-mini categoria" name="Calido" value="Calido"><?php echo $solicitud_ingresarsol_catcalido;  ?></button>
                                    <button type="button" class="btn btn-info btn-mini categoria" name="Nieve" value="Nieve"><?php echo $solicitud_ingresarsol_catnieve;  ?></button>
                                    <button type="button" class="btn btn-info btn-mini categoria" name="Lluvioso" value="Lluvioso"><?php echo $solicitud_ingresarsol_catlluvioso;  ?></button>
                                    <button type="button" class="btn btn-info btn-mini categoria" name="Templado" value="Piscina"><?php echo $solicitud_ingresarsol_cattemplado;  ?></button>
                                </div>    
                            </td>
                        </tr>
                        <tr>
                            <td>&nbsp;</td>
                        </tr>
                        <tr>
                            <td>Social: &nbsp;</td>
                            <td>
                                <div  class="btn-group" data-toggle="buttons-checkbox">
                                    <button type="button" class="btn btn-info btn-mini categoria" name="Tercera edad" value="Tercera edad"><?php echo $solicitud_ingresarsol_catterceraedad; ?></button>
                                    <button type="button" class="btn btn-info btn-mini categoria" name="Juvenil" value="Juvenil"><?php echo $solicitud_ingresarsol_catjuvenil;  ?></button>
                                    <button type="button" class="btn btn-info btn-mini categoria" name="Familiar" value="Familiar">Familiar</button>
                                </div>    
                            </td>
                        </tr>
                        <tr>
                            <td>&nbsp;</td>
                        </tr>
                        <tr>
                            <td><?php echo $solicitud_ingresarsol_deportescat;  ?>: &nbsp;</td>
                            <td>
                                <div  class="btn-group" data-toggle="buttons-checkbox">
                                    <button type="button" class="btn btn-info btn-mini categoria" name="Terrestres" value="Terrestres"><?php echo $solicitud_ingresarsol_catterrestres;  ?></button>
                                    <button type="button" class="btn btn-info btn-mini categoria" name="Extremos" value="Extremos"><?php echo $solicitud_ingresarsol_catextremos;   ?></button>
                                    <button type="button" class="btn btn-info btn-mini categoria" name="Acuaticos" value="Acuáticos"><?php echo $solicitud_ingresarsol_catacuaticos;  ?></button>
                                    <button type="button" class="btn btn-info btn-mini categoria" name="Aventura" value="Aventura"><?php echo $solicitud_ingresarsol_cataventura;  ?></button>
                                    <button type="button" class="btn btn-info btn-mini categoria" name="Fitness" value="Fitness">Fitness</button>
                                </div>    
                            </td>
                        </tr>
                        <tr>
                            <td>&nbsp;</td>
                        </tr>
                        <tr>
                            <td><?php echo $solicitud_ingresarsol_culturalcat;  ?>: &nbsp;</td>
                            <td>
                                <div  class="btn-group" data-toggle="buttons-checkbox">
                                    <button type="button" class="btn btn-info btn-mini categoria" name="Historico" value="Histórico"><?php echo $solicitud_ingresarsol_cathistorico;  ?></button>
                                    <button type="button" class="btn btn-info btn-mini categoria" name="Festivo" value="Festivo"><?php  echo $solicitud_ingresarsol_catfestivo; ?></button>
                                    <button type="button" class="btn btn-info btn-mini categoria" name="Gastronomico" value="Gastronómico"><?php echo $solicitud_ingresarsol_catgastronomico;  ?></button>
                                    <button type="button" class="btn btn-info btn-mini categoria" name="Shopping" value="Shopping">Shopping</button>
                                    <button type="button" class="btn btn-info btn-mini categoria" name="Folklore" value="Folklore">Folklore</button>
                                </div>    
                            </td>
                        </tr>
                        <tr>
                            <td>&nbsp;</td>
                        </tr>
                        <tr>
                            <td><?php echo $solicitud_ingresarsol_tecnologiacat;  ?>: &nbsp;</td>
                            <td>
                                <div  class="btn-group" data-toggle="buttons-checkbox">
                                    <button type="button" class="btn btn-info btn-mini categoria" name="WiFi" value="WiFi">WiFi</button>
                                    <button type="button" class="btn btn-info btn-mini categoria" name="TV-Cable" value="TV-Cable">Cable</button>
                                    <button type="button" class="btn btn-info btn-mini categoria" name="GTelevision" value="Televisión">TV</button>
                                    <button type="button" class="btn btn-info btn-mini categoria" name="Radio" value="Radio">Radio</button>
                                </div>    
                            </td>
                        </tr>
                        <tr>
                            <td>&nbsp;</td>
                        </tr>
                        <tr>
                            <td><?php echo $solicitud_ingresarsol_servicioscat;  ?>: &nbsp;</td>
                            <td>
                                <div  class="btn-group" data-toggle="buttons-checkbox">
                                    <button type="button" class="btn btn-info btn-mini categoria" name="Calefaccion" value="Calefacción"><?php echo $solicitud_ingresarsol_catcalefaccion;  ?></button>
                                    <button type="button" class="btn btn-info btn-mini categoria" name="Baños" value="Baños individuales"><?php $solicitud_ingresarsol_banosindividuales;  ?></button>
                                    <button type="button" class="btn btn-info btn-mini categoria" name="Duchas" value="Duchas"><?php echo $solicitud_ingresarsol_catduchas;  ?></button>
                                    <button type="button" class="btn btn-info btn-mini categoria" name="DuchasI" value="Duchas individuales"><?php echo $solicitud_ingresarsol_catduchasindividuales;  ?></button>
                                </div>    
                            </td>
                        </tr>
                        <tr>
                            <td>&nbsp</td>
                        </tr>
                        <tr>
                            <td>&nbsp</td>
                        </tr>
                        <tr>
                            <td>&nbsp</td>
                        </tr>
                        <tr>
                            <td>&nbsp</td>
                            
                        </tr>
                        <tr>
                            <td>&nbsp</td>
                        </tr>
                        <tr>
                            <td>&nbsp</td>
                        </tr>
                        
                    </table>
                </td>
            </tr>
        </table>
    </div>

    <div align="center">
        <table>
            <tr>

                <td><?php echo Form::submit($solicitud_ingresarsol_botenviarsolicitud, 'class="btn btn-submit btn-success boton"') ?>&nbsp;</td>
                <td><?php echo Form::reset($solicitud_ingresarsol_botreiniciar, 'class="btn btn-danger"') ?></td>
            </tr>         
        </table>
    </div>
    <?php echo Form::hidden('categorias', 'class="categorias_string"'); ?>
    <?php echo Form::hidden('cliente.id', null, Auth::get('id')); ?>
    <?php echo Form::hidden('cliente.username_usu', null, Auth::get('username_usu')); ?>
    <?php echo Form::hidden('cliente.visitas_cli', null, 0); ?>

    <?php echo Form::close() ?> 
</fieldset>