<!--Codigo para el idioma-->
<?php
$url = $_SERVER['REQUEST_URI'];
//devuelve los 2 ultimos caracteres de la url si es igual a en se utiliza las variables en inglés
$url = substr($url, -2);
if ($url == "en") {
    //inglés
    //variables de menu Principal
    $modificardatos_string = "My data";
    $suscripcion_string = "Solicitud de suscripción(T)";
    $buscar_solicitud_string = "Administrar solicitudes(traducir)";
    $inicio_string = "Home";
    $cuenta_string = "Account";
    $cliente_string = "Customer";
    $publicarservicio_string = "Publish service";
    $indiqueubicacion_string = "Enter your location";
    $subirfotos_string = "Upload a photo";
    $administracion_string = "Administration";
    $ingresarcliente_string = "Add customers";
    $buscarusuarios_string = "Search users";
    $enlace_home = "index/en";
    $ingresarpublicacion_string = "Publish";
    $ingresaradministrador_string = "Add administrator";
    $ingresarcategorias_string = "Add category";
    $buscardestinos_string = "Search Destination";
    $iniciarsesion_string = "Login";
    $enlace_cerrarsesion = "usuario/cerrarsesion/en";
    $cerrarsesion_string = "Logout";
    $enlace_form_login = "usuario/autenticar/en";
    $enlace_registrate = "usuario/ingresar/en";
    $registrate_string = "Create an account";
    $usuario_string = "Username";
    $contraseña_string = "Password";
    $ingresar_string = "Sign in";
    $enlace_usuario_buscar = "usuario/buscar/en";
    $enlace_usuario_publicar="publicacion/ingresar/en";
} else {
    //español
    //variables de menu Principal
    $modificardatos_string = "Mis datos";
    $buscar_solicitud_string = "Administrar solicitudes";
    $suscripcion_string = "Solicitud de suscripción";
    $inicio_string = "Inicio";
    $cuenta_string = "Cuenta";
    $cliente_string = "Cliente";
    $publicarservicio_string = "Publicar servicio";
    $indiqueubicacion_string = "Indique su ubicaci&oacute;n";
    $subirfotos_string = "Subir fotos";
    $administracion_string = "Administraci&oacute;n";
    $ingresarcliente_string = "Ingresar Cliente";
    $buscarusuarios_string = "Buscar Usuarios";
    $enlace_home = "index";
    $ingresarpublicacion_string = "Ingresar Publicaci&oacute;n";
    $ingresaradministrador_string = "Ingresar Admnistrador";
    $ingresarcategorias_string = "Ingresar Categor&iacute;a";
    $buscardestinos_string = "Buscar Destinos";
    $iniciarsesion_string = "Iniciar Sesi&oacute;n";
    $enlace_cerrarsesion = "usuario/cerrarsesion/es";
    $cerrarsesion_string = "Cerrar Sesi&oacute;n";
    $enlace_form_login = "usuario/autenticar/es";
    $enlace_registrate = "usuario/ingresar/es";
    $registrate_string = "Reg&iacute;strate";
    $usuario_string = "Usuario";
    $contraseña_string = "Contraseña";
    $ingresar_string = "Ingresar";
    $enlace_usuario_buscar = "usuario/buscar/es";
     $enlace_usuario_publicar="publicacion/ingresar/es";
}
?>

<!--CODIGO PARA BUSQUEDA -->
<?php
//$arr= Load::model('ubicacion','categoria')->find() ; 
//captura los campos necesarios de busqueda
$arr = Load::Model('ubicacion', 'cliente')->find_all_by_sql("select  distinct region_ubi from  
    ubicacion  union select distinct  ciudad_ubi from ubicacion union  select 
    distinct  nombre_cat from categoria");
?>


<script type="text/javascript"> //JQUERY PARA BUSQUEDA AJAX (autocompletado)
    $(document).ready(function()
    { 
// Charles Lawrence - Feb 16, 2012. Free to use and modify. Please attribute back to @geuis if you find this useful
// Twitter Bootstrap Typeahead doesn't support remote data querying. This is an expected feature in the future. In the meantime, others have submitted patches to the core bootstrap component that allow it. 
// The following will allow remote autocompletes *without* modifying any officially released core code. 
// If others find ways to improve this, please share.


    var autocomplete = $('#searchinput').typeahead()
        .on('keyup', function(ev){

            ev.stopPropagation();
            ev.preventDefault();

            //filter out up/down, tab, enter, and escape keys
            if( $.inArray(ev.keyCode,[40,38,9,13,27]) === -1 ){

                var self = $(this);
                
                //set typeahead source to empty
                self.data('typeahead').source = [];

                //active used so we aren't triggering duplicate keyup events
                if( !self.data('active') && self.val().length > 0){

                    self.data('active', true);

                    $.ajax
                    ({

                        type: "POST",
                        data : {
                            string: $("#searchinput").val()
                        },            
                        url: '<?php echo PUBLIC_PATH; ?>ajax/busqueda_gral_autocomplete.php',
                        dataType: "html",
                        success: function(data)
                        {
                            self.data('active',true);
                            
                            //esto para remover la ultima coma
                            data = data.slice(0,data.length-1);
                            
                            //Generamos el array separando el string por las comas
                            array_res = data.split(',');
                            
                          //CODIGO PARA Q FUNCIONE
                          //set this to true when your callback executes
                        self.data('active',true);

                        //Filter out your own parameters. Populate them into an array, since this is what typeahead's source requires
//                        var arr = [],
//                            i=data.results.length;
//                        while(i--){
//                            arr[i] = data.results[i].text
//                        }

                        //set your results into the typehead's source 
                        self.data('typeahead').source = array_res;

                        //trigger keyup on the typeahead to make it search
                        self.trigger('keyup');

                        //All done, set to false to prepare for the next remote query.
                        self.data('active', false);
                        }  // FIN SUCCESS 
                     }); //FIN AJAX


                }
            }
        });
        });
</script>

<div class="navbar navbar-inverse ">
    <div class="navbar-inner">
        <div class="container">
            <a class="brand" >Quality Tours</a>
            <ul class="nav">
                <!-- HOME -->
                <li class="">
                    <?php echo Html::link('' . $enlace_home . '', '<i class="icon-home icon-white"></i>' . $inicio_string . ''); ?>
                </li>

                <!--Menu del usuario-->
                <?php
                    if (Auth::is_valid()) {
                        if (Session::get('rol_usu') == 'turista') {
                ?>
                <li class="dropdown">
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                        <i class="icon-wrench icon-white"></i> 
                        <?php echo $cuenta_string; ?>
                        <b class="caret"></b>
                    </a>
                    <ul class="dropdown-menu">
                        <li><?php echo Html::link('usuario/automodificar/', '<i class="icon-file"></i>' . $modificardatos_string . ''); ?></li>
                        <li><?php echo Html::link('cliente/ingresarsolicitud/', '<i class="icon-thumbs-up"></i>' . $suscripcion_string . ''); ?></li>
                        <li><?php echo Html::link('solicitud/vertodas/'.Auth::get("id"), '<i class="icon-eye-open"></i>Solicitudes anteriores(t)'); ?></li>
                    </ul>
                </li>
                <?php
                        }
                    }
                ?>

                <!--Menu del cliente-->
                <?php
                if (Auth::is_valid()) {
                    if (Session::get('rol_usu') == 'cliente') {
                        ?>
                        <li class="dropdown">
                            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                                <i class="icon-asterisk icon-white"></i> 
                                <?php echo $cliente_string; ?>
                                <b class="caret"></b>
                            </a>
                            <ul class="dropdown-menu">
                                <li><?php echo Html::link('servicio/ingresar/', '<i class="icon-plus"></i>' . $publicarservicio_string . ''); ?></li>
                                <li><?php echo Html::link('ubicacion/ingresar/', '<i class="icon-screenshot"></i>' . $indiqueubicacion_string . ''); ?></li>
                                <li><?php echo Html::link('contenido/ingresarcli/', '<i class="icon-camera"></i>' . $subirfotos_string . ''); ?></li>
                            </ul>
                        </li>
                 <?php
                    }
                 }
                ?>

                <!--Panel de administración-->
                <?php
                if (Auth::is_valid()) {
                    if (Session::get('rol_usu') == 'administrador') {
                        ?>
                        <li class="dropdown">
                            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                                <i class="icon-tasks icon-white"></i> 
                                <?php echo $administracion_string; ?>
                                <b class="caret"></b>
                            </a>
                            <ul class="dropdown-menu">
                                <li><?php echo Html::link('solicitud/buscar/', '<i class="icon-briefcase"></i> ' . $buscar_solicitud_string . ''); ?></li>
                                <li><?php echo Html::link('' . $enlace_usuario_buscar . '', '<i class="icon-search"></i> ' . $buscarusuarios_string . ''); ?></li>
                                <li><?php echo Html::link(''.$enlace_usuario_publicar.'', '<i class="icon-upload"></i> ' . $ingresarpublicacion_string . ''); ?></li>
                                <li><?php echo Html::link('categoria/ingresar', '<i class="icon-plus"></i> ' . $ingresarcategorias_string . ''); ?></li>
                            </ul>
                        </li>
                <?php
                    }
                }
                ?>
            </ul>
<!--Fin menus usuario, cliente y administrador-->

<!--Banderas-->
            <ul class="nav pull-right">
            <?php
            $url = $_SERVER['REQUEST_URI'];
            if ($url == "/trunk/qualitytours/" || $url == "/trunk/qualitytours/index/?l=en" || $url == "/trunk/qualitytours/index/" || $url == "/trunk/qualitytours/index" || $url == "trunk/qualitytours") {
            ?>
                
            <?php if (!Auth::is_valid()) 
                { 
            ?>
                <li> <?php echo Html::link('index', "<img src='/trunk/qualitytours/img/1351461465_es.png'>"); ?></li>
                <li> <?php echo Html::link('index/en', "<img src='/trunk/qualitytours/img/1351461500_gb.png'>"); ?></li>

            <?php
                 } 
                 else 
                 {
            ?>
                    <li> <?php echo Html::link('usuario/leng/es', "<img src='/trunk/qualitytours/img/1351461465_es.png'>"); ?></li>
                    <li> <?php echo Html::link('usuario/leng/en', "<img src='/trunk/qualitytours/img/1351461500_gb.png'>"); ?></li>
           <?php } ?>

<?php
} else {
    ?>
                    <?php $url = substr($url, 0, -2); ?>
                    <li> <?php echo "<a href='" . $url . "es'><img src='/trunk/qualitytours/img/1351461465_es.png'></a>"; ?> </li>
                    <li> <?php echo "<a href='" . $url . "en'><img src='/trunk/qualitytours/img/1351461500_gb.png'></a>"; ?></li>
                <?php } ?>

<!--Fin banderas-->

<!-- CAMPO DE BUSQUEDA-->
                <?php echo Form::open("busqueda/buscando/", 'post', 'class=navbar-search'); ?>
                    <?php // echo Form::text("ciudad","class='search-query span2' placeholder='Buscar destinos' data-provide='typeahead' ");   ?>
                
                    <i class="icon-search icon-white"></i>
                    <input id="searchinput" name="ciudad" type="text" value="" class='search-query span2 busqueda' placeholder='<?php echo $buscardestinos_string; ?>' data-provide='typeahead' >  

                    <!-- <input type="text" id="ciudad" class="search-query span2" placeholder="Buscar destinos" data-provide="typeahead" class="search-query">-->
                <?php echo Form::close() ?>

<!-- FIN CAMPO DE BUSQUEDA-->

<!-- MENU INICIO/CIERRE DE SESION-->
                <li class="dropdown">
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                        <?php
                        if (Auth::is_valid()) {
                            echo '<i class="icon-user icon-white"></i> ';
                            echo Auth::get('username_usu');
                        } else {
                            echo $iniciarsesion_string;
                        }
                        ?>
                        <b class="caret"></b>
                    </a>
                    <ul class="dropdown-menu">
                 
                    <li>
                    <?php
                    //Si el user esta loguedao se mostrará la opción para cerrar sesión en el menu desplegable
                    if (Auth::is_valid()) {
                        echo "<li>";
                        echo Html::link('' . $enlace_cerrarsesion . '', '<i class="icon-off"></i> ' . $cerrarsesion_string);
                        echo "</li>";
                    } else { //Si no esta logueado se mostrará el form para iniciar sesión
                    ?>
                        <?php echo Form::open('' . $enlace_form_login . '', 'post', 'class=navbar-form'); ?>
                        <center>
                        <?php echo $usuario_string; ?>
                        <?php echo Form::text("username_usu", "class='span2'"); ?>
                        <?php echo $contraseña_string; ?>
                        <?php echo Form::pass("password_usu", "class='span2'"); ?>
                        <?php echo Form::submit('' . $ingresar_string . '', "class='btn btn-primary'"); ?>
                        <br><hr>
               
                    <li><?php echo Html::link('' . $enlace_registrate . '', $registrate_string . ' <i class="icon-plus-sign"></i>'); ?></li>
                        </center>
                             </form> 
                        <?php } ?>

                      </li>
                    </ul>
                </li>
            </ul>
        </div>
    </div>
</div>