<!--Codigo para el idioma-->

<?php
echo Tag::js('jquery.keyfilter');

$url = $_SERVER['REQUEST_URI'];
//devuelve los 2 ultimos caracteres de la url si es igual a en se utiliza las variables en inglés
$url = substr($url, -2);
if ($url == "en") {
    $leng = "en";
    //inglés
    //variables de menu Principal
    $modificardatos_string = "My data";
    $suscripcion_string = "Suscription request";
    $buscar_solicitud_string = "Request management";
    $inicio_string = "Home";
    $cuenta_string = "Account";
    $cliente_string = "Customer";
    $publicarservicio_string = "Publish service";
    $indiqueubicacion_string = "Enter your location";
    $subirfotos_string = "Upload a photo";
    $administracion_string = "Administration";
    $ingresarcliente_string = "Add customers";
    $buscarusuarios_string = "Search users";
    $enlace_home = "index/en";
    $ingresarpublicacion_string = "Add publication";
    $ingresaradministrador_string = "Add administrator";
    $ingresarcategorias_string = "Add category";
    $buscardestinos_string = "Search Destination";
    $iniciarsesion_string = "Login";
    $enlace_cerrarsesion = "usuario/cerrarsesion/en";
    $cerrarsesion_string = "Logout";
    $enlace_form_login = "usuario/autenticar/en";
    $enlace_registrate = "usuario/ingresar/en";
    $registrate_string = "Create an account";
    $usuario_string = "Username";
    $contraseña_string = "Password";
    $ingresar_string = "Sign in";
    $enlace_usuario_buscar = "usuario/buscar/en";
    $enlace_usuario_publicar = "publicacion/ingresar/en";
    $ingresar_traductor_string = "Add translator";
    $tu_pagina = "Your page";
    $enlace_olvido = "Forgot your password?";
    $administrar_suscripcion_string = "Suscription info";
    
    } else {
    $leng = "es";
    //español
    //variables de menu Principal
    $ingresar_traductor_string = "Agregar traductor";
    $modificardatos_string = "Mis datos";
    $buscar_solicitud_string = "Administrar solicitudes";
    $suscripcion_string = "Solicitud de suscripción";
    $inicio_string = "Inicio";
    $cuenta_string = "Cuenta";
    $cliente_string = "Cliente";
    $publicarservicio_string = "Publicar servicio";
    $indiqueubicacion_string = "Indique su ubicaci&oacute;n";
    $subirfotos_string = "Subir fotos";
    $administracion_string = "Administraci&oacute;n";
    $ingresarcliente_string = "Ingresar Cliente";
    $buscarusuarios_string = "Buscar Usuarios";
    $enlace_home = "index";
    $ingresarpublicacion_string = "Ingresar Publicaci&oacute;n";
    $ingresaradministrador_string = "Ingresar Admnistrador";
    $ingresarcategorias_string = "Ingresar Categor&iacute;a";
    $buscardestinos_string = "Buscar Destinos";
    $iniciarsesion_string = "Iniciar Sesi&oacute;n";
    $enlace_cerrarsesion = "usuario/cerrarsesion/es";
    $cerrarsesion_string = "Cerrar Sesi&oacute;n";
    $enlace_form_login = "usuario/autenticar/es";
    $enlace_registrate = "usuario/ingresar/es";
    $registrate_string = "Reg&iacute;strate";
    $usuario_string = "Usuario";
    $contraseña_string = "Contraseña";
    $ingresar_string = "Ingresar";
    $enlace_usuario_buscar = "usuario/buscar/es";
    $enlace_usuario_publicar = "publicacion/ingresar/es";
    $tu_pagina = "Tu p&aacute;gina";
    $enlace_olvido = "¿Olvid&oacute; su clave?";
    $administrar_suscripcion_string = "Datos de suscripci&oacute;n";
}
?>



<script type="text/javascript"> //JQUERY PARA BUSQUEDA AJAX (autocompletado)
    $(document).ready(function()
    { 
        //VALIDACION COMILLAS FORM LOGIN
        $(".botonlogin").click(function(){
            $(".login_usu").val( $(".login_usu").val().replace(/[^a-z0-9\s]/gi,"") );
            $(".login_pass").val( $(".login_pass").val().replace(/[^a-z0-9\s]/gi,"") );
        });
        
        // TYPEAHEAD
        var autocomplete = $('#searchinput').typeahead()
        .on('keyup', function(ev){

            ev.stopPropagation();
            ev.preventDefault();

            //filter out up/down, tab, enter, and escape keys
            if( $.inArray(ev.keyCode,[40,38,9,13,27]) === -1 ){

                var self = $(this);
                
                //set typeahead source to empty
                self.data('typeahead').source = [];

                //active used so we aren't triggering duplicate keyup events
                if( !self.data('active') && self.val().length > 0){

                    self.data('active', true);

                    $.ajax
                    ({

                        type: "POST",
                        data : {
                            string: $("#searchinput").val(),
                            leng: '<?php echo $leng ?>'
                        },            
                        url: '<?php echo PUBLIC_PATH; ?>ajax/busqueda_gral_autocomplete.php',
                        dataType: "html",
                        success: function(data)
                        {
                            self.data('active',true);
                            
                            //esto para remover la ultima coma
                            data = data.slice(0,data.length-1);
                            
                            //Generamos el array separando el string por las comas
                            array_res = data.split(',');
                            
                            //CODIGO PARA Q FUNCIONE
                            //set this to true when your callback executes
                            self.data('active',true);

                            //Filter out your own parameters. Populate them into an array, since this is what typeahead's source requires
                            //                        var arr = [],
                            //                            i=data.results.length;
                            //                        while(i--){
                            //                            arr[i] = data.results[i].text
                            //                        }

                            //set your results into the typehead's source 
                            self.data('typeahead').source = array_res;

                            //trigger keyup on the typeahead to make it search
                            self.trigger('keyup');

                            //All done, set to false to prepare for the next remote query.
                            self.data('active', false);
                        }  // FIN SUCCESS 
                    }); //FIN AJAX


                }
            }
        });
        // AJAX PARA LAS NOTIFICACIONES
        $.ajax
        ({
            
            type: "POST",        
            url: '<?php echo PUBLIC_PATH; ?>ajax/notificaciones.php',
            dataType: "json",
            success: function(data)
            {
                if (data != null && data.length > 0)
                {
                    if (data[2]['datos'] != 0)
                    {$("#pen_sol").after("<span class='notifi'>" + data[2]['datos'] +"</span>");}
                    if(data[0]['datos'] != 0)
                    {$("#mail_sol").after("<span class='notifi'>" + data[0]['datos'] +"</span>");}
                    if(data[1]['datos'] != 0)
                    {$("#modi_sol").after("<span class='notifi'>" + data[1]['datos'] +"</span>");}
                    if(data[3]['datos'] != 0)
                    {$("#eli_sus").after("<span class='notifi'>" + data[3]['datos'] +"</span>");}
                }
                else 
                {
                }
            } // cierre success
            
            //DESCOMENTAR LA SIGUIENTE LINEA SI QUEREEMOS VER ALERTS SI HAY ERROR EN LA SOLICITUD AJAX
            //,error: function (xhr, ajaxOptions, thrownError){alert(xhr.status+' '+thrownError);}
        });
    });
</script>

<div class="navbar navbar-inverse ">
    <div class="navbar-inner">
        <div class="container">
            <?php if (!Auth::is_valid()){ echo "<a class='brand' >Quality Tours</a>";} else if (Auth::get("rol_usu")== "turista" || Auth::get("rol_usu")== "cliente" || Auth::get("rol_usu")== "traductor" ) {echo "<a class='brand' >Quality Tours</a>";} ?>

            <ul class="nav">
                <!-- HOME -->
                <li class="">
                    <?php echo Html::link('' . $enlace_home . '', '<i class="icon-home icon-white"></i>' . $inicio_string . ''); ?>
                </li>

                <!--Menu del usuario-->
                <?php
                if (Auth::is_valid()) {
                    if (Session::get('rol_usu') == 'turista') {
                        ?>
                        <li class="dropdown">
                            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                                <i class="icon-wrench icon-white"></i> 
                                <?php echo $cuenta_string; ?>
                                <b class="caret"></b>
                            </a>
                            <ul class="dropdown-menu">
                                <li><?php echo Html::link('usuario/automodificar/' . $leng, '<i class="icon-file"></i>' . $modificardatos_string . ''); ?></li>
                                <li><?php echo Html::link('cliente/ingresarsolicitud/', '<i class="icon-thumbs-up"></i>' . $suscripcion_string . ''); ?></li>
                                <li><?php echo Html::link('solicitud/vertodas/' . Auth::get("id"), '<i class="icon-eye-open"></i>Solicitudes anteriores(t)'); ?></li>
                            </ul>
                        </li>
                        <?php
                    }
                }
                ?>
                <!--Menu del traductor-->
                <?php
                if (Auth::is_valid()) {
                    if (Session::get('rol_usu') == 'traductor') {
                        ?>
                        <li class="dropdown">
                            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                                <i class="icon-wrench icon-white"></i> 
                                Traductor
                                <b class="caret"></b>
                            </a>
                            <ul class="dropdown-menu">
                                <li><?php echo Html::link('publicacion/traduct/' . $leng, '<i class="icon-file"></i>&nbsp;Traducir Publicaciones'); ?></li>
                                <li><?php echo Html::link('servicio/traduct/' . $leng, '<i class="icon-file"></i>&nbsp;Traducir servicios'); ?></li>
                            </ul>
                        </li>
                        <?php
                    }
                }
                ?>

                <!--Menu del cliente-->
                <?php
                if (Auth::is_valid()) {
                    if (Session::get('rol_usu') == 'cliente') {
                        ?>
                        <li class="dropdown">
                            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                                <i class="icon-asterisk icon-white"></i> 
                                <?php echo $cliente_string; ?>
                                <b class="caret"></b>
                            </a>
                            <ul class="dropdown-menu">
                                <li><?php echo Html::link('cliente/administrarsuscripcion/'.$leng, '<i class="icon-user"></i>' . $administrar_suscripcion_string . ''); ?></li>
                                <li><?php echo Html::link('servicio/ingresar/' . $leng, '<i class="icon-plus"></i>' . $publicarservicio_string . ''); ?></li>
                                <li><?php echo Html::link('ubicacion/ingresar/' . $leng, '<i class="icon-screenshot"></i>' . $indiqueubicacion_string . ''); ?></li>
                                <li><?php echo Html::link('contenido/ingresarcli/' . $leng, '<i class="icon-camera"></i>' . $subirfotos_string . ''); ?></li>
                            </ul>
                        </li>
                        <li><?php echo Html::link('cliente/detalle/'.Auth::get("id").'/'. $leng, '<i class="icon-globe icon-white"></i>&nbsp;'.$tu_pagina); ?></li>
                        <?php
                    }
                }
                ?>

                <!--Panel de administración-->
                <?php
                if (Auth::is_valid()) {
                    if (Session::get('rol_usu') == 'administrador') {
                        ?>

                        <li class="dropdown">
                            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                                <i class="icon-tasks icon-white"></i> 
                                <?php echo $administracion_string; ?>
                                <b class="caret"></b>
                            </a>
                            <ul class="dropdown-menu">
                                <li><?php echo Html::link('solicitud/buscar/' . $leng, '<i class="icon-briefcase"></i> ' . $buscar_solicitud_string . ''); ?></li>
                                <li><?php echo Html::link('' . $enlace_usuario_buscar . '', '<i class="icon-search"></i> ' . $buscarusuarios_string . ''); ?></li>
                                <li><?php echo Html::link('' . $enlace_usuario_publicar . '', '<i class="icon-upload"></i> ' . $ingresarpublicacion_string . ''); ?></li>
                                <li><?php echo Html::link('usuario/ingresart/' . $leng, '<i class="icon-plus"></i> ' . $ingresar_traductor_string); ?></li>
                            </ul>
                        </li>
                        <li>
                            <?php echo Html::link('administrador/notificaciones/pendiente/' . $leng, '<i id="pen_sol" class="icon-exclamation-sign icon-white"></i>') ?>
                        </li>
                        <li>
                            <?php echo Html::link('administrador/notificaciones/mail/' . $leng, '<i id="mail_sol" class="icon-envelope icon-white"></i>') ?>
                        </li>
                        <li>
                            <?php echo Html::link('administrador/notificaciones/modificacion/' . $leng, '<i id="modi_sol" class="icon-edit icon-white"></i>') ?>
                        </li>
                        <li>
                            <?php echo Html::link('administrador/revocar/eliminacion/' . $leng, '<i id="eli_sus" class="icon-remove-sign icon-white"></i>') ?>
                        </li>
                        <?php
                    }
                }
                ?>
            </ul>
            <!--Fin menus usuario, cliente y administrador-->

            <!--Banderas-->
            <ul class="nav pull-right">
                <?php
                $url = $_SERVER['REQUEST_URI'];
                if ($url == "/trunk/qualitytours/" || $url == "/trunk/qualitytours/index/?l=en" || $url == "/trunk/qualitytours/index/" || $url == "/trunk/qualitytours/index" || $url == "trunk/qualitytours") {
                    ?>

                    <?php
                    if (!Auth::is_valid()) {
                        ?>
                        <li> <?php echo Html::link('index', "<img src='/trunk/qualitytours/img/1351461465_es.png' alt='Spanish'>"); ?></li>
                        <li> <?php echo Html::link('index/en', "<img src='/trunk/qualitytours/img/1351461500_gb.png' alt='English'>"); ?></li>

                        <?php
                    } else {
                        ?>
                        <li> <?php echo Html::link('usuario/leng/es', "<img src='/trunk/qualitytours/img/1351461465_es.png' alt='Spanish'>"); ?></li>
                        <li> <?php echo Html::link('usuario/leng/en', "<img src='/trunk/qualitytours/img/1351461500_gb.png' alt='English'>"); ?></li>
                    <?php } ?>

                    <?php
                } else {
                    ?>
                    <?php $url = substr($url, 0, -2); ?>
                    <li> <?php echo "<a href='" . $url . "es'><img src='/trunk/qualitytours/img/1351461465_es.png' alt='Spanish'></a>"; ?> </li>
                    <li> <?php echo "<a href='" . $url . "en'><img src='/trunk/qualitytours/img/1351461500_gb.png' alt='English'></a>"; ?></li>
                <?php } ?>

                <!--Fin banderas-->

                <!-- CAMPO DE BUSQUEDA-->
                <?php echo Form::open("busqueda/buscando/" . $leng, 'post', 'class=navbar-search'); ?>
                <i class="icon-search icon-white"></i>
                <input id="searchinput" name="string" type="text" value="" class='search-query span2 busqueda  mask-alphanum' placeholder='<?php echo $buscardestinos_string; ?>' data-provide='typeahead' >  
                <?php echo Form::close() ?>

                <!-- FIN CAMPO DE BUSQUEDA-->

                <!-- MENU INICIO/CIERRE DE SESION-->
                <li class="dropdown">
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                        <?php
                        if (Auth::is_valid()) {
                            echo '<i class="icon-user icon-white"></i> ';
                            echo Auth::get('username_usu');
                        } else {
                            echo $iniciarsesion_string;
                        }
                        ?>
                        <b class="caret"></b>
                    </a>
                    <ul class="dropdown-menu">

                        <li style="text-align: center; ">
                            <?php
//Si el user esta loguedao se mostrará la opción para cerrar sesión en el menu desplegable
                            if (Auth::is_valid()) {
                                echo "<li>";
                                echo Html::link('' . $enlace_cerrarsesion . '', '<i class="icon-off"></i> ' . $cerrarsesion_string);
                                //echo "</li>";
                            } else { //Si no esta logueado se mostrará el form para iniciar sesión
                                ?>
                                <?php echo Form::open('' . $enlace_form_login . '', 'post', 'class=navbar-form'); ?>
                            
                                <?php echo $usuario_string; ?>
                                <?php echo Form::text("username_usu", "class='span2 mask-alphanum login_usu'"); ?>
                                <?php echo $contraseña_string; ?>
                                <?php echo Form::pass("password_usu", "class='span2 mask-alphanum login_pass'"); ?>
                                <?php echo Form::submit('' . $ingresar_string . '', "class='btn btn-primary botonlogin'"); ?>
                            </form>     
                            <br>
                                <?php echo Html::link("usuario/olvidar/" . $leng, $enlace_olvido,"style='font-size: 10px;'"); ?>
                                <hr>
                                    
                                <li style="text-align: center; "><?php echo Html::link('' . $enlace_registrate . '', $registrate_string . ' <i class="icon-plus-sign"></i>'); ?></li>
                            
                            
                        <?php } ?>

                
            </ul>
            </li>
            </ul>
        </div>
    </div>
</div>