<div><?php View::content()?></div> 

<script type="text/javascript">
    $(document).ready(function () 
    {
        $("#buscaCentro").keyup(function()
        {
            if ($("#buscaCentro").val() != "")
                {
                    $.ajax
                    ({
                        url: '<?php echo PUBLIC_PATH; ?>ajax/cliente_busqueda.php?string='+$("#buscaCentro").val(),
                        type: "POST",
                        dataType: "json",
                        success: function(data)
                        {
                                //console.log(data[0]['id_usu']);
                                if (data != null && data.length > 0)
                                {
                                    var count = data.length;
                                    var i = 0;
                                    $("#categoria_id_usu").empty();
                                    while (i < count)
                                        {
                                            $("#categoria_id_usu").append('<option value="'+data[i]['id_usu']+'">'+data[i]['nombre_cli']+'</option>');
                                            i++;
                                        }
                                }
                                else
                                {
                                    $("#categoria_id_usu").empty();
                                    $("#categoria_id_usu").append('<option value="0" selected="selected">No se encontraron resultados</option>');
                                }
                        } // cierre success
                    }); //cierre ajax
                } //Cierre If
                else
                {
                    $("#categoria_id_usu").empty();
                    $("#categoria_id_usu").append('<option value="0" selected="selected>No se encontraron resultados</option>');
                }
        }); //Cierre keyup
        
        $(".submit").click(function()
        {
            //VALIDACION QUE SELECCIONE UN CENTRO TURISTICO
            if ($("#categoria_id_usu").val() == "0")
            {
                alert('Seleccione centro turistico');
                return false;
            }
            //VALIDACION QUE INGRESE UNA CATEGORIA
            if ($("#categoria_nombre_cat").val() == "")
            {
                alert('Ingrese categoria');
                return false;
            }
        });
        
    }); //Cierre Jquery
        
</script>

<div align="center">
    
    <h1>Clasificar centros turísticos</h1>
     <?php echo Form::open('categoria/ingresar') ?>
    <table>
        <tr>
            <td>Nombre a buscar:&nbsp;</td>
            <td><?php echo Form::text('buscaCentro')?></td>
        </tr>
        <tr>
            <td>Seleccione centro turístico:&nbsp;</td>
            <td><?php echo "<select id='categoria_id_usu' size='9' name='categoria[id_usu]'><option value='0' selected='selected'></option></select>"?></td>
        </tr>
        <tr>
            <td>Nombre Categoría:&nbsp;</td>
            <td><?php echo Form::text("categoria.nombre_cat"); ?></td>
        </tr>
    </table>
    <table>
        <tr>
            <td><?php echo Form::submit('Ingresar Categor&iacute;a', 'class="btn btn-primary submit"') ?></td>
        </tr>
    </table>
    
    <?php echo Form::hidden('categoria.estado_cat',null,1)?>
    <?php echo Form::close();?>
</div>   
