
<!-- captura de id  del usuario para enviarlo al controlador       -->
<?php $id =  Auth::get('id'); 
//captura del id de la publicacion
  $id_pub= $id_pub;
  
  echo  "usuario".$id."<br>";
  echo  "publicacion".$id_pub;
?>

<div align="center">
    <h1>Ingresar Contenido</h1>
    <table>
        <tr>
            <td>  <?php echo Form::openMultipart('contenido/admincont') ?>
                  Ingrese una imagen .jpg , .gif ó .png :
                  <?php echo Form::file("imagen","class='btn btn-info'") ?>
                  <?php //echo Form::hidden('oculto') //para saber si se envió el form ?>
                  
                  <?php echo Form::hidden('contenido.id_pub',null , $id_pub); ?>
                  <?php echo Form::hidden('contenido.id_usu',null , $id); ?>
                  <?php echo Form::hidden('contenido.tipo_con',null ,"imagen"); ?>
                  
              
            </td>      
            
        </tr>
      </table>
       <table>    
        <tr>
            <td>fecha:</td>
            <td><?php echo Calendar::text('contenido.fecha_con','class="calendario"') ?></td>
        </tr>
        <tr>
            <td>Nombre:</td>
            <td><?php  echo Form::text('contenido.nombre_con','class="nombre"') ?></td>
        </tr>
        <tr>
            <td>  
                <div align="center"> <?php echo  Form::submit('subir','class="btn btn-submit boton" ')  ?></div>
                  <?php echo Form::close() ?>
            </td>
        </tr>
         
        
    </table>
</div>
<br>

