<!--Estilos para mensajes y errores de validación-->

<style>
    .mensajeVal{
    background-color: #4AC948;
    padding: 6px 12px;
    border-radius: 4px;
    color: white;
    font-weight: bold;
    margin-left: 16px;
    margin-top: 6px;
    position: absolute;
}
    .mensajeVal:before{ /* Este es un truco para crear una flechita */
    content: '';
    border-top: 8px solid transparent;
    border-bottom: 8px solid transparent;
    border-right: 8px solid #BC1010;
    border-left: 8px solid transparent;
    left: -16px;
    position: absolute;
    top: 5px;
}
    .errorVal{
    background-color: #BC1010;
    padding: 6px 12px;
    border-radius: 4px;
    color: white;
    font-weight: bold;
    margin-left: 16px;
    margin-top: 6px;
    position: absolute;
}
.errorVal:before{ /* Este es un truco para crear una flechita */
    content: '';
    border-top: 8px solid transparent;
    border-bottom: 8px solid transparent;
    border-right: 8px solid #BC1010;
    border-left: 8px solid transparent;
    left: -16px;
    position: absolute;
    top: 5px;
}
</style>

<!--PARA GOOGLE MAPS COMIENZO-->
<style type="text/css">
  html { height: 100% }
  body { height: 100%; margin: 0px; padding: 0px }
  #map_canvas { height: 100% }
</style>

<meta name="viewport" content="initial-scale=1.0, user-scalable=yes" />

<script type="text/javascript" src="https://maps.google.com/maps/api/js?sensor=false">
//Esto carga el api de Google Maps
</script>

<script type="text/javascript">
//Este código carga el mapa en santiago cuando el html se ha terminado
//de ejecutar completamente
//FUNCTION INITIALIZE
var map;
var markersArray = [];
$(document).ready(function(){
    
    //Ocultamos el boton de obtener direccion e inhabilitamos campos
    $(".json-direccion, .submit, .advertencia, .tr_direccion, .tr_ciudad, .tr_region, .advertencia_json").hide();
    $(".direccion, .ciudad, .region").attr('readonly','readonly');

    //Setup del mapa
    var myOptions = {
          zoom: 8,
          center: new google.maps.LatLng(-33.45, -70.66),
          mapTypeId: google.maps.MapTypeId.ROADMAP
        };
    map = new google.maps.Map(document.getElementById('map_canvas'),
            myOptions);
      
   
    google.maps.event.addListener(map, 'click', function(event) {  //Al hacer click en el mapa...
    
    //AÑADIMOS EL MARCADOR
    addMarker(event.latLng);
    
    //Habilitamos el boton obtener dirección
    if ( $(".direccion").val() == "" ) $(".json-direccion, .advertencia_json").show();
    
    //Modificamos los campos de latitud y longitud
    document.getElementById("ubicacion_latitud_ubi").value = event.latLng.lat();
    document.getElementById("ubicacion_longitud_ubi").value = event.latLng.lng();
    
    }); //Fin al hacer click en el mapa
  
});
</script>




<script type="text/javascript"> //OBTENCION DE LA DIRECCION BOTON OBTENER DIRECCION
    $(document).ready(function(){
        //Al presionar el boton se ejecutará lo siguiente
        $(".json-direccion").click(function (){
            
            //Obtenemos las coordenadas del marcador
            var lat =  document.getElementById("ubicacion_latitud_ubi").value;
            var lng =  document.getElementById("ubicacion_longitud_ubi").value;
            
            //Dandole formato a nuestras coordenadas
            var latlng = new google.maps.LatLng(lat,lng);
            
            //Consultamos la dirección de nuestras coordenadas
            var geocoder = new google.maps.Geocoder();
            geocoder.geocode( {'latLng': latlng },
            function(data, status) 
            { 
                //0 - Lineas de ayuda para la codificacion (luego comentarlas)
                //console.log(data); //Linea para analizar el objeto que devuelve
                //$(".tablaform").after("<br>"+data[0].formatted_address); 
                
                //1 - Actualizar value de direccion
                if (data[0].address_components.length > 6 )
                    $(".direccion").val(data[0].address_components[1].long_name+' '+data[0].address_components[0].long_name);
                else
                    $(".direccion").val(data[0].address_components[0].long_name);
                
                //2 - Actualizar value de ciudad
                $(".ciudad").val(data[1].address_components[0].long_name);
                    
                //3 - Actualizar value de la región
                $(".region").val(data[4].address_components[0].long_name);
                
                //4 - Limitamos el uso del boton a una vez escondiéndolo
                $(".json-direccion, .advertencia_json").hide();

                //5 - Mostramos el botón submit y su advertencia
                $(".submit, .advertencia, .tr_direccion, .tr_ciudad, .tr_region").show();
            });


        });
    });

</script>

<script type="text/javascript">
    //MANEJO DE MARCADORES EN EL MAPA

function addMarker(location) {
        deleteOverlays(); //LIMPIAMOS MARCADORES ANTERIORES
        marker = new google.maps.Marker({
            position: location,
            map: map,
            title:"<?php echo $nombre_cliente ?>"
        });
       
        markersArray.push(marker); 
        
    }
    
    //LIMPIA EL ARRAY DE MARCADORES
    function deleteOverlays() {
    if (markersArray) {
        for (i in markersArray) {
            markersArray[i].setMap(null);
        }
        markersArray.length = 0;
    }
      
}
    
</script>
<!--FIN CODIGO PARA GOOGLE MAPS-->
<?php echo Form::open('ubicacion/ingresar') ?>
<fieldset>
    <div align="center">
        <table>
            <tr>
                <td>Centro turístico:&nbsp;</td>
                <td><?php echo $nombre_cliente; ?></td>
            </tr>
        </table>
        <br><h6>Indique la ubicación de su destino turístico</h6>
        
        <div id="map_canvas" style="width:400px; height:400px"></div>
        <br>
        <table class="tablaform">
            <tr>
                <td><?php echo Form::hidden('ubicacion.latitud_ubi','class="latitud" placeholder=" l a t i t u d "','')?></td>
                <td><?php echo Form::hidden('ubicacion.longitud_ubi','class="longitud" placeholder=" l o n g i t u d "','')?></td>
            </tr>
            <tr class="tr_direccion">
                <td>Dirección:&nbsp;</td>
                <td><?php echo Form::text('ubicacion.direccion_ubi','class="direccion" ','')?></td>
            </tr>
            <tr class="tr_ciudad">
                <td>Ciudad:&nbsp;</td>
                <td><?php echo Form::text('ubicacion.ciudad_ubi','class="ciudad" ','')?></td>
            </tr>
            <tr class="tr_region">
                <td>Regi&oacute;n:&nbsp;</td>
                <td><?php echo Form::text('ubicacion.region_ubi','class="region" ','')?></td>
            </tr>
            <tr>
                <td colspan="2"><center>
                    <p class="advertencia_json"><i>Obtener la dirección de su marcador en el mapa</i></p>
                    <?php echo Form::button('Obtener direccion','class="json-direccion btn btn-success"')?>
                </center></td>
            </tr>
            <tr>
                <td colspan="2"><center>
                    <p class="advertencia"><i>Verifique los datos antes de ingresar su ubicación</i></p>
                    <?php echo Form::submit('Confirmar ubicación', 'class="btn btn-primary submit"') ?>&nbsp;
                </center></td>
            </tr> 
        </table>
        
        <?php echo Form::hidden('ubicacion.id_usu','',$id_usu)?>
        
                
    </div>
</fieldset>
<?php echo Form::close() ?>     
    
